---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 'what"s new' 
summary: In diesem Thema werden Änderungen in den neuesten Versionen von SANtricity System Manager des CLI-Befehls und Skripts aufgeführt. 
---
= Was ist neu
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In diesem Thema werden Änderungen in den neuesten Versionen von SANtricity System Manager des CLI-Befehls und Skripts aufgeführt.

[NOTE]
====
Wenn Sie SMcli-Befehle an der Eingabeaufforderung eingeben, müssen Sie einen zusätzlichen umgekehrten Schrägstrich eingeben (`\`) Zeichen als Escape-Zeichen im Dateipfadnamen einer ein- oder Ausgabedatei bei Verwendung des Windows-Betriebssystems. Der zusätzliche umgekehrter Schrägstrich (`\`) Muss bei der Verwendung von SMcli im sicheren HTTPS-Modus enthalten sein, indem die Option -U zur Angabe eines Benutzer für die rollenbasierte Zugriffsverwaltung bereitgestellt wird. Beispiel: `C:\\dir\\subdir\\filename`

====
[NOTE]
====
Wenn Sie derzeit SANtricity 11.52 oder eine frühere Version verwenden, können Sie kein Upgrade auf die neueste Version von SANtricity über die alte CLI durchführen. Upgrades von SANtricity 11.52 auf neuere Versionen können nur über SMcli durchgeführt werden.

====


== SANtricity 11.90

Die folgende Tabelle führt Änderungen an den CLI- und Skriptbefehlen für Version 11.90 auf.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html["Legen Sie die maximale AutoSupport-Entsendungsgröße fest"]
 a| 
Befehl hinzugefügt



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html["Speichern Sie die ControllerarrayManagementCSR"]
 a| 
Parameter hinzugefügt `KeySize`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-email-smtp-delivery-method.html["Legen Sie die E-Mail-Bereitstellungsmethode (SMTP) fest"]
 a| 
Parameter hinzugefügt `destinationAddress`.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples["AutoSupport-Einstellungen anzeigen"]
 a| 
Größenbeschränkungen für Entsendung und Ziel-E-Mail-Adressen wurden der Beispielausgabe für den Befehl hinzugefügt.



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html["Laden Sie storageArray keyManagementCertificate herunter"]
 a| 
Parameter hinzugefügt `privateKeyFile`.

|===


== SANtricity 11.81

Die folgende Tabelle führt Änderungen an den CLI- und Skriptbefehlen für Version 11.81 auf.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices["Geräte identifizieren"]
 a| 
Hinzugefügt `identifyDevices` Parameter.

|===


== SANtricity 11.80

Die folgende Tabelle führt Änderungen an den CLI- und Skriptbefehlen für Version 11.80 auf.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[Speichern Sie Paritätsfehler bei der Volume-Paritätsprüfung]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/start-check-vol-parity-job.adoc[Starten Sie die Überprüfung des Volume Parity Jobs]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[Zeigt Check Volume-Paritätsjobs an]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/show-check-vol-parity-job.adoc[Zeigt den Job zur Überprüfung von Volume-Parität an]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/stop-check-vol-parity-job.adoc[Stoppen Sie die Überprüfung des Volume Parity Jobs]
 a| 
Befehl hinzugefügt



 a| 
xref:./get-started/command-line-parameters.adoc[Parameter der Legacy-Kommandozeile]
 a| 
Hinzugefügt `-useLegacyTransferPort` Parameter.



 a| 
xref:./commands-a-z/autoconfigure-storagearray.adoc[Speicher-Array automatisch konfigurieren]
 a| 
Hinzugefügt `blockSize` Parameter.



 a| 
xref:./commands-a-z/check-volume-parity.adoc[Prüfen Sie die Volume-Parität]
 a| 
Verschreibter Befehl.

|===


== SANtricity 11.70.5

Für Version 11.70.5 gibt es keine Änderungen an CLI- und Skriptbefehlen.



== SANtricity 11.70.4

In der folgenden Tabelle werden Änderungen an den CLI- und Skript-Befehlen für Release 11.70.4 aufgeführt.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./get-started/downloadable-smcli-parameters.adoc[Herunterladenbare SMcli-Befehlszeilenparameter]
 a| 
Hinzugefügt `-t` Und `-T` Lesen Sie die Parameterbeschreibungen für die Multi-Faktor-Authentifizierung.

|===


== SANtricity 11.70.3

In der folgenden Tabelle werden Änderungen an den CLI- und Skript-Befehlen für Release 11.70.3 aufgeführt.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[Starten Sie Disk Pool Resource Provisioning]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[Starten Sie Die Ressourcenbereitstellung Der Volume-Gruppe]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[Starten Sie Disk Pool Full Provisioning]
 a| 
Aktualisiert `disableResourceProvisioning` Parameterbeschreibung.



 a| 
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[Starten Sie Vollprovisionierung Von Volume-Gruppen]
 a| 
Aktualisiert `disableResourceProvisioning` Parameterbeschreibung.



 a| 
xref:./commands-a-z/recreate-storagearray-securitykey.html[Externen Sicherheitsschlüssel neu erstellen]
 a| 
Hinzugefügt `deleteOldKey` Parameter.



 a| 
xref:./commands-a-z/create-diskpool.html[Erstellen Sie einen Laufwerkspool]
 a| 
Aktualisiert `driveCount` Parameterbeschreibung.

|===


== SANtricity 11.70.2

In der folgenden Tabelle werden Änderungen an den CLI- und Skript-Befehlen für Release 11.70.2 aufgeführt.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./commands-a-z/create-snmpuser-username.adoc[SNMPv3-USM-Benutzer registrieren]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/set-snmpuser-username.adoc[SNMPv3 USM-Benutzer aktualisieren]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/show-allsnmpusers.adoc[Zeigt den SNMPv3-USM-Benutzer an]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/delete-snmpuser-username.adoc[Aufheben der Registrierung von SNMPv3 USM-Benutzern]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/create-snmptrapdestination.adoc[SNMP-Trap-Ziel registrieren]
 a| 
Hinzugefügt `userName` Und `engineid` Parameter.



 a| 
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[Aktualisieren Sie das SNMP-Trap-Ziel]
 a| 
Hinzugefügt `userName` Und `engineid` Parameter.



 a| 
xref:./commands-a-z/start-snmptrapdestination.adoc[Testen Sie das SNMP-Trap-Ziel]
 a| 
Hinzugefügt `userName` Und `engineid` Parameter.

|===


== SANtricity 11.70.1

In der folgenden Tabelle werden Änderungen an den CLI- und Skript-Befehlen für Release 11.70.1 aufgeführt.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./commands-a-z/start-drive-erase.adoc[Starten Sie das Löschen des Laufwerks]
 a| 
Befehl hinzugefügt



 a| 
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[Importieren des Sicherheitsschlüssels für das Storage-Array]
 a| 
Hinzugefügt `forceOverwrite` Parameter.



 a| 
xref:./commands-a-z/set-controller-hostport.adoc[Legen Sie die Eigenschaften des Controller-Host-Ports fest]
 a| 
Hinzugefügt `fecMode` Parameter.



 a| 
xref:./commands-a-z/show-syslog-summary.adoc[Zeigt die Syslog-Konfiguration an]
 a| 
Hinzugefügt `syslogFormat` Parameter.



 a| 
xref:./commands-a-z/set-syslog.adoc[Konfigurieren Sie die Syslog-Einstellungen]
 a| 
Hinzugefügt `syslogFormat` Parameter.



 a| 
xref:./commands-a-z/set-emailalert.adoc[Konfigurieren Sie Einstellungen für E-Mail-Warnmeldungen]
 a| 
Hinzugefügt `serverEncryption`, `serverPort`, `serverUsername`, und `serverPassword` Parameter.



 a| 
xref:./commands-a-z/show-emailalert-summary.adoc[Konfiguration von E-Mail-Warnmeldungen anzeigen]
 a| 
Hinzugefügt `SMTP` Parameterdaten für Verschlüsselung, Port und Anmeldeinformationen.



 a| 
xref:./commands-a-z/recover-volume.adoc[RAID-Volume wiederherstellen]
 a| 
Hinzugefügt `blockSize` Parameter.

|===


== SANtricity 11.70

In der folgenden Tabelle werden Änderungen an den CLI- und Skript-Befehlen für Release 11.70 aufgeführt.

[cols="2*"]
|===
| Befehl | Beschreibung der Änderung 


 a| 
xref:./commands-a-z/download-storagearray-firmware.adoc[Laden Sie die Speicher-Array-Firmware/NVSRAM herunter]
 a| 
Hinzugefügt `healthCheckNeedsAttnOverride` Parameter.



 a| 
xref:./commands-a-z/create-volume-diskpool.adoc[Erstellen Sie ein Volume im Festplatten-Pool]
 a| 
Hinzugefügt `raidLevel` Parameter.



 a| 
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[Externes Sicherheits-Verschlüsselungsmanagement]
 a| 
Hinzugefügt `saveFile` Parameter.



 a| 
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[Deaktivieren Sie die Verwaltung der externen Sicherheitsschlüssel]
 a| 
Hinzugefügt `saveFile` Parameter.



 a| 
xref:./commands-a-z/recover-volume.adoc[RAID-Volume wiederherstellen]
 a| 
Hinzugefügt `hostUnmapEnabled` Parameter.

|===