---
permalink: get-started/interactive-mode.html 
sidebar: sidebar 
keywords: interactive mode 
summary: 'Im interaktiven Modus können Sie einzelne Befehle ausführen, ohne die Befehle mit voreinstellen `SMcli` zu müssen.' 
---
= Erfahren Sie mehr über den interaktiven SANtricity CLI-Modus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im interaktiven Modus können Sie einzelne Befehle ausführen, ohne die Befehle mit voreinstellen `SMcli` zu müssen.

Wenn Sie eingeben `SMcli` Und ein Speicher-Array-Name, aber keine CLI-Parameter, Skriptbefehle oder eine Skriptdatei angeben, wird die Befehlszeilenschnittstelle im interaktiven Modus ausgeführt.

Im interaktiven Modus können Sie einen einzelnen Befehl eingeben, die Ergebnisse anzeigen und den nächsten Befehl eingeben, ohne den vollständigen Befehl eingeben zu müssen `SMcli` Zeichenfolge. Der interaktive Modus eignet sich zur Bestimmung von Konfigurationsfehlern und zum schnellen Testen von Konfigurationsänderungen.

Um eine Sitzung im interaktiven Modus zu beenden, geben Sie den systemspezifischen Befehl ein. Für Linux ist diese Schlüsselkombination *Control-D*. Für Windows ist diese Tastenkombination *Control-Z + ENTER*.
