---
permalink: get-started/usage-guidelines.html 
sidebar: sidebar 
keywords: script command, guidelines 
summary: Beachten Sie beim Schreiben von Skriptbefehlen die folgenden Richtlinien. 
---
= Erfahren Sie mehr über die Richtlinien für SANtricity CLI-Skriptbefehle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Beachten Sie beim Schreiben von Skriptbefehlen die folgenden Richtlinien.

Diese Liste enthält Richtlinien zum Schreiben von Skriptbefehlen in die Befehlszeile:

* Sie müssen alle Befehle mit einem Semikolon beenden (`;`).
* Sie können mehrere Befehle in einer Zeile eingeben, müssen jedoch jeden Befehl mit einem Semikolon trennen (`;`).
* Sie müssen die einzelnen Basis-Befehle und die damit verbundenen primären Parameter und sekundären Parameter mit einem Speicherplatz trennen.
* Die Skript-Engine reagiert nicht auf Groß- und Kleinschreibung. Sie können Befehle unter Verwendung von Groß- und Kleinbuchstaben oder gemischte Groß-/Kleinschreibung eingeben.
* Fügen Sie Kommentare zu Ihren Skripten hinzu, damit Sie und zukünftige Benutzer den Zweck der Skriptbefehle besser verstehen können. (Informationen zum Hinzufügen von Kommentaren finden Sie unter link:adding-comments-to-a-script-file.html["Hinzufügen von Kommentaren zu einer Skriptdatei"].)


[NOTE]
====
Während die Groß-/Kleinschreibung der CLI-Befehle und der Skript-Befehle nicht beachtet wird, müssen bei Benutzeretiketten (z. B. für Volumes, Hosts oder Host-Ports) die Groß-/Kleinschreibung beachtet werden. Wenn Sie versuchen, ein Objekt zuzuordnen, das durch eine Benutzerbeschriftung identifiziert wird, müssen Sie die Benutzerbezeichnung genau so eingeben, wie sie definiert ist. Andernfalls werden die CLI-Befehle und die Skriptbefehle fehlschlagen.

====