---
permalink: commands-a-z/activate-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, asynchronous, mirroring 
summary: Mit dem Befehl activate storageArray Feature wird die Funktion Asynchronous Mirroring aktiviert. 
---
= Asynchrone Spiegelung aktivieren - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `activate storageArray feature` Befehl aktiviert die Funktion Asynchronous Mirroring.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.

[NOTE]
====
Dieser Befehl ist nur für die asynchrone Spiegelung über Fibre Channel verfügbar.

====


== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Nachdem Sie die Funktion zur asynchronen Spiegelung aktiviert haben, müssen Sie eine asynchrone Spiegelgruppe und ein asynchrones gespiegeltes Paar einrichten.



== Syntax

[source, cli]
----
activate storageArray feature=asyncRemoteMirror
----


== Parameter

Keine.



== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
