---
permalink: commands-a-z/activate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, synchronous mirroring, supported arrays, roles, context, syntax, parameters, data assurance management, minimum firmware level 
summary: Mit dem Befehl activate storageArray Feature wird die Funktion Synchronous Mirroring aktiviert und das Mirror-Repository Volume erstellt. 
---
= Aktivieren Sie die synchrone Spiegelung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `activate storageArray feature` Befehl aktiviert die Funktion Synchronous Mirroring und erstellt das Mirror-Repository-Volume.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E4000, E2700, E5600, E2800 und E5700 Arrays, sofern alle SMcli-Pakete installiert sind.



== Rollen

Sie müssen über die Rolle Storage-Administrator verfügen, um diesen Befehl für ein E4000, E2800 oder E5700 Storage-Array auszuführen.



== Kontext

Mit diesem Befehl können Sie das Mirror-Repository-Volume auf eine der drei Arten definieren:

* Benutzerdefinierte Laufwerke
* Benutzerdefinierte Volume-Gruppe
* Benutzerdefinierte Anzahl von Laufwerken


Wenn Sie sich für eine Reihe von Laufwerken entscheiden, wählt die Controller-Firmware, welche Laufwerke für das Mirror-Repository Volume verwendet werden sollen.

[NOTE]
====
In früheren Versionen dieses Befehls war die Feature-ID `remoteMirror`. Diese Feature-ID ist nicht mehr gültig und wird durch ersetzt `syncMirror`.

====


== Syntax (benutzerdefinierte Laufwerke)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_,pass:quotes[[_drawerIDn_,]pass:quotes[_slotIDn_
[driveType=(fibre | SATA | SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 5 | 6)
repositoryDrives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn)_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Syntax (benutzerdefinierte Volume-Gruppe)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryVolumeGroup=pass:quotes[_volumeGroupName_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== Syntax (benutzerdefinierte Anzahl von Laufwerken)

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`repositoryRAIDLevel`
 a| 
RAID-Level für das Mirror-Repository-Volume Gültige Werte sind `0`, `1`, `3`, `5`, Oder `6`.



 a| 
`repositoryDrives`
 a| 
Die Laufwerke für das Mirror-Repository Volume. Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`.

Alle maximale Steckplatz-ID sind 24. Die Steckplatz-ID-Werte beginnen je nach Fachmodell bei 0 oder 1. Die Laufwerksfächer sind mit E2800 und E5700 Controllern kompatibel und besitzen die Steckplatz-ID-Nummern ab 0. Die Laufwerksfächer sind mit E2700 und E5600 Controllern kompatibel und verfügen ab 1 über die Steckplatz-ID.

Schließen Sie den Wert für Fach-ID, die Fach-ID und den Wert für die Steckplatz-ID in eckigen Klammern ([ ]) an.



 a| 
`repositoryVolumeGroupUserLabel`
 a| 
Den Namen, den Sie der neuen Volume-Gruppe angeben möchten, in der sich das Mirror-Repository Volume befinden soll. Schließen Sie den Namen der Volume-Gruppe in doppelte Anführungszeichen (" ").



 a| 
`repositoryVolumeGroup`
 a| 
Der Name der Spiegelungs-Repository-Volume-Gruppe, in der sich das Spiegelungs-Repository-Volume befindet. (Um die Namen der Volume-Gruppen in Ihrem Speicher-Array zu bestimmen, führen Sie den aus `show storageArray profile` Befehl.)



 a| 
`freeCapacityArea`
 a| 
Die Indexnummer des freien Speicherplatzes in einer vorhandenen Volume-Gruppe, die Sie zum Erstellen des Mirror-Repository-Volumes verwenden möchten. Freie Kapazität wird als freie Kapazität zwischen vorhandenen Volumes in einer Volume-Gruppe definiert. Eine Volume-Gruppe kann zum Beispiel die folgenden Bereiche haben: Volume 1, freie Kapazität, Volume 2, freie Kapazität, Volume 3, Freie Kapazität: Um die freie Kapazität nach Volume 2 zu nutzen, geben Sie an:

[listing]
----
freeCapacityArea=2
----
Führen Sie die aus `show volumeGroup` Befehl, um zu bestimmen, ob ein freier Speicherplatz vorhanden ist.



 a| 
`repositoryDriveCount`
 a| 
Die Anzahl der nicht zugewiesenen Laufwerke, die für das Mirror-Repository-Volume verwendet werden sollen.



 a| 
`driveType`
 a| 
Der Laufwerkstyp, für den Sie Informationen abrufen möchten. Sie können keine unterschiedlichen Laufwerkstypen verwenden.

Gültige Laufwerkstypen:

* `fibre`
* `SATA`
* `SAS`
* NVMe4K


Wenn Sie keinen Laufwerkstyp angeben, wird standardmäßig der Befehl für alle Typen verwendet.



 a| 
`trayLossProtect`
 a| 
Die Einstellung zum erzwingen des Ablagefach-Verlustschutzes, wenn Sie das Spiegelarchiv-Volume erstellen. Um den Schutz gegen den Verlust des Fachs durchzusetzen, setzen Sie diesen Parameter auf `TRUE`. Der Standardwert ist `FALSE`.



 a| 
`drawerLossProtect`
 a| 
Die Einstellung zum Schutz vor Schubladenverlust beim Erstellen des Spiegelarchiv-Volumes. Um den Schutz vor Schubladenverlust durchzusetzen, setzen Sie diesen Parameter auf `TRUE`. Der Standardwert ist `FALSE`.

|===


== Hinweise

Der `repositoryDrives` Der Parameter unterstützt sowohl Laufwerksfächer mit hoher Kapazität als auch Laufwerksfächer mit geringer Kapazität. Ein Laufwerksfach mit hoher Kapazität verfügt über Schubladen, die die Laufwerke halten. Die Schubladen ziehen aus dem Laufwerksfach, um Zugriff auf die Laufwerke zu ermöglichen. Ein Laufwerksfach mit geringer Kapazität verfügt nicht über Schubladen. Bei einem Laufwerksfach mit hoher Kapazität müssen Sie die Kennung (ID) des Laufwerksfachs, die ID des Fachs und die ID des Steckplatzes, in dem sich ein Laufwerk befindet, angeben. Bei einem Laufwerksfach mit niedriger Kapazität müssen Sie nur die ID des Laufwerksfachs und die ID des Steckplatzes angeben, in dem sich ein Laufwerk befindet. Bei einem Laufwerksfach mit geringer Kapazität kann die ID des Laufwerksfachs auf festgelegt werden, um einen Speicherort für ein Laufwerk zu ermitteln `0`, Und geben Sie die ID des Steckplatzes an, in dem sich ein Laufwerk befindet.

Wenn die Laufwerke, die Sie für das auswählen `repositoryDrives` Die Parameter sind nicht mit anderen Parametern kompatibel (wie z. B. dem `repositoryRAIDLevel` Parameter), gibt der Befehl Skript einen Fehler aus, und Synchronous Mirroring ist nicht aktiviert. Der Fehler gibt die Menge an Speicherplatz zurück, die für das Mirror-Repository-Volume benötigt wird. Sie können dann den Befehl erneut eingeben und die entsprechende Menge an Speicherplatz angeben.

Wenn Sie einen Wert für den Repository-Speicherplatz eingeben, der für die Spiegelarchiv-Volumes zu klein ist, gibt die Controller-Firmware eine Fehlermeldung aus, die die Menge an Speicherplatz bereitstellt, die für die Spiegelarchiv-Volumes benötigt wird. Der Befehl versucht nicht, das synchrone Spiegeln zu aktivieren. Sie können den Befehl erneut eingeben, indem Sie den Wert aus der Fehlermeldung für den Wert des Repository-Speicherplatzes verwenden.

Wenn Sie die Laufwerke zuweisen, stellen Sie das ein `trayLossProtect` Parameter an `TRUE` Und mehrere Laufwerke aus einem Fach ausgewählt haben, gibt das Speicherarray einen Fehler zurück. Wenn Sie die einstellen `trayLossProtect` Parameter an `FALSE`, Das Speicherarray führt Vorgänge aus, aber die von Ihnen erstellte Volume-Gruppe verfügt möglicherweise nicht über einen Schutz vor Fachverlust.

Wenn die Controller-Firmware die Laufwerke zuweist, wenn Sie den festlegen `trayLossProtect` Parameter an `TRUE`, Das Speicherarray gibt einen Fehler aus, wenn die Controller-Firmware keine Laufwerke bereitstellen kann, die dazu führen, dass die neue Volume-Gruppe den Tray-Schutz hat. Wenn Sie die einstellen `trayLossProtect` Parameter an `FALSE`, Das Speicher-Array führt den Vorgang aus, selbst wenn es bedeutet, dass die Volume-Gruppe möglicherweise keinen Tray Loss Protection hat.

Der `drawerLossProtect` Mit dem Parameter wird festgelegt, ob bei Ausfall einer Schublade auf Daten auf einem Volume zugegriffen werden kann. Wenn Sie die Laufwerke zuweisen, stellen Sie das ein `drawerLossProtect` Parameter an `TRUE` Und wählen Sie aus einem beliebigen Fach mehrere Laufwerke aus, gibt das Speicher-Array einen Fehler zurück. Wenn Sie die einstellen `drawerLossProtect` Parameter an `FALSE`, Das Speicher-Array führt Vorgänge aus, aber die von Ihnen erstellte Volume-Gruppe hat möglicherweise keinen Schubladenverlust Schutz.



== Data Assurance Management

Die Data Assurance (da)-Funktion erhöht die Datenintegrität im gesamten Storage-System. DA ermöglicht es dem Storage-Array, nach Fehlern zu suchen, die auftreten können, wenn Daten zwischen Hosts und Laufwerken verschoben werden. Wenn diese Funktion aktiviert ist, hängt das Speicherarray die Fehlerprüfungscodes (auch zyklische Redundanzprüfungen oder CRCs genannt) an jeden Datenblock im Volume an. Nach dem Verschieben eines Datenblocks ermittelt das Speicher-Array anhand dieser CRC-Codes, ob während der Übertragung Fehler aufgetreten sind. Potenziell beschädigte Daten werden weder auf Festplatte geschrieben noch an den Host zurückgegeben.

Wenn Sie die da-Funktion verwenden möchten, beginnen Sie mit einem Pool oder einer Volume-Gruppe, der nur Laufwerke enthält, die da unterstützen. Erstellen Sie dann da-fähige Volumes. Ordnen Sie diese da-fähigen Volumes schließlich dem Host mithilfe einer E/A-Schnittstelle zu, die für da geeignet ist. Zu den I/O-Schnittstellen, die da unterstützen, gehören Fibre Channel, SAS und iSER over InfiniBand (iSCSI-Erweiterungen für RDMA/IB). DA wird nicht durch iSCSI über Ethernet oder durch die SRP über InfiniBand unterstützt.

[NOTE]
====
Wenn alle Laufwerke für die da-Fähigkeit geeignet sind, können Sie die einstellen `dataAssurance` Parameter an `enabled` Und dann mit bestimmten Operationen da verwenden. Sie können beispielsweise eine Volume-Gruppe mit da-fähigen Laufwerken erstellen und anschließend ein Volume in dieser Volume-Gruppe erstellen, die für da aktiviert ist. Andere Vorgänge, bei denen ein DA-fähiges Volume verwendet wird, verfügen über Optionen zur Unterstützung der da-Funktion.

====
Wenn der `dataAssurance` Parameter ist auf festgelegt `enabled`, Nur Data Assurance-fähige Laufwerke werden für Volume-Kandidaten in Betracht gezogen werden. Anderenfalls werden sowohl Data Assurance-fähige als auch nicht Data Assurance-fähige Laufwerke berücksichtigt. Sind nur Data Assurance Drives verfügbar, wird die neue Volume-Gruppe mit den aktivierten Data Assurance-Laufwerken erstellt.



== Minimale Firmware-Stufe

7.10 fügt RAID Level 6-Fähigkeit hinzu.

7.60 fügt die hinzu `drawerID` Benutzereingaben, der `driveMediaType` Parameter, und das `drawerLossProtect` Parameter.

7.75 fügt die hinzu `dataAssurance` Parameter.

8.10 entfernt die `driveMediaType` Parameter.

8.60 fügt die hinzu `driveType` Parameter.
