---
permalink: commands-a-z/autoconfigure-storagearray-hotspares.html 
sidebar: sidebar 
keywords: autoconfigure, storage, array, hot spares, supported, roles, syntax, parameters, minimum firmware level 
summary: Der Befehl „AutoConfigure storageArray HotSpares“ definiert und konfiguriert die Hot Spares in einem Storage Array automatisch. Sie können diesen Befehl jederzeit ausführen. Dieser Befehl bietet die beste Hot-Spare-Abdeckung für ein Speicher-Array. 
---
= Automatische Konfiguration von Hotspares für Speicherarrays – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `autoConfigure storageArray hotSpares` Befehl definiert und konfiguriert die Hot Spares in einem Storage Array automatisch. Sie können diesen Befehl jederzeit ausführen. Dieser Befehl bietet die beste Hot-Spare-Abdeckung für ein Speicher-Array.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli]
----
autoConfigure storageArray hotSpares
----


[[parameters]]
== Parameter

Keine.



[[notes]]
== Hinweise

Wenn Sie den ausführen `autoconfigure storageArray hotSpares` Der Befehl, die Controller-Firmware bestimmt die Anzahl der Hot Spares, die erstellt werden sollen, basierend auf der Gesamtzahl und dem Typ der Laufwerke im Storage Array. Bei SAS-Laufwerken erstellt die Controller-Firmware ein Hot Spare für das Storage Array und einen zusätzlichen Hot Spare für alle 60 Laufwerke im Speicher-Array.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
