---
permalink: commands-a-z/change-ssd-cache-application-type.html 
sidebar: sidebar 
keywords: ssd cache application type 
summary: Mit dem Befehl Set ssdCache wird der Anwendungstyp geändert, der dem SSD-Cache zugeordnet ist. Der Applikationstyp kann Web-Server, Datenbank oder Multimedia sein. Durch die Änderung des Applikationstyps werden die Blockgröße, die Größe des Unterblocks geändert, der Schwellenwert für das Lesen befüllt und der Schreibschwellenwert für die Volumes, die dem SSD-Cache zugrunde liegen, befüllt. 
---
= SSD-Cache-Anwendungstyp ändern – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set ssdCache` Befehl ändert den Applikationstyp, der dem SSD-Cache zugeordnet ist. Der Applikationstyp kann Web-Server, Datenbank oder Multimedia sein. Durch die Änderung des Applikationstyps werden die Blockgröße, die Größe des Unterblocks geändert, der Schwellenwert für das Lesen befüllt und der Schreibschwellenwert für die Volumes, die dem SSD-Cache zugrunde liegen, befüllt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000-, E2800-, E5700-, EF600-, EF300-, EF50- oder EF80-Speicherarray auszuführen, müssen Sie die Support Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]usageHint=(webServer|dataBase|fileSystem)
----


[[parameter]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, für den Sie den Applikationstyp ändern möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`usageHint`
 a| 
Die Werte basieren auf dem typischen I/O-Nutzungsmuster der Applikation, die den SSD-Cache verwendet. Gültige Werte sind `webServer`, `dataBase`, Oder `fileSystem`.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
