---
permalink: commands-a-z/check-repositoryconsistency.html 
sidebar: sidebar 
keywords: check, repository, consistency 
summary: Der Befehl Check repositoryConsistency erzeugt einen Bericht, der auf der Analyse der Daten im zugrunde liegenden Repository-Volume eines bestimmten Objekts basiert. 
---
= Prüfen Sie die Repository-Konsistenz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `check repositoryConsistency` Befehl erstellt einen Bericht, der auf der Analyse der Daten im zugrunde liegenden Repository-Volume eines bestimmten Objekts basiert.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
check (snapGroup pass:quotes[[_snapGroupName_]] repositoryConsistency |
snapVolume pass:quotes[[_snapVolumeName_]] repositoryConsistency |
volume pass:quotes[[_volumeName_]] repositoryConsistency |
volumeCopy target pass:quotes[[_targetName_]] repositoryConsistency |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
repositoryConsistency localVolume=pass:quotes[_"localVolumeName"_]]
file=pass:quotes[_"filePath"_]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`repositoryConsistency`
 a| 
Gibt an, dass die Snapshot-Gruppe, das Snapshot-Volume, das Volume oder die asynchrone Spiegelgruppe (je nachdem, welcher durch den entsprechenden Parameter angegeben wird) auf Konsistenz überprüft wird.



 a| 
`snapGroup`
 a| 
Der Name der Snapshot-Gruppe, auf der eine Konsistenzprüfung ausgeführt werden soll. Schließen Sie den Namen der Snapshot-Gruppe in eckige Klammern ([ ]). Wenn der Name der Snapshot-Gruppe Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`snapVolume`
 a| 
Der Name des Snapshot-Volumes, auf dem eine Konsistenzprüfung ausgeführt werden soll. Schließen Sie den Namen des Snapshot-Volumes in eckige Klammern ([ ]). Wenn der Name des Snapshot-Volumes Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`volume`
 a| 
Der Name des Thin-Volumes, auf dem eine Konsistenzprüfung ausgeführt werden soll. Schließen Sie den Namen des dünnen Volumens in eckige Klammern ([ ]). Wenn der Name des Thin-Volumes Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`volumeCopy`
 a| 
Gibt an, dass das Ziel einer Volume-Kopie-Beziehung auf Konsistenz überprüft wird.



 a| 
`target`
 a| 
Verwenden Sie nur in Verbindung mit dem `volumeCopy` Parameter, um den Namen des Volumes anzugeben, der Ziel der Volume-Kopierbeziehung ist. Wenn der Volume-Name Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckige Klammern setzen.



 a| 
`asyncMirrorGroup`
 a| 
Der Name der asynchronen Spiegelgruppe, auf der eine Konsistenzprüfung ausgeführt werden soll. Schließen Sie den Namen der asynchronen Spiegelgruppe in eckige Klammern ([ ]). Wenn der Name der asynchronen Spiegelgruppe Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`localVolume`
 a| 
Verwenden Sie nur mit dem `asyncMirrorGroup` Parameter, um den Namen eines lokalen Volumes anzugeben, das an der Spiegelbeziehung beteiligt ist. Sie können ein lokales Volume angeben, das entweder die Quelle oder das Ziel einer Spiegelbeziehung ist. Schließen Sie den lokalen Volumennamen in doppelte Anführungszeichen (" ").



 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in den Sie den Bericht speichern möchten, der aus der Konsistenzprüfung stammt. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\repoConsistency.txt"` Dieser Parameter muss nach einem der optionalen Parameter der letzte sein.

|===


== Hinweise

Der mit diesem Befehl erzeugte Bericht dient der technischen Unterstützung zur Analyse von Problemen.



== Minimale Firmware-Stufe

7.83
