---
permalink: commands-a-z/clear-storagearray-firmwarependingarea.html 
sidebar: sidebar 
keywords: clear, storage array, firmware, pending, area 
summary: Der Befehl clear storageArray firmwarePendingArea löscht ein Firmware-Image oder NVSRAM-Werte, die Sie zuvor aus dem ausstehenden Area Buffer heruntergeladen haben. 
---
= Ausstehender Bereich der Speicherarray-Firmware löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `clear storageArray firmwarePendingArea` Mit dem Befehl werden ein Firmware-Image oder NVSRAM-Werte gelöscht, die Sie zuvor aus dem ausstehenden Area Buffer heruntergeladen haben.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Kontext

[NOTE]
====
*Mögliche Schäden an der Speicherarray-Konfiguration* -- Sobald Sie diesen Befehl ausführen, werden die Inhalte des vorhandenen ausstehenden Bereichs im Speicher-Array gelöscht.

====


== Syntax

[source, cli]
----
clear storageArray firmwarePendingArea
----


== Parameter

Keine.
