---
permalink: commands-a-z/create-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency, group 
summary: Der Befehl create consistencyGroup erstellt eine neue, leere Konsistenzgruppe, die Snapshot-Gruppen enthalten kann. Sie müssen die Snapshot-Gruppen mit dem Befehl Set konsistent Group addCGMember hinzufügen. 
---
= Konsistenzgruppe erstellen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create consistencyGroup` Befehl erstellt eine neue, leere Konsistenzgruppe, die Snapshot Gruppen enthalten kann. Sie müssen die Snapshot-Gruppen mithilfe der hinzufügen `set consistencyGroup addCGMember` Befehl.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
create consistencyGroup userLabel=pass:quotes[_"consistencyGroupName"_]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapSchedule_])]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`userLabel`
 a| 
Der Name der neuen Konsistenzgruppe, die Sie erstellen möchten. Schließen Sie den neuen Namen der Konsistenzgruppe in doppelte Anführungszeichen (“ „).



 a| 
`repositoryFullPolicy`
 a| 
Wie soll die Snapshot-Verarbeitung fortgesetzt werden, wenn die Snapshot-Repository-Volumen voll sind? Sie können festlegen, dass Schreibzugriffe auf das Basis-Volume fehlschlagen (`failBaseWrites`) Oder löschen Sie die Snapshot-Bilder  `purgeSnapImages`). Die Standardaktion ist `purgeSnapImages`.



 a| 
`repositoryFullLimit`
 a| 
Der Prozentsatz der Repository-Kapazität, mit der Sie eine Warnung erhalten, dass das Snapshot-Repository-Volume sich dem vollen Volumen nähert. Ganzzahlwerte verwenden. Beispielsweise bedeutet ein Wert von 70 70 Prozent. Der Standardwert ist 75.



 a| 
`autoDeleteLimit`
 a| 
Jede Snapshot-Gruppe kann so konfiguriert werden, dass sie ihre Snapshot-Images automatisch löscht, um die Gesamtanzahl der Snapshot-Images in der Snapshot-Gruppe auf einer festgelegten Ebene oder unter ihnen zu halten. Wenn diese Option aktiviert ist, wird jedes Mal, wenn ein neues Snapshot-Image in der Snapshot-Gruppe erstellt wird, automatisch das älteste Snapshot-Image in der Gruppe gelöscht, um dem Grenzwert zu entsprechen. Durch diese Aktion wird die Repository-Kapazität frei, sodass sie zur Erfüllung der fortlaufenden Anforderungen an das Copy-on-Write für die verbleibenden Snapshot-Images verwendet werden kann.



 a| 
`enableSchedule`
 a| 
Gibt an, ob die Möglichkeit, einen Snapshot-Vorgang zu planen, aktiviert oder deaktiviert ist. Um die Snapshot-Planung zu aktivieren, setzen Sie diesen Parameter auf `TRUE`. Um die Snapshot-Planung zu deaktivieren, setzen Sie diesen Parameter auf `FALSE`.



 a| 
`rollBackPriority`
 a| 
Legt fest, ob Systemressourcen auf Kosten der Systemleistung dem Rollback-Vorgang zugewiesen werden sollen. Der Wert von `high` Zeigt an, dass der Rollback-Vorgang über alle anderen Host-I/O-Operationen priorisiert wird Der Wert von `low` Zeigt an, dass der Rollback-Vorgang mit minimalen Auswirkungen auf den Host-I/O durchgeführt werden sollte

|===


== Hinweise

Eine Konsistenzgruppe ist eine logische Einheit, mit der Sie alle Snapshot-Images, die Sie der Sammlung hinzufügen, in Batch-Form verwalten können. Die Konsistenzgruppe ist eine Sammlung von Snapshot Gruppen, die für ihre Snapshot Images gemeinsame Konsistenzanforderungen oder Abhängigkeiten haben. Alle Snapshot-Images, die Sie für diese Sammlung erstellen und verwenden, müssen entsprechend den Konsistenzabhängigkeiten verwaltet werden.

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Die Snapshot Images in einer Konsistenzgruppe können basierend auf der Existenz eines Snapshot Images in einer Konsistenzgruppe abgeleitet werden. Alle Snapshot Images in einer Konsistenzgruppe verwenden einen gemeinsamen Zeitstempel und eine Sequenznummer.

Ein Vorgang auf einer Snapshot-Image-Konsistenzgruppe wird als eine einzige Anforderung behandelt und bewirkt, dass alle ausstehenden I/O-Vorgänge für das zugehörige Basisvolume jedes Mitglieds vor der Erstellung der Snapshot-Images entfernt und ausgesetzt werden. Wenn die Erstellung der Snapshot-Images für alle Mitglieder der Konsistenzgruppe nicht erfolgreich abgeschlossen werden kann, schlägt der Vorgang fehl und hat keine Auswirkungen (d. h. neue Snapshot-Images werden nicht erstellt).

Basierend auf diesem Verhalten haben alle Mitglieder für eine Konsistenzgruppe in der Regel die gleiche Anzahl von Snapshot Images. Wenn jedoch ein neues Mitglied einer Konsistenzgruppe hinzugefügt wird, fehlen dem neuen Mitglied die Snapshot-Images, die zuvor auf den festgelegten Mitgliedern der Konsistenzgruppe erstellt wurden. Das Fehlen von Snapshot-Images wird nicht als Fehlerbedingung betrachtet. Die folgenden Anfragen zum Löschen oder Rollback von Snapshot-Images, die nur auf einer Teilmenge der Mitglieder der Consistency Group vorhanden sind, wirken sich nur auf die Mitglieder aus, für die die angegebenen Snapshot-Images tatsächlich vorhanden sind.



== Automatisches Löschen

Sie können jede Snapshot-Gruppe so konfigurieren, dass die Snapshot-Images automatisch gelöscht werden, damit die Gesamtanzahl der Snapshot-Images in der Snapshot-Gruppe bei oder unter einer maximalen Anzahl von Bildern bleibt. Wenn die Anzahl der Snapshot-Images in der Snapshot-Gruppe die Höchstgrenze erreicht, wird das angezeigt `autoDeleteLimit` Der Parameter löscht Snapshot-Images automatisch, wenn ein neues Snapshot-Image in der Snapshot-Gruppe erstellt wird. Der `autoDeleteLimit` Der Parameter löscht die ältesten Snapshot-Images der Snapshot-Gruppe, bis die maximale Anzahl von Bildern, die mit dem Parameter definiert wurden, erreicht ist. Dies wirkt sich auf die Freigabe der Repository-Kapazität aus, sodass diese zur Erfüllung der fortlaufenden Anforderungen an das Copy-on-Write für die verbleibenden Snapshot-Images genutzt werden kann.



== Planen von Snapshot Images in einer Konsistenzgruppe

Der `enableSchedule` Und das `schedule` Parameter bieten eine Möglichkeit, Snapshots zu planen. Mithilfe dieser Parameter können Sie Snapshots täglich, wöchentlich oder monatlich (nach Tag oder nach Datum) planen. Der `enableSchedule` Der Parameter aktiviert oder deaktiviert die Möglichkeit, Snapshots zu planen. Wenn Sie die Planung aktivieren, verwenden Sie das `schedule` Parameter, der definiert werden soll, wann die Snapshots ausgeführt werden sollen.

In dieser Tabelle wird erläutert, wie die Optionen für das verwendet werden `schedule` Parameter:

|===
| Parameter | Beschreibung 


 a| 
`schedule`
 a| 
Erforderlich für die Angabe von Zeitplanparametern.



 a| 
`immediate`
 a| 
Starten Sie den Vorgang sofort. Dieses Element schließen sich gegenseitig mit anderen Planungsparametern aus.



 a| 
`enableSchedule`
 a| 
Wenn eingestellt auf `true`, Die Planung ist eingeschaltet. Wenn eingestellt auf `false`, Die Planung ist ausgeschaltet.

[NOTE]
====
Die Standardeinstellung lautet `false`.

====


 a| 
`startDate`
 a| 
Ein bestimmtes Datum, an dem der Vorgang gestartet werden soll. Das Format zur Eingabe des Datums ist MM:TT:JJ. Der Standardwert ist das aktuelle Datum. Ein Beispiel für diese Option ist `startDate=06:27:11`.



 a| 
`scheduleDay`
 a| 
Ein Tag der Woche, an dem der Betrieb gestartet werden soll. Kann entweder alle oder mehrere der folgenden Werte sein:

* `monday`
* `tuesday`
* `wednesday`
* `thursday`
* `friday`
* `saturday`
* `sunday`


[NOTE]
====
Setzen Sie den Wert in Klammern ein. Beispiel: `scheduleDay=(wednesday)`.

====
Mehr als ein Tag kann durch die Festlegung der Tage in einer einzelnen Reihe von Klammern angegeben werden und jeden Tag mit einem Leerzeichen voneinander trennen. Beispiel: `scheduleDay=(monday wednesday friday)`.

[NOTE]
====
Dieser Parameter ist nicht mit einem monatlichen Zeitplan kompatibel.

====


 a| 
`startTime`
 a| 
Die Zeit eines Tages, an dem der Betrieb gestartet werden soll. Das Format für die Eingabe der Zeit ist HH:MM, wobei HH die Stunde und MM ist die Minute nach der Stunde. Verwendet einen 24-Stunden-Takt. Beispiel: 2:00 am Nachmittag ist 14:00. Ein Beispiel für diese Option ist `startTime=14:27`.



 a| 
`scheduleInterval`
 a| 
Eine Zeit, die in Minuten als Minimum zwischen den Operationen.Zeitplan-Intervall sollte nicht mehr als 1440 (24 Stunden) und es sollte ein Vielfaches von 30 sein.

Ein Beispiel für diese Option ist``scheduleInterval=180``.



 a| 
`endDate`
 a| 
Ein bestimmtes Datum, an dem der Vorgang beendet werden soll. Das Format zur Eingabe des Datums ist MM:TT:JJ. Wenn kein Enddatum gewünscht ist, können Sie angeben `noEndDate`. Ein Beispiel für diese Option ist `endDate=11:26:11`.



 a| 
`timesPerDay`
 a| 
Die Anzahl der Zeiten, die für die Durchführung der Operation an einem Tag erforderlich sind. Ein Beispiel für diese Option ist `timesPerDay=4`.



 a| 
`timezone`
 a| 
Gibt die Zeitzone an, die für den Zeitplan verwendet werden soll. Es gibt zwei Möglichkeiten:

* *GMT±HH:MM*
+
Die Zeitzone wird von GMT versetzt. Beispiel: `timezone=GMT-06:00`.

* *Textzeichenfolge*
+
Standardtext für Zeitzonen, muss in Anführungszeichen eingeschlossen sein. Beispiel:``timezone="America/Chicago"``





 a| 
`scheduleDate`
 a| 
Ein Tag des Monats, an dem die Operation ausgeführt werden soll. Die Werte für die Tage sind numerisch und im Bereich von 1-31.

[NOTE]
====
Dieser Parameter ist nicht mit einem Wochenplan kompatibel.

====
Ein Beispiel für `scheduleDate` Option ist `scheduleDate=("15")`.



 a| 
`month`
 a| 
Ein bestimmter Monat, in dem der Vorgang ausgeführt werden soll. Die Werte für die Monate sind:

* `jan` - Januar
* `feb` - Februar
* `mar` - März
* `apr` - April
* `may` - Mai
* `jun` - Juni
* `jul` - Juli
* `aug` - August
* `sep` - September
* `oct` - Oktober
* `nov` - November
* `dec` - Dezember


[NOTE]
====
Setzen Sie den Wert in Klammern ein. Beispiel: `month=(jan)`.

====
Mehr als ein Monat kann durch die Schließung der Monate in einer einzelnen Reihe von Klammern angegeben werden und durch die Trennung jedes Monats mit einem Leerzeichen. Beispiel: `month=(jan jul dec)`.

Verwenden Sie diesen Parameter mit dem `scheduleDate` Parameter, um den Vorgang an einem bestimmten Tag des Monats auszuführen.

[NOTE]
====
Dieser Parameter ist nicht mit einem Wochenplan kompatibel.

====
|===
In dieser Tabelle wird die Verwendung des erläutert `timeZone` Parameter:

|===
| Name Der Zeitzone | GMT-Offset 


 a| 
`Etc/GMT+12`
 a| 
`GMT-12:00`



 a| 
`Etc/GMT+11`
 a| 
`GMT-11:00`



 a| 
`Pacific/Honolulu`
 a| 
`GMT-10:00`



 a| 
`America/Anchorage`
 a| 
`GMT-09:00`



 a| 
`America/Santa_Isabel`
 a| 
`GMT-08:00`



 a| 
`America/Los_Angeles`
 a| 
`GMT-08:00`



 a| 
`America/Phoenix`
 a| 
`GMT-07:00`



 a| 
`America/Chihuahua`
 a| 
`GMT-07:00`



 a| 
`America/Denver`
 a| 
`GMT-07:00`



 a| 
`America/Guatemala`
 a| 
`GMT-06:00`



 a| 
`America/Chicago`
 a| 
`GMT-06:00`



 a| 
`America/Mexico_City`
 a| 
`GMT-06:00`



 a| 
`America/Regina`
 a| 
`GMT-06:00`



 a| 
`America/Bogota`
 a| 
`GMT-05:00`



 a| 
`America/New_York`
 a| 
`GMT-05:00`



 a| 
`Etc/GMT+5`
 a| 
`GMT-05:00`



 a| 
`America/Caracas`
 a| 
`GMT-04:30`



 a| 
`America/Asuncion`
 a| 
`GMT-04:00`



 a| 
`America/Halifax`
 a| 
`GMT-04:00`



 a| 
`America/Cuiaba`
 a| 
`GMT-04:00`



 a| 
`America/La_Paz`
 a| 
`GMT-04:00`



 a| 
`America/Santiago`
 a| 
`GMT-04:00`



 a| 
`America/St_Johns`
 a| 
`GMT-03:30`



 a| 
`America/Sao_Paulo`
 a| 
`GMT-03:00`



 a| 
`America/Buenos_Aires`
 a| 
`GMT-03:00`



 a| 
`America/Cayenne`
 a| 
`GMT-03:00`



 a| 
`America/Godthab`
 a| 
`GMT-03:00`



 a| 
`America/Montevideo`
 a| 
`GMT-03:00`



 a| 
`Etc/GMT+2`
 a| 
`GMT-02:00`



 a| 
`Atlantic/Azores`
 a| 
`GMT-01:00`



 a| 
`Atlantic/Cape_Verde`
 a| 
`GMT-01:00`



 a| 
`Africa/Casablanca`
 a| 
`GMT`



 a| 
`Etc/GMT`
 a| 
`GMT`



 a| 
`Europe/London`
 a| 
`GMT`



 a| 
`Atlantic/Reykjavik`
 a| 
`GMT`



 a| 
`Europe/Berlin`
 a| 
`GMT+01:00`



 a| 
`Europe/Budapest`
 a| 
`GMT+01:00`



 a| 
`Europe/Paris`
 a| 
`GMT+01:00`



 a| 
`Europe/Warsaw`
 a| 
`GMT+01:00`



 a| 
`Africa/Lagos`
 a| 
`GMT+01:00`



 a| 
`Africa/Windhoek`
 a| 
`GMT+01:00`



 a| 
`Asia/Anman`
 a| 
`GMT+02:00`



 a| 
`Asia/Beirut`
 a| 
`GMT+02:00`



 a| 
`Africa/Cairo`
 a| 
`GMT+02:00`



 a| 
`Asia/Damascus`
 a| 
`GMT+02:00`



 a| 
`Africa/Johannesburg`
 a| 
`GMT+02:00`



 a| 
`Europe/Kiev`
 a| 
`GMT+02:00`



 a| 
`Asia/Jerusalem`
 a| 
`GMT+02:00`



 a| 
`Europe/Istanbul`
 a| 
`GMT+03:00`



 a| 
`Europe/Minsk`
 a| 
`GMT+02:00`



 a| 
`Asia/Baghdad`
 a| 
`GMT+03:00`



 a| 
`Asia/Riyadh`
 a| 
`GMT+03:00`



 a| 
`Africa/Nairobi`
 a| 
`GMT+03:00`



 a| 
`Asia/Tehran`
 a| 
`GMT+03:30`



 a| 
`Europe/Moscow`
 a| 
`GMT+04:00`



 a| 
`Asia/Dubai`
 a| 
`GMT+04:00`



 a| 
`Asia/Baku`
 a| 
`GMT+04:00`



 a| 
`Indian/Mauritius`
 a| 
`GMT+04:00`



 a| 
`Asia/Tbilisi`
 a| 
`GMT+04:00`



 a| 
`Asia/Yerevan`
 a| 
`GMT+04:00`



 a| 
`Asia/Kabul`
 a| 
`GMT+04:30`



 a| 
`Asia/Karachi`
 a| 
`GMT+05:00`



 a| 
`Asia//Tashkent`
 a| 
`GMT+05:00`



 a| 
`Asia/Calcutta`
 a| 
`GMT+05:30`



 a| 
`Asia/Colombo`
 a| 
`GMT+05:30`



 a| 
`Asia/Katmandu`
 a| 
`GMT+05:45`



 a| 
`Asia/Yekaterinburg`
 a| 
`GMT+06:00`



 a| 
`Asia/Almaty`
 a| 
`GMT+06:00`



 a| 
`Asia/Dhaka`
 a| 
`GMT+06:00`



 a| 
`Asia/Rangoon`
 a| 
`GMT+06:30`



 a| 
`Asia/Novosibirsk`
 a| 
`GMT+07:00`



 a| 
`Asia/Bangkok`
 a| 
`GMT+07:00`



 a| 
`Asia/Krasnoyarsk`
 a| 
`GMT+08:00`



 a| 
`Asia/Shanghai`
 a| 
`GMT+08:00`



 a| 
`Asia/Singapore`
 a| 
`GMT+08:00`



 a| 
`Australia/Perth`
 a| 
`GMT+08:00`



 a| 
`Asia/Taipei`
 a| 
`GMT+08:00`



 a| 
`Asia/Ulaanbaatar`
 a| 
`GMT+08:00`



 a| 
`Asia/Irkutsk`
 a| 
`GMT+09:00`



 a| 
`Asia/Tokyo`
 a| 
`GMT+09:00`



 a| 
`Asia/Seoul`
 a| 
`GMT+09:00`



 a| 
`Australia/Adelaide`
 a| 
`GMT+09:30`



 a| 
`Australia/Darwin`
 a| 
`GMT+09:30`



 a| 
`Asia/Yakutsk`
 a| 
`GMT+10:00`



 a| 
`Australia/Brisbane`
 a| 
`GMT+10:00`



 a| 
`Australia/Sydney`
 a| 
`GMT+10:00`



 a| 
`Pacific/Port Moresby`
 a| 
`GMT+10:00`



 a| 
`Australia/Hobart`
 a| 
`GMT+10:00`



 a| 
`Asia/Vladivostok`
 a| 
`GMT+11:00`



 a| 
`Pacific/Guadalcanal`
 a| 
`GMT+11:00`



 a| 
`Pacific/Auckland`
 a| 
`GMT+12:00`



 a| 
`Etc/GMT-12`
 a| 
`GMT+12:00`



 a| 
`Pacific/Fiji`
 a| 
`GMT+12:00`



 a| 
`Asia/Kamchatka`
 a| 
`GMT+12:00`



 a| 
`Pacific/Tongatapu`
 a| 
`GMT+13:00`

|===
Der Code-String zum Definieren eines Zeitplans ähnelt den folgenden Beispielen:

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
Wenn Sie auch den verwenden `scheduleInterval` Die Option, die Firmware wird zwischen dem ausgewählt `timesPerDay` Option und das `scheduleInterval` Option durch Auswahl des niedrigsten Werts der beiden Optionen. Die Firmware berechnet einen ganzzahligen Wert für das `scheduleInterval` Möglichkeit, 1440 durch ein zu teilen `scheduleInterval` Von Ihnen festgelegte Optionswert. Beispiel: 1440/180 = 8. Die Firmware vergleicht dann das `timesPerDay` Integer-Wert mit dem berechneten Wert `scheduleInterval` Ganzzahlwert und verwendet den kleineren Wert.

Um einen Zeitplan zu entfernen, verwenden Sie den `delete volume` Befehl mit dem `schedule` Parameter. Der `delete volume` Befehl mit dem `schedule` Mit dem Parameter wird nur der Zeitplan gelöscht, nicht das Snapshot-Volume.

Wenn Sie ein Rollback in einer Konsistenzgruppe durchführen, besteht der Standardvorgang darin, alle Mitglieder der Konsistenzgruppe zurückzusetzen. Wenn ein Rollback für alle Mitglieder der Konsistenzgruppe nicht erfolgreich gestartet werden kann, schlägt das Rollback fehl und hat keine Auswirkungen. Das Snapshot-Image wird nicht zurückgesetzt.



== Minimale Firmware-Stufe

7.83

7.86 fügt die hinzu `scheduleDate` Option und das `month` Option.
