---
permalink: commands-a-z/create-storagearray-syslog.html 
sidebar: sidebar 
keywords: create, storage, array, syslog, configuration 
summary: Mit dem Befehl create storageArray syslog können Sie Audit-Protokolle auf einem externen Syslog-Server archivieren. Nachdem eine Verbindung zwischen dem Speicher-Array und dem Syslog-Server hergestellt wurde, werden Audit-Protokolle automatisch auf dem Syslog-Server gespeichert. 
---
= Erstellen der Syslog-Konfiguration des Storage-Arrays
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `create storageArray syslog` Mit dem Befehl können Sie Audit-Protokolle auf einem externen Syslog-Server archivieren. Nachdem eine Verbindung zwischen dem Speicher-Array und dem Syslog-Server hergestellt wurde, werden Audit-Protokolle automatisch auf dem Syslog-Server gespeichert.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Security Admin“ vorhanden sein.



== Syntax

[listing]
----

create storageArray syslog serverAddress="<address>" port=<port> protocol=("udp" | "tcp" | "tls") components=(componentName=("auditLog") ...)
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`serverAddress`
 a| 
Syslog-Empfänger-Hostname oder IP-Adresse.



 a| 
`port`
 a| 
Anschlussnummer des Syslog-Empfängers.



 a| 
`protocol`
 a| 
Syslog-Übertragungsprotokoll: Zulässige Werte sind udp, tcp oder tls.



 a| 
`components`
 a| 
Liste der Komponenteneinträge, die auf dem Syslog-Server protokolliert werden. Aktuell werden nur Audit-Protokolle unterstützt.



 a| 
`componentName`
 a| 
Komponentenname; derzeit wird nur „AuditLog“ unterstützt.

|===


=== Beispiel

[listing]
----
SMcli -n Array1 -c "create storageArray syslog
serverAddress=\"192.168.2.1\" port=514 protocol=\"udp\"
components=(componentName=\"auditLog\");"
ID: 331998fe-3154-4489-b773-b0bb60c6b48e
Server Address: 192.168.2.1.com
Port: 514
Protocol: udp
Components
1. Component Name: auditLog
SMcli completed successfully.
----


== Minimale Firmware-Stufe

8.42
