---
permalink: commands-a-z/create-initiator.html 
sidebar: sidebar 
keywords: create, initiator 
summary: Der Befehl „Create Initiator“ erstellt das Initiatorobjekt. 
---
= Initiator erstellen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create initiator` Befehl erstellt das Initiator-Objekt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

[NOTE]
====
Mit diesem Befehl wird die veraltete Version ersetzt xref:create-iscsiinitiator.adoc[ISCSI-Initiator erstellen] Befehl.

====
[NOTE]
====
Dieser Befehl gilt nur für iSCSI, iSER, NVMe over RoCE, NVMe over InfiniBand und NVMe over Fibre Channel.

====


== Syntax

[source, cli]
----
create initiator identifier="initiatorQualifiedName" userLabel="initiatorName" host="hostName"
interfaceType=(iscsi | iser | nvmeof) [chapSecret="securityKey"]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`identifier`
 a| 
Ermöglicht Ihnen, den qualifizierten Identifier-Namen (z. B. iqn oder nqn) zum Erstellen eines Initiators anzugeben. Schließen Sie die Kennung in doppelte Anführungszeichen (" ").



 a| 
`userLabel`
 a| 
Ermöglicht Ihnen die Angabe eines Benutzeretiketts für den Initiator. Schließen Sie den Namen in doppelte Anführungszeichen (" ").



 a| 
`host`
 a| 
Ermöglicht Ihnen die Angabe des Host-Namens, an dem der Initiator installiert ist. Schließen Sie den Namen in doppelte Anführungszeichen (" ").



 a| 
`interfaceType`
 a| 
Ermöglicht Ihnen, festzulegen, für welchen Schnittstellentyp der Initiator verwendet wird. Gültige Auswahlmöglichkeiten: iscsi, iser oder nvmeof.



 a| 
`chapSecret`
 a| 
Ermöglicht die Eingabe des Sicherheitsschlüssels, den Sie zur Authentifizierung einer Peer-Verbindung verwenden möchten. Schließen Sie den Sicherheitsschlüssel in doppelte Anführungszeichen („ “). Dieser Parameter gilt nur für iSCSI- und iSER-Host-Schnittstellentypen.

|===


== Minimale Firmware-Stufe

8.41
