---
permalink: commands-a-z/create-hostgroup.html 
sidebar: sidebar 
keywords: create, host group 
summary: Mit dem Befehl „HostGroup erstellen“ wird eine neue Host-Gruppe erstellt. 
---
= Hostgruppe erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create hostGroup` Befehl erstellt eine neue Host-Gruppe.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
create hostGroup userLabel=pass:quotes[_"hostGroupName"_]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`userLabel`
 a| 
Der Name, den Sie der von Ihnen erstellten Host-Gruppe geben möchten. Schließen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen (" ").

|===


== Hinweise

Eine Host-Gruppe ist ein optionales topologisches Element, das Sie definieren können, ob Sie eine Sammlung von Hosts bestimmen möchten, die Zugriff auf dieselben Volumes haben. Die Host-Gruppe ist eine logische Einheit. Definieren Sie eine Host-Gruppe nur, wenn Sie über zwei oder mehr Hosts verfügen, die den Zugriff auf dieselben Volumes teilen können.

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Bindestriche und Unterstrichen für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.



== Minimale Firmware-Stufe

5.20
