---
permalink: commands-a-z/create-snmpcommunity.html 
sidebar: sidebar 
keywords: register, snmp, community 
summary: 'Der Befehl create snmpCommunity erstellt eine neue SNMP-Community (Simple Network Management Protocol), einen Community-Namensstring und registriert die neue Community als eine bekannte Einheit beim SNMP-Agenten. Jeder Versuch, eine neue Community mit demselben Namen wie eine vorhandene Community zu registrieren, wird abgelehnt und die Firmware gibt eine Fehlermeldung zurück.' 
---
= SNMP-Community registrieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create snmpCommunity` Befehl erstellt eine neue SNMP-Community (Simple Network Management Protocol), einen Community-Name-String und registriert die neue Community als eine bekannte Einheit beim SNMP-Agent. Jeder Versuch, eine neue Community mit demselben Namen wie eine vorhandene Community zu registrieren, wird abgelehnt und die Firmware gibt eine Fehlermeldung zurück.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Speichersystem auszuführen, müssen Sie die Rolle Storage Admin oder Support Admin haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
create snmpCommunity communityName=pass:quotes[_"snmpCommunityName"_]
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`communityName`
 a| 
Der Name der SNMP-Community, die Sie erstellen möchten. Schließen Sie den SNMP-Community-Namen in doppelte Anführungszeichen (" ").

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.30
