---
permalink: commands-a-z/create-cgsnapvolume.html 
sidebar: sidebar 
keywords: create, consistency group, snapshot, volume 
summary: Der Befehl create cgSnapVolume erstellt ein Snapshot-Volumen von spezifischen Images in den Basis-Volumes in einer Konsistenzgruppe. 
---
= Konsistenzgruppen-Snapshot-Volume erstellen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create cgSnapVolume` Befehl erstellt ein Snapshot-Volume von spezifischen Images in den Basis-Volumes einer Konsistenzgruppe.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Sie können ein Basis-Volume oder mehrere Basisvolumes aus der Konsistenzgruppe auswählen, die in das Snapshot-Volume aufgenommen werden soll. Wenn Sie ein Snapshot-Volume einer Konsistenzgruppe erstellen, erstellen Sie ein Volume mit Inhalten, die Sie anzeigen können.



== Syntax mit benutzerspezifizierten Basis-Volumes

[source, cli, subs="+macros"]
----
create cgSnapVolume userLabel=pass:quotes[_"cgVolumeName"_]
cgSnapImageID=pass:quotes[_"snapCGID:imageID"_]
members=pass:quotes[_(baseVolume1:repos_XXXX ... baseVolumen:repos_YYYY)_]
----


== Syntax bei Einstellung des Snapshot- Volumens der Konsistenzgruppe auf „schreibgeschützt“

[source, cli, subs="+macros"]
----
create cgSnapVolume userLabel=pass:quotes[_"cgVolumeName"_]
cgSnapImageID=pass:quotes[_"snapCGID:imageID"_]
readOnly
----


== Syntax beim Festlegen der vollen Repository-Grenze

[source, cli, subs="+macros"]
----
create cgSnapVolume userLabel=pass:quotes[_"cgVolumeName"_]
cgSnapImageID=pass:quotes[_"snapCGID:imageID"_]
members=pass:quotes[_(baseVolume1:repos_XXXX_] |
baseVolume1: (pass:quotes[_volumeGroupName_] pass:quotes[[_capacity=capacityValue_])] |
(baseVolume1:pass:quotes[_diskPoolName_] [capacity=pass:quotes[_capacityValue_]])
... baseVolumen:repos_YYYY |
baseVolumen: (pass:quotes[_volumeGroupName_] [capacity=pass:quotes[_capacityValue_]]) |
baseVolumen: (pass:quotes[_diskPoolName_] [capacity=pass:quotes{_capacityValue_]]))
repositoryFullLimit=pass:quotes[_percentValue_]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`userLabel`
 a| 
Der Name, den Sie dem von Ihnen erstellten Snapshot-Volumen der Konsistenzgruppe angeben möchten. Schließen Sie den Namen des Snapshot-Volumes der Konsistenzgruppe in doppelte Anführungszeichen (“ „).



 a| 
`cgSnapImageID`
 a| 
Der Name des Snapshot-Images in einer Konsistenzgruppe. Der Name eines Snapshot-Images besteht aus zwei Teilen:

* Der Name der Konsistenzgruppe
* Eine Kennung für das Snapshot-Image in der Konsistenzgruppe


Die Kennung für das Snapshot-Image kann eine der folgenden sein:

* `newest` - Verwenden Sie diese Option, wenn Sie das neueste Snapshot-Image anzeigen möchten, das in der Konsistenzgruppe erstellt wurde.
* `oldest` - Verwenden Sie diese Option, wenn Sie das früheste Snapshot Image anzeigen möchten, das in der Konsistenzgruppe erstellt wurde.


Schließen Sie den Namen des Snapshot-Bildes in doppelte Anführungszeichen (" ").

Sie können mehr als einen Snapshot-Bildnamen oder eine Sequenznummer eingeben. Schließen Sie alle Snapshot-Bildnamen in Klammern. Trennen Sie jeden Snapshot-Image-Namen mit einem Leerzeichen.



 a| 
`members`
 a| 
Der Bezeichner eines Basis-Volumes oder mehrerer Basisvolumes, die hinzugefügt werden sollen. Die Mitglieder-ID besteht aus dem Namen des Basis-Volumes, der mit dem Namen des Repository-Volumes verknüpft ist. Sie müssen einen Doppelpunkt (:) zwischen den beiden Namen verwenden. Schließen Sie alle Mitglieds-IDs in Klammern. Wenn Sie mehr als ein Mitglied eingeben, trennen Sie die Mitglieder mit einem Leerzeichen.

Wenn Sie den Mitgliedsparameter nicht verwenden, werden alle Mitglieder automatisch dem neuen Snapshot Volume der Konsistenzgruppe hinzugefügt.



 a| 
`repositoryVolume`
 a| 
Der Name des Repository-Volumes, das die Mitgliedsvolumes der Konsistenzgruppe enthält.

Es stehen zwei Optionen zur Verfügung, um den Namen eines Repository-Volumes festzulegen:

* Ein vorhandenes Repository-Volume verwenden: Name
* Erstellen Sie ein neues Repository-Volume, wenn Sie diesen Befehl ausführen


Der Name eines vorhandenen Repository-Volumes besteht aus zwei Teilen:

* Der Begriff „Repos“
* Eine vierstellige numerische Kennung, die die Speicherverwaltungssoftware dem Namen des Repository-Volumes zuweist


Schließen Sie den Namen des vorhandenen Repository-Volumes in doppelte Anführungszeichen (" ").

Wenn Sie bei Ausführung dieses Befehls ein neues Repository-Volume erstellen möchten, müssen Sie entweder den Namen einer Volume-Gruppe oder eines Laufwerk-Pools eingeben, in dem das Repository-Volume erstellt werden soll. Optional können Sie auch die Kapazität des Repository-Volumes festlegen. Wenn Sie die Kapazität definieren möchten, können Sie die folgenden Werte verwenden:

* Ein ganzzahliger Wert, der einen Prozentsatz der Basis-Volume-Kapazität darstellt
* Ein Dezimaltrennzeichen, der einen Prozentsatz der Basis-Volume-Kapazität darstellt
* Eine bestimmte Größe für das Repository-Volume erhalten. Größe ist in Einheiten von definiert `bytes`, `KB`, `MB`, `GB`, Oder `TB`.


Wenn Sie die Kapazitätsoption nicht nutzen, setzt die Storage-Managementsoftware die Kapazität auf 20 Prozent der Kapazität des Basis-Volume.

Bei Ausführung dieses Befehls erstellt die Speichermanagementsoftware das Repository-Volume für das Snapshot-Volume.



 a| 
`repositoryFullLimit`
 a| 
Der Prozentsatz der Repository-Kapazität, bei der sich das Snapshot Repository-Volume der Konsistenzgruppe fast voll nähert. Ganzzahlwerte verwenden. Beispielsweise bedeutet ein Wert von 70 70 Prozent.



 a| 
`readOnly`
 a| 
Die Einstellung, um zu bestimmen, ob Sie auf das Snapshot-Volumen schreiben können oder nur vom Snapshot-Volumen lesen. Wenn Sie auf das Snapshot-Volume schreiben möchten, verwenden Sie diesen Parameter nicht. Um das Schreiben auf das Snapshot-Volume zu verhindern, verwenden Sie diesen Parameter.

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Der Name eines Snapshot-Bildes hat zwei Teile, die durch einen Doppelpunkt (:) getrennt sind:

* Die Kennung der Snapshot-Gruppe
* Die Kennung des Snapshot-Images


Wenn Sie den nicht angeben `repositoryVolumeType` Oder `readOnly` Parameter: Die Storage-Managementsoftware wählt die Repositorys für das Snapshot-Volume der Konsistenzgruppe aus. Wenn die Volume-Gruppe oder der Festplatten-Pool, in dem sich das Basis-Volume befindet, nicht genügend Speicherplatz zur Verfügung steht, schlägt dieser Befehl fehl.

Der `create cgSnapVolume` Befehl enthält eindeutige Formulare, die durch die folgenden Beispiele erklärt werden:

* Erstellen eines Lese-/Schreib-Snapshot-Volumes für eine Snapshot-Konsistenzgruppe mit dem Namen „SnapCG1“, die drei Mitglieder hat: Cgm1, cgm2 und cgm3. Die Repository-Volumes sind bereits vorhanden und werden vom Benutzer in diesem Befehl ausgewählt.
+
[listing]
----
create cgSnapVolume userLabel="cgSnapVolume1"
cgSnapImageID="snapCG1:oldest"
members=(cgm1:repos_0010 cgm2:repos_0011 cgm3:repos_0007);
----
+
Beachten Sie die Verwendung des Doppelpunktes (:) im Namen des Snapshot-Images, das in das Snapshot-Volumen der Konsistenzgruppe aufgenommen werden soll. Der Doppelpunkt ist ein Trennzeichen, das den Namen des Snapshot-Volumes von einem bestimmten Snapshot-Image trennt, das Sie verwenden möchten. Sie können eine der folgenden Optionen nach dem Doppelpunkt verwenden:

+
** Ein Integer-Wert, der die tatsächliche Sequenznummer des Snapshot-Images ist.
** `newest` - Verwenden Sie diese Option, wenn Sie das neueste Snapshot-Image der Konsistenzgruppe anzeigen möchten.
** `oldest` - Verwenden Sie diese Option, wenn Sie das erste erstellte Snapshot-Bild anzeigen möchten. Durch die Verwendung des Doppelpunktes nach den Namen der Mitglieder der Snapshot-Consistency-Gruppe wird die Zuordnung zwischen dem Mitglied und einem Repository-Volume definiert. Beispiel: In `cgm1:repos_10`, Mitglied cgm1 ordnet das Repository Volume repos_0010 zu.


* Erstellen eines Lese-/Schreib-Snapshot-Volumes einer Snapshot-Konsistenzgruppe mit dem Namen „SnapCG1“ nur der Mitglieder cgm1 und cgm2:
+
[listing]
----
create cgSnapVolume userLabel="cgSnapVolume2"
cgSnapImageID="snapCG1:14214"
members=(cgm1:repos_1000 cgm2:repos_1001);
----
* Erstellen eines schreibgeschützten Snapshot-Volumes für Konsistenzgruppen auf einer Snapshot-Konsistenzgruppe mit dem Namen SnapCG1, die drei Mitglieder hat: Cgm1, cgm2 und cgm3:
+
[listing]
----
create cgSnapVolume userLabel="cgSnapVolume3"
cgSnapImageID="snapCG1:oldest" readOnly;
----
* Erstellen eines Snapshot-Volumes der Consistency Group, das ein Repository-volles Limit auf 60 Prozent auf einer Snapshot-Consistency Group namens SnapCG1 hat, das drei Mitglieder hat: Cgm1, cgm2 und cgm3:
+
[listing]
----
create cgSnapVolume userLabel="cgSnapVolume3"
cgSnapImageID="snapCG1:oldest"
repositoryFullLimit=60;
----
* Erstellen eines Snapshot-Volumes mit Lese-/Schreibvorgängen und automatischer Repository-Auswahl auf einer Snapshot-Consistency Group namens SnapCG1, die drei Mitglieder hat: Cgm1, cgm2 und cgm3:
+
[listing]
----
create cgSnapVolume userLabel="cgSnapVolume4"
cgSnapImageID="snapCG1:oldest";
----




== Minimale Firmware-Stufe

7.83
