---
permalink: commands-a-z/create-snmpcommunity.html 
sidebar: sidebar 
keywords: register, snmp, community 
summary: 'Der Befehl create snmpCommunity erstellt eine neue SNMP-Community (Simple Network Management Protocol), einen Community-Namensstring und registriert die neue Community als eine bekannte Einheit beim SNMP-Agenten. Jeder Versuch, eine neue Community mit demselben Namen wie eine vorhandene Community zu registrieren, wird abgelehnt und die Firmware gibt eine Fehlermeldung zurück.' 
---
= SNMP-Community registrieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create snmpCommunity` Befehl erstellt eine neue SNMP-Community (Simple Network Management Protocol), einen Community-Name-String und registriert die neue Community als eine bekannte Einheit beim SNMP-Agent. Jeder Versuch, eine neue Community mit demselben Namen wie eine vorhandene Community zu registrieren, wird abgelehnt und die Firmware gibt eine Fehlermeldung zurück.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E4000, E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Syntax

[source, cli, subs="+macros"]
----
create snmpCommunity communityName=pass:quotes[_"snmpCommunityName"_]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`communityName`
 a| 
Der Name der SNMP-Community, die Sie erstellen möchten. Schließen Sie den SNMP-Community-Namen in doppelte Anführungszeichen (" ").

|===


== Minimale Firmware-Stufe

8.30
