---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: Der Befehl „Create VolumeGroup“ erstellt entweder eine Volume-Gruppe mit freier Kapazität oder eine Volume-Gruppe mit einem Volume, wenn Sie einen Satz nicht zugewiesener Laufwerke eingeben. 
---
= Volume-Gruppe erstellen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `create volumeGroup` Befehl erstellt entweder eine Volume-Gruppe mit freier Kapazität oder eine Volume-Gruppe mit einem Volume, wenn Sie einen Satz nicht zugewiesener Laufwerke eingeben.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`drives`
 a| 
Die Laufwerke, die Sie der Volume-Gruppe zuweisen möchten, die Sie erstellen möchten. Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`.

Alle maximale Steckplatz-ID sind 24. Die Steckplatz-ID-Werte beginnen je nach Fachmodell bei 0 oder 1. Die Laufwerksfächer sind mit E2800 und E5700 Controllern kompatibel und besitzen die Steckplatz-ID-Nummern ab 0. Die Laufwerksfächer sind mit E2700 und E5600 Controllern kompatibel und verfügen ab 1 über die Steckplatz-ID.

Schließen Sie den Wert für Fach-ID, die Fach-ID und den Wert für die Steckplatz-ID in eckigen Klammern ([ ]) an.



 a| 
`raidLevel`
 a| 
Der RAID-Level der Volume-Gruppe, die das Volume enthält. Gültige Werte sind `0`, `1`, `3`, `5`, Oder `6`.



 a| 
`userLabel`
 a| 
Der Name, den Sie der neuen Volume-Gruppe geben möchten. Schließen Sie den Namen der Volume-Gruppe in doppelte Anführungszeichen (" ").



 a| 
`driveMediaType`
 a| 
Der Laufwerkstyp, den Sie für die Volume-Gruppe verwenden möchten

Sie müssen diesen Parameter verwenden, wenn Sie mehr als einen Laufwerkstyp im Speicher-Array haben.

Diese Datenträger sind gültig:

* `HDD` -- Verwenden Sie diese Option, wenn Sie Festplatten in der Laufwerksschublade haben
* `SSD` -- Verwenden Sie diese Option, wenn Sie Solid State-Laufwerke in der Laufwerksschublade haben
* `unknown` -- Verwenden Sie diese Option, wenn Sie nicht sicher sind, welche Arten von Datenträgern in der Laufwerksschublade sind
* `allMedia` -- Verwenden Sie diese Option, wenn Sie alle Arten von Datenträgern verwenden möchten, die sich in der Laufwerksschublade befinden




 a| 
`driveType`
 a| 
Der Laufwerkstyp, den Sie in der Volume-Gruppe verwenden möchten. Sie können keine unterschiedlichen Laufwerkstypen verwenden.

Sie müssen diesen Parameter verwenden, wenn Sie mehr als einen Laufwerkstyp im Speicher-Array haben.

Diese Laufwerkstypen sind gültig:

* `SAS`
* `NVMe4K`


Wenn Sie keinen Laufwerkstyp angeben, überprüft der Code nicht, ob die angegebenen Laufwerke von diesem Laufwerkstyp sind.



 a| 
`trayLossProtect`
 a| 
Die Einstellung zum erzwingen des Ablagefach-Verlustschutzes, wenn Sie die Volume-Gruppe erstellen. Um den Tray Loss Protection durchzusetzen, setzen Sie diesen Parameter auf `TRUE`. Der Standardwert ist `FALSE`.



 a| 
`drawerLossProtect`
 a| 
Die Einstellung zum erzwingen des Abschubeschutzes, wenn Sie die Volume-Gruppe erstellen. Um den Schutz des Schubladenverlusts durchzusetzen, setzen Sie diesen Parameter auf `TRUE`. Der Standardwert ist `FALSE`.



 a| 
`securityType`
 a| 
Die Einstellung zum Festlegen des Sicherheitsniveaus beim Erstellen der Volume-Gruppen und aller zugehörigen Volumes. Diese Einstellungen sind gültig:

* `none` -- die Volume-Gruppe und die Volumen sind nicht sicher.
* `capable` -- die Volume-Gruppe und die Volumes sind in der Lage, die Sicherheit einzustellen, aber die Sicherheit wurde nicht aktiviert.
* `enabled` -- die Volume-Gruppe und die Volumes haben die Sicherheit aktiviert.




 a| 
`resourceProvisioningCapable`
 a| 
Die Einstellung zur Angabe, ob Ressourcen-Provisioning-Funktionen aktiviert sind. Um die Ressourcenbereitstellung zu deaktivieren, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `TRUE`.

|===


== Laufwerke und Volume-Gruppen

Eine Volume-Gruppe ist ein Satz von Laufwerken, die logisch durch die Controller im Storage-Array gruppiert werden. Die Anzahl der Laufwerke in einer Volume-Gruppe beschränkt sich auf die RAID-Ebene und die Controller-Firmware. Wenn Sie eine Volume-Gruppe erstellen, befolgen Sie die folgenden Richtlinien:

* Ab der Firmware-Version 7.10 können Sie eine leere Volume-Gruppe erstellen, sodass Sie die Kapazität für eine spätere Verwendung reservieren können.
* Sie können Laufwerktypen nicht innerhalb einer einzelnen Volume-Gruppe kombinieren.
* Es ist nicht möglich, HDD- und SSD-Laufwerke innerhalb einer einzelnen Volume-Gruppe miteinander zu kombinieren.
* Die maximale Anzahl von Laufwerken in einer Volume-Gruppe hängt von folgenden Bedingungen ab:
+
** Der Typ des Controllers
** RAID-Level


* Die RAID-Level umfassen: 0, 1, 3, 5 und 6 .
+
** Eine Volume-Gruppe mit RAID-Level 3, RAID Level 5 oder RAID-Level 6 kann nicht mehr als 30 Laufwerke haben.
** Eine Volume-Gruppe mit RAID-Level 6 muss mindestens fünf Laufwerke aufweisen.
** Wenn eine Volume-Gruppe mit RAID Level 1 vier oder mehr Laufwerke hat, konvertiert die Storage-Managementsoftware die Volume-Gruppe automatisch in eine RAID-Level 10, also RAID Level 1 + RAID Level 0.


* Weitere Kriterien sind in den folgenden Tabellen zu finden, um den Schutz vor Schubladenverlusten zu aktivieren:


|===
| Ebene | Kriterien für den Schutz vor Verlust des Fachs | Mindestanzahl der benötigten Fächer 


 a| 
`Disk Pool`
 a| 
Der Laufwerk-Pool enthält nicht mehr als zwei Laufwerke in einem einzelnen Fach
 a| 
6



 a| 
`RAID 6`
 a| 
Die Volume-Gruppe enthält nicht mehr als zwei Laufwerke in einem einzelnen Fach
 a| 
3



 a| 
`RAID 3` Oder `RAID 5`
 a| 
Jedes Laufwerk in der Volume-Gruppe befindet sich in einem separaten Fach
 a| 
3



 a| 
`RAID 1`
 a| 
Jedes Laufwerk in einem RAID 1-Paar muss in einem separaten Fach untergebracht sein
 a| 
2



 a| 
`RAID 0`
 a| 
Der Schutz vor Laufwerksverlust kann nicht erreicht werden.
 a| 
Keine Angabe

|===
|===
| Ebene | Kriterien für den Schutz vor Schubladenverlust | Mindestanzahl der benötigten Schubladen 


 a| 
`Disk Pool`
 a| 
Der Pool umfasst Laufwerke aus allen fünf Schubladen und in jeder Schublade befindet sich eine gleiche Anzahl von Laufwerken. Ein Fach mit 60 Laufwerken kann einen Schubladenschutz erreichen, wenn der Laufwerk-Pool 15, 20, 25, 30, 35, 40, 45, 50, 55 oder 60 Laufwerke.
 a| 
5



 a| 
`RAID 6`
 a| 
Die Volume-Gruppe enthält nicht mehr als zwei Laufwerke in einem einzigen Einschub.
 a| 
3



 a| 
`RAID 3` Oder `RAID 5`
 a| 
Jedes Laufwerk in der Volume-Gruppe befindet sich in einem separaten Einschub.
 a| 
3



 a| 
`RAID 1`
 a| 
Jedes Laufwerk in einem gespiegelten Paar muss sich in einem separaten Fach befinden.
 a| 
2



 a| 
`RAID 0`
 a| 
Der Schutz vor Schubladenverlust kann nicht erreicht werden.
 a| 
Keine Angabe

|===


== Hot Spares

Bei Volume-Gruppen ist die Sicherung von Daten eine wertvolle Strategie, verfügbare Laufwerke im Storage Array als Hot Spare-Laufwerke zuzuweisen. Ein Hot Spare ist ein Laufwerk ohne Daten, das im Speicher-Array als Standby fungiert, falls ein Laufwerk in einer RAID 1-, RAID 3-, RAID 5- oder RAID 6-Volume-Gruppe ausfällt. Das Hot Spare fügt dem Speicher-Array eine weitere Ebene an Redundanz hinzu.

Im Allgemeinen müssen Hot-Spare-Laufwerke die Kapazitäten haben, die der verwendeten Kapazität auf den Laufwerken entsprechen oder größer sind, die sie sichern. Hot-Spare-Festplatten müssen vom gleichen Medientyp, vom selben Schnittstellentyp und von der gleichen Kapazität wie die Laufwerke sein, die sie sichern.

Wenn ein Laufwerk im Speicher-Array ausfällt, wird das Hot Spare normalerweise automatisch durch das ausgefallene Laufwerk ersetzt, ohne dass ein Eingreifen erforderlich ist. Wenn ein Hot Spare verfügbar ist, wenn ein Laufwerk ausfällt, verwendet der Controller Redundanzdatenparität, um die Daten auf dem Hot Spare zu rekonstruieren. Die Unterstützung für die Evakuierung von Daten ermöglicht außerdem das Kopieren von Daten auf ein Hot Spare, bevor die Software das Laufwerk als „ausgefallen“ markiert.

Nachdem das ausgefallene Laufwerk physisch ersetzt wurde, können Sie eine der folgenden Optionen zum Wiederherstellen der Daten nutzen:

Wenn Sie das ausgefallene Laufwerk ausgetauscht haben, werden die Daten aus dem Hot Spare wieder auf das Ersatzlaufwerk kopiert. Diese Aktion wird Copyback genannt.

Wenn Sie das Hot-Spare-Laufwerk als dauerhaftes Mitglied einer Volume-Gruppe angeben, ist der Copyback-Vorgang nicht erforderlich.

Die Verfügbarkeit von Ablagefach-Verlustschutz und Schubladenschutz für eine Volume-Gruppe hängt von der Position der Laufwerke ab, aus denen die Volume-Gruppe besteht. Der Schutz vor Verlust des Fachs und der Schutz vor Schubladenverlust können aufgrund eines ausgefallenen Laufwerks und der Position des Hot-Spare-Laufwerks verloren gehen. Um sicherzustellen, dass der Schutz vor Verlust des Fachs und der Schutz vor Schubladenverlust nicht beeinträchtigt werden, müssen Sie ein ausgefallenes Laufwerk austauschen, um den Kopiervorgang zu initiieren.

Das Speicher-Array wählt automatisch Data Assurance (da)-fähige Laufwerke für Hot-Spare-Abdeckung von da-fähigen Volumes aus.

Stellen Sie sicher, dass Sie im Speicher-Array über da-fähige Laufwerke verfügen, damit Hot-Spare-fähige Volumes abgedeckt werden können. Weitere Informationen zu da-fähigen Laufwerken finden Sie in der Data Assurance-Funktion.

Secure-fähige Laufwerke (FIPS und FDE) können als Hot Spare für sichere und nicht sichere Laufwerke verwendet werden. Nicht sichere Laufwerke können für andere nicht sichere Laufwerke und für sichere Laufwerke sorgen, wenn die Volume-Gruppe die Sicherheit nicht aktiviert hat. Eine FIPS-Volume-Gruppe kann nur ein FIPS-Laufwerk als Hot Spare verwenden. Sie können jedoch ein FIPS-Hot-Spare für nicht sichere, sichere und sichere Volume-Gruppen verwenden, die nicht sicher sind.

Wenn Sie kein Hot Spare besitzen, können Sie weiterhin ein ausgefallenes Laufwerk austauschen, während das Speicher-Array in Betrieb ist. Wenn das Laufwerk Teil einer RAID 1-, RAID 3-, RAID 5- oder RAID 6-Volume-Gruppe ist, verwendet der Controller Redundanzdatenparität, um die Daten automatisch auf dem Ersatzlaufwerk zu rekonstruieren. Diese Aktion wird Rekonstruktion genannt.



== Segmentgröße

Die Größe eines Segments bestimmt, wie viele Datenblöcke der Controller auf ein einzelnes Laufwerk in einem Volume schreibt, bevor Daten auf das nächste Laufwerk geschrieben werden. Jeder Datenblock speichert 512 Bytes an Daten. Ein Datenblock ist die kleinste Storage-Einheit. Die Größe eines Segments bestimmt, wie viele Datenblöcke er enthält. Ein 8-KB-Segment umfasst beispielsweise 16 Datenblöcke. Ein 64-KB-Segment umfasst 128 Datenblöcke.

Wenn Sie einen Wert für die Segmentgröße eingeben, wird der Wert anhand der unterstützten Werte geprüft, die der Controller zur Laufzeit zur Verfügung stellt. Wenn der eingegebene Wert ungültig ist, gibt der Controller eine Liste mit gültigen Werten zurück. Wenn Sie ein einzelnes Laufwerk für eine einzelne Anforderung verwenden, können andere Laufwerke gleichzeitig für die Bedienung anderer Anfragen verwendet werden. Befindet sich ein Volume in einer Umgebung, in der ein einzelner Benutzer große Dateneinheiten (wie Multimedia) überträgt, so wird die Performance maximiert, wenn eine einzelne Datentransferanfrage über ein einziges Daten-Stripe bedient wird. (Ein Daten-Stripe ist die Segmentgröße, die mit der Anzahl der Laufwerke in der Volume-Gruppe multipliziert wird, die für den Datentransfer verwendet werden.) In diesem Fall werden mehrere Laufwerke für dieselbe Anfrage genutzt, allerdings wird auf jedes Laufwerk nur einmal zugegriffen.

Um eine optimale Performance in einer Storage-Umgebung mit mehreren Benutzern oder Dateisystemen zu erzielen, legen Sie die Segmentgröße so fest, dass die Anzahl der Laufwerke minimiert wird, die zur Erfüllung einer Datentransferanfrage erforderlich sind.



== Verwendungshinweis

[NOTE]
====
Sie müssen keinen Wert für das eingeben `cacheReadPrefetch` Parameter oder der `segmentSize` Parameter. Wenn Sie keinen Wert eingeben, verwendet die Controller-Firmware das `usageHint` Parameter mit `fileSystem` Als Standardwert. Geben Sie einen Wert für das ein `usageHint` Parameter und ein Wert für das `cacheReadPrefetch` Parameter oder ein Wert für das `segmentSize` Parameter verursacht keinen Fehler. Der Wert, den Sie für das eingeben `cacheReadPrefetch` Parameter oder der `segmentSize` Parameter hat Priorität über den Wert für das `usageHint` Parameter. Die Einstellungen für Segmentgröße und Cache-Lese-Prefetch für verschiedene Nutzungshinweise sind in der folgenden Tabelle aufgeführt:

====
|===
| Nutzungshinweis | Segmentgröße einstellen | Dynamische Cache-Einstellungen für das Lesen in der Prefetch-Einstellung 


 a| 
File-System
 a| 
128 KB
 a| 
Aktiviert



 a| 
Datenbank
 a| 
128 KB
 a| 
Aktiviert



 a| 
Multimedia
 a| 
256 KB
 a| 
Aktiviert

|===


== Cache-Lese-Prefetch

Mit dem Cache-Lese-Prefetch kann der Controller zusätzliche Datenblöcke in den Cache kopieren, während der Controller Datenblöcke liest und kopiert, die vom Host von dem Laufwerk in den Cache angefordert werden. Dadurch erhöht sich die Wahrscheinlichkeit, dass zukünftige Datenanfragen aus dem Cache bedient werden können. Cache-Lese-Prefetch ist für Multimedia-Anwendungen, die sequenzielle Datentransfers verwenden, wichtig. Gültige Werte für das `cacheReadPrefetch` Parameter sind `TRUE` Oder `FALSE`. Die Standardeinstellung lautet `TRUE`.



== Sicherheitstyp

Verwenden Sie die `securityType` Parameter zum Festlegen der Sicherheitseinstellungen für das Speicher-Array.

Bevor Sie den einstellen können `securityType` Parameter an `enabled`, Sie müssen einen Sicherheitsschlüssel für das Speicher-Array erstellen. Verwenden Sie die `create storageArray securityKey` Befehl zum Erstellen eines Speicherarray-Sicherheitsschlüssels. Diese Befehle beziehen sich auf den Sicherheitsschlüssel:

* `create storageArray securityKey`
* `export storageArray securityKey`
* `import storageArray securityKey`
* `set storageArray securityKey`
* `enable volumeGroup [volumeGroupName] security`
* `enable diskPool [diskPoolName] security`




== Sichere Laufwerke

Sichere Laufwerke können entweder vollständige Festplattenverschlüsselung (Full Disk Encryption, FDE) oder FIPS-Laufwerke (Federal Information Processing Standard) sein. Verwenden Sie die `secureDrives` Parameter, um den Typ der zu verwendenden sicheren Laufwerke anzugeben. Die Werte, die Sie verwenden können, sind `fips` Und `fde`.



== Data Assurance Management

Die Data Assurance (da)-Funktion erhöht die Datenintegrität im gesamten Storage-System. DA ermöglicht es dem Storage-Array, nach Fehlern zu suchen, die auftreten können, wenn Daten zwischen Hosts und Laufwerken verschoben werden. Wenn diese Funktion aktiviert ist, hängt das Speicherarray die Fehlerprüfungscodes (auch zyklische Redundanzprüfungen oder CRCs genannt) an jeden Datenblock im Volume an. Nach dem Verschieben eines Datenblocks ermittelt das Speicher-Array anhand dieser CRC-Codes, ob während der Übertragung Fehler aufgetreten sind. Potenziell beschädigte Daten werden weder auf Festplatte geschrieben noch an den Host zurückgegeben.

Wenn Sie die da-Funktion verwenden möchten, beginnen Sie mit einem Pool oder einer Volume-Gruppe, der nur Laufwerke enthält, die da unterstützen. Erstellen Sie dann da-fähige Volumes. Ordnen Sie diese da-fähigen Volumes schließlich dem Host mithilfe einer E/A-Schnittstelle zu, die für da geeignet ist. Zu den I/O-Schnittstellen, die da unterstützen, gehören Fibre Channel, SAS und iSER over InfiniBand (iSCSI-Erweiterungen für RDMA/IB). DA wird nicht durch iSCSI über Ethernet oder durch die SRP über InfiniBand unterstützt.

[NOTE]
====
Wenn alle Laufwerke für die da-Fähigkeit geeignet sind, können Sie die einstellen `dataAssurance` Parameter an `enabled` Und dann mit bestimmten Operationen da verwenden. Sie können beispielsweise eine Volume-Gruppe mit da-fähigen Laufwerken erstellen und anschließend ein Volume in dieser Volume-Gruppe erstellen, die für da aktiviert ist. Andere Vorgänge, bei denen ein DA-fähiges Volume verwendet wird, verfügen über Optionen zur Unterstützung der da-Funktion.

====
Wenn der `dataAssurance` Parameter ist auf festgelegt `enabled`, Nur Data Assurance-fähige Laufwerke werden für Volume-Kandidaten in Betracht gezogen werden. Anderenfalls werden sowohl Data Assurance-fähige als auch nicht Data Assurance-fähige Laufwerke berücksichtigt. Sind nur Data Assurance Drives verfügbar, wird die neue Volume-Gruppe mit den aktivierten Data Assurance-Laufwerken erstellt.



== Minimale Firmware-Stufe

7.10

7.50 fügt die hinzu `securityType` Parameter.

7.60 fügt die hinzu `drawerID` Benutzereingaben, der `driveMediaType` Parameter, und das `drawerLossProtect` Parameter.

7.75 fügt die hinzu `dataAssurance` Parameter.

8.63 fügt die hinzu `resourceProvisioningCapable` Parameter.
