---
permalink: commands-a-z/create-snmptrapdestination.html 
sidebar: sidebar 
keywords: register, snmp, trap, destination 
summary: 'Der Befehl create snmpTrapDestination erstellt ein neues SNMP-Trap-Ziel (Simple Network Management Protocol). Ein Trap-Ziel ist der SNMP-Manager, der die Trap-Meldungen empfängt.' 
---
= SNMP-Trap-Ziel registrieren
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `create snmpTrapDestination` Befehl erstellt ein neues SNMP-Trap-Ziel (Simple Network Management Protocol). Ein Trap-Ziel ist der SNMP-Manager, der die Trap-Meldungen empfängt.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage-Admin“ oder „Support-Admin“ vorhanden sein.



== Syntax

[listing, subs="+macros"]
----
create snmpTrapDestination trapReceiverIP=ipAddress
    (communityName=pass:quotes[_"communityName" | (userName="userName"_] [engineId=(local | engineId)]))
    [sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`trapReceiverIP`
 a| 
Die IP-Adresse des SNMP-Managers, an den Sie Trap-Nachrichten senden möchten.



 a| 
`communityName`
 a| 
Der Name der SNMP-Community, für die Sie Trap-Nachrichten senden möchten.



 a| 
`userName`
 a| 
Der Name des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten.



 a| 
`engineId`
 a| 
Die Engine-ID des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten. Die Engine-ID ist erforderlich, wenn mehr als ein USM-Benutzer mit demselben Benutzernamen vorhanden ist. Der Wert kann „[.code]``local``„ Die Angabe des lokalen SNMP-Agenten ist der autorisierende Agent oder eine sechzimale Ziffernfolge, um eine Remote-SNMP-Agent-Engine-ID anzugeben.



 a| 
`sendAuthenticationFailureTraps`
 a| 
Dieser Parameter aktiviert oder deaktiviert das Senden von Authentifizierungsfehlern an einen SNMP-Manager. Um Authentifizierungsfehler zu senden, setzen Sie den Parameter auf `TRUE`. Um zu verhindern, dass Authentifizierungsfehler gesendet werden, setzen Sie den Parameter auf `FALSE`. Die Standardeinstellung lautet `TRUE`.

|===


== Minimale Firmware-Stufe

8.30
