---
permalink: commands-a-z/create-host.html 
sidebar: sidebar 
keywords: create, host 
summary: Der Befehl zum Erstellen eines Hosts erstellt einen neuen Host. 
---
= Host erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `create host` Befehl erstellt einen neuen Host.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

Wenn Sie bei E2700 und E5600 Storage-Arrays keine Host-Gruppe angeben, in der der neue Host erstellt werden soll, wird der neue Host in der Standardgruppe erstellt.



== Syntax

[listing, subs="+macros"]
----
create host userLabel=pass:quotes[_"hostName"_]
[hostGroup=pass:quotes[(_"hostGroupName"_] | defaultGroup)]
[hostType=(hostTypeIndexLabel | hostTypeIndexNumber)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`userLabel`
 a| 
Der Name, den Sie dem von Ihnen erstellten Host geben möchten. Schließen Sie den Hostnamen in doppelte Anführungszeichen (" ").



 a| 
`hostGroup`
 a| 
Der Name der Host-Gruppe, in der Sie einen neuen Host erstellen möchten. Schließen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen (" "). (Wenn keine Hostgruppe vorhanden ist, können Sie eine neue Hostgruppe mithilfe der erstellen `create hostGroup` Befehl.) Der `defaultGroup` Option ist die Host-Gruppe, die den Host enthält, dem das Volume zugeordnet ist.



 a| 
`hostType`
 a| 
Das Indexetikett oder die Indexnummer, die den Hosttyp identifiziert. Verwenden Sie die `show storageArray hostTypeTable` Befehl zum Generieren einer Liste der verfügbaren Host-Typ-IDs. Wenn der Host-Typ Sonderzeichen hat, setzen Sie den Hosttyp in doppelte Anführungszeichen („ “).

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Bindestriche und Unterstrichen für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Ein Host ist ein Computer, der mit dem Speicherarray verbunden ist und über die Host-Ports auf die Volumes auf dem Speicher-Array zugreift. Sie können spezifische Zuordnungen zu einem einzelnen Host definieren. Sie können den Host auch einer Host-Gruppe zuweisen, die den Zugriff auf ein oder mehrere Volumes freigibt.

Eine Host-Gruppe ist ein optionales topologisches Element, das Sie definieren können, ob Sie eine Sammlung von Hosts bestimmen möchten, die Zugriff auf dieselben Volumes haben. Die Host-Gruppe ist eine logische Einheit. Definieren Sie eine Host-Gruppe nur, wenn Sie über zwei oder mehr Hosts verfügen, die sich auf dieselben Volumes zugreifen.

Wenn Sie keine Host-Gruppe angeben, in der der erstellte Host platziert werden soll, gehört der neu definierte Host zur Standard-Host-Gruppe.



== Minimale Firmware-Stufe

5.20

7.10 fügt die hinzu `hostType` Parameter.
