---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: Mit der Funktion „Storage Array deaktivieren“ wird die Funktion „Asynchronous Mirroring“ deaktiviert. 
---
= Deaktivieren Sie die asynchrone Spiegelung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `deactivate storageArray feature` Deaktiviert die Funktion Asynchronous Mirroring.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Alle bestehenden asynchronen Spiegelgruppen oder asynchronen gespiegelten Paare müssen aus dem lokalen Storage-Array und dem Remote-Storage-Array gelöscht werden, bevor die Funktion zur asynchronen Spiegelung deaktiviert werden kann.



== Syntax

[source, cli]
----
deactivate storageArray feature=asyncRemoteMirror
----


== Parameter

Keine.



== Minimale Firmware-Stufe

7.84
