---
permalink: commands-a-z/deactivate-storagearray.html 
sidebar: sidebar 
keywords: deactivate, asynchronous, mirroring 
summary: Mit der Funktion „Storage Array deaktivieren“ wird die Funktion „Asynchronous Mirroring“ deaktiviert. 
---
= Asynchrone Spiegelung deaktivieren - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `deactivate storageArray feature` Deaktiviert die Funktion Asynchronous Mirroring.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600 und EF300 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600 oder EF300 Storage Array auszuführen, ist die Rolle Storage Admin erforderlich.



[[context]]
== Kontext

Alle bestehenden asynchronen Spiegelgruppen oder asynchronen gespiegelten Paare müssen aus dem lokalen Storage-Array und dem Remote-Storage-Array gelöscht werden, bevor die Funktion zur asynchronen Spiegelung deaktiviert werden kann.



[[syntax]]
== Syntax

[source, cli]
----
deactivate storageArray feature=asyncRemoteMirror
----


[[parameters]]
== Parameter

Keine.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.84
