---
permalink: commands-a-z/delete-snmpcommunity.html 
sidebar: sidebar 
keywords: delete, snmpcommunity, command, existing, simple, network, management, protocol, community, previously, create, effective, unregister, trap, destination, associate, remove 
summary: 'Der Befehl delete snmpCommunity löscht eine bestehende SNMP-Community (Simple Network Management Protocol), die Sie zuvor mit dem Befehl create snmpCommunity erstellt und registriert haben. Durch das Löschen einer SNMP-Community wird die Registrierung der Community effektiv aufgehoben. Alle mit dieser Community verknüpften Trap-Ziele werden ebenfalls entfernt.' 
---
= SNMP-Community abmelden – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete snmpCommunity` Befehl löscht eine vorhandene SNMP-Community (Simple Network Management Protocol), die Sie zuvor mit dem erstellt und registriert haben `create snmpCommunity` Befehl. Durch das Löschen einer SNMP-Community wird die Registrierung der Community effektiv aufgehoben. Alle mit dieser Community verknüpften Trap-Ziele werden ebenfalls entfernt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete snmpCommunity communityName="_snmpCommunityName_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`communityName`
 a| 
Der Name der SNMP-Community, die Sie löschen möchten. Schließen Sie den SNMP-Community-Namen in doppelte Anführungszeichen (" ").

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.30
