---
permalink: commands-a-z/delete-syslog.html 
sidebar: sidebar 
keywords: delete, syslog, command, servers, configuration, alerts, array, support, role 
summary: Der Befehl „delete syslog“ löscht einen oder mehrere Server aus der Syslog-Konfiguration, sodass keine Warnmeldungen mehr empfangen werden. 
---
= Syslog-Server löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete syslog` Befehl löscht einen oder mehrere Server aus der Syslog-Konfiguration, sodass keine Warnmeldungen mehr empfangen werden.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Speichersystem auszuführen, müssen Sie die Rolle Storage Admin oder Support Admin haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
delete syslog (allServers | serverAddresses pass:quotes[[_serverAddress1_ ... _serverAddressN_]])
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allServers`
 a| 
Ermöglicht dem Benutzer, alle Syslog-Server zu löschen.



 a| 
`serverAddresses`
 a| 
Ermöglicht dem Benutzer, die Syslog-Server zu löschen. Umschließen Sie die Server in eckigen Klammern ([ ]).

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "delete syslog allServers;

SMcli -n Array1 -c "delete syslog serverAddresses ["serverName1.company.com"]";

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
