---
permalink: commands-a-z/delete-emailalert.html 
sidebar: sidebar 
keywords: delete, email, alert, recipient 
summary: Mit dem Befehl „emailAlert löschen“ werden E-Mail-Adressen der Empfänger aus der Konfiguration für E-Mail-Warnungen gelöscht. 
---
= Empfänger von E-Mail-Benachrichtigungen löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete emailAlert` Befehl löscht Empfänger-E-Mail-Adressen aus der E-Mail-Alarmkonfiguration.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E4000, E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Syntax

[source, cli, subs="+macros"]
----
delete emailAlert
       (allEmailRecipients |
        emailRecipients pass:quotes[[_emailAddress1 ... emailAddressN_]])
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`allEmailRecipients`
 a| 
Ermöglicht das Löschen aller E-Mail-Empfänger.



 a| 
`emailRecipients`
 a| 
Ermöglicht das Löschen der Empfängeradressen. Schließen Sie die E-Mail-Adressen in eckige Klammern ([ ]).

|===


== Beispiele

[listing]
----

SMcli -n Array1 -c "delete emailAlert allEmailRecipients;"

SMcli -n Array1 -c "delete emailAlert emailRecipients ["person1@email.domain.com" "person3@email.domain.com"];"

SMcli completed successfully.
----


== Minimale Firmware-Stufe

8.40
