---
permalink: commands-a-z/delete-ssdcache.html 
sidebar: sidebar 
keywords: delete, cache, command, data, purged, array, support, role, parameter 
summary: Mit dem Befehl delete ssdCache wird der SSD-Cache gelöscht. Alle Daten im SSD-Cache werden gelöscht. 
---
= Löschen des SSD-Caches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete ssdCache` Mit dem Befehl wird der SSD-Cache gelöscht. Alle Daten im SSD-Cache werden gelöscht.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Support Admin verfügen.



== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete ssdCache [_ssdCacheName_]]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, den Sie löschen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
