---
permalink: commands-a-z/delete-hostgroup.html 
sidebar: sidebar 
keywords: delete, hostgroup, command, support, role 
summary: Mit dem Befehl „hostGroup löschen“ wird eine Host-Gruppe gelöscht. 
---
= Hostgruppe löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete hostGroup` Befehl löscht eine Host-Gruppe.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
*Mögliche Beschädigung der Speicher-Array-Konfiguration* -- dieser Befehl löscht alle Host-Definitionen in der Host-Gruppe.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete hostGroup [_hostGroupName_]]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`hostGroup`
 a| 
Der Name der Host-Gruppe, die Sie löschen möchten. Fügen Sie den Namen der Host-Gruppe in eckige Klammern ([ ]) ein. Wenn der Name der Host-Gruppe Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


[[notes]]
== Hinweise

Eine Host-Gruppe ist ein optionales topologisches Element, das eine Sammlung von Hosts ist, die den Zugriff auf dieselben Volumes teilen. Die Host-Gruppe ist eine logische Einheit.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

5.20
