---
permalink: commands-a-z/delete-iscsiinitiator.html 
sidebar: sidebar 
keywords: delete, initiator, command, specific, object, supported, array, role 
summary: Der Befehl delete iscsiInitiator löscht ein bestimmtes iSCSI-Initiator-Objekt. 
---
= iSCSI-Initiator löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete iscsiInitiator` Befehl löscht ein bestimmtes iSCSI-Initiator-Objekt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.

[IMPORTANT]
====
Dieser Befehl ist veraltet und wird von ersetzt xref:delete-initiator.adoc[Initiator löschen] Befehl.

====


[[syntax]]
== Syntax

[source, cli]
----
delete iscsiInitiator (<"iscsiID"> | ["name"])
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`iscsiInitiator`
 a| 
Die Kennung des iSCSI-Initiators, den Sie löschen möchten. Die Kennung des iSCSI-Initiators kann eine iSCSI-ID oder ein eindeutiger Name sein.

Schließen Sie eine iSCSI-ID in doppelte Anführungszeichen (“ „) in Winkelklammern (< >).

Schließen Sie den Namen in doppelte Anführungszeichen (" ") in eckigen Klammern ([ ]) ein.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10

8.41 dieser Befehl ist veraltet.
