---
permalink: commands-a-z/delete-sgsnapvolume.html 
sidebar: sidebar 
keywords: delte, snapvolume, command, snapshot, consistency, group, optionally, repository, members 
summary: Mit dem Befehl delete sgSnapVolume wird das Snapshot Volume einer Konsistenzgruppe gelöscht. Optional können Sie auch die Repository-Mitglieder löschen. 
---
= Konsistenzgruppen-Snapshot-Volume löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete sgSnapVolume` Mit dem Befehl wird das Snapshot Volume einer Konsistenzgruppe gelöscht. Optional können Sie auch die Repository-Mitglieder löschen.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete cgSnapVolume ["_snapVolumeName_"]]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`cgSnapVolume`
 a| 
Der Name des Snapshot-Volumes der Konsistenzgruppe, das Sie löschen möchten. Schließen Sie den Namen des Snapshot-Volumes der Konsistenzgruppe in doppelte Anführungszeichen („ ") in eckigen Klammern ([ ]) ein.



 a| 
`deleteRepositoryMembers`
 a| 
Der Parameter zum Speichern oder Löschen der Mitgliedvolumes. Um die Mitgliedsvolumes zu speichern, setzen Sie diesen Parameter auf `TRUE`. Um die Mitgliedsvolumes zu löschen, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `TRUE`.

|===


== Minimale Firmware-Stufe

7.83
