---
permalink: commands-a-z/delete-storagearray-directoryservers.html 
sidebar: sidebar 
keywords: delete, storage, array, directory, servers, command, allow, directory, role 
summary: Mit dem Befehl delete storageArray DirectoryServers können Sie einen oder mehrere Verzeichnisserver löschen. 
---
= Speicherarray-Verzeichnisserver löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete storageArray directoryServers` Mit Befehl können Sie einen oder mehrere Verzeichnisserver löschen.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete storageArray (allDirectoryServers |
 directoryServers ["_domainId1_" ... "_domainIdN_"])
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allDirectoryServers`
 a| 
Ermöglicht das Löschen aller Verzeichnisserver.



 a| 
`directoryServers`
 a| 
Ermöglicht Ihnen, einen oder mehrere zu löschende Verzeichnisserver anzugeben, die jeweils mit der Domänen-ID identifiziert werden.

[NOTE]
====
Schließen Sie die IDs in eckigen Klammern ([ ]). Wenn Sie mehr als eine liefern, trennen Sie sie mit einem Raum.

====
|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "delete storageArray directoryServers ["domain1" "domain3"];"

SMcli -n Array1 -c "delete storageArray allDirectoryServers;"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40 fügt den Befehl hinzu.
