---
permalink: commands-a-z/delete-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, key, management, certificate, command, remove, install, external 
summary: Der Befehl delete storageArray keyManagementCertificate entfernt das installierte externe Schlüsselverwaltungs-Zertifikat aus dem Speicher-Array. 
---
= Installiertes externes Schlüsselverwaltungszertifikat entfernen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete storageArray keyManagementCertificate` Mit dem Befehl wird das installierte externe Verschlüsselungsmanagementzertifikat aus dem Speicher-Array entfernt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete storageArray keyManagementCertificate certificateType=_certificate_type_]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`certificateType`
 a| 
Hier können Sie den zu löschenden Zertifikatstyp angeben. Gültige Auswahlmöglichkeiten: `client` Oder `server`.

|===


[[example]]
== Beispiel

[listing]
----
 SMcli -n Array1 -c "delete storageArray keyManagementCertificate certificateType="client";"

   SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
