---
permalink: commands-a-z/delete-initiator.html 
sidebar: sidebar 
keywords: delete, initiator, command, object, supported, array, role 
summary: Mit dem Befehl delete Initiator wird das Initiator-Objekt gelöscht. 
---
= Initiator löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete initiator` Mit dem Befehl wird das Initiator-Objekt gelöscht.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

[IMPORTANT]
====
Mit diesem Befehl wird die veraltete Version ersetzt xref:delete-iscsiinitiator.adoc[ISCSI-Initiator löschen] Befehl.

====
[NOTE]
====
Dieser Befehl ist nur für iSCSI, iSER, NVMe over RoCE, NVMe over InfiniBand und NVMe over Fibre Channel anwendbar.

====


[[syntax]]
== Syntax

[source, cli]
----
delete initiator (["initiatorName"] | <"initiatorQualifiedName">)
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`initiator`
 a| 
Ermöglicht Ihnen die Angabe der Initiator-ID, für die Sie löschen möchten. Schließen Sie den Namen in doppelte Anführungszeichen („` "`). Sie müssen den Namen auch in eckige Klammern ([ ]) einfügen, wenn der Wert ein Benutzeretikett oder Winkel Klammern ( ) ist, wenn der Wert ein qualifizierter Name ist (z.B. iqn oder nqn).

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.41
