---
permalink: commands-a-z/delete-hostport.html 
sidebar: sidebar 
keywords: delete, hostport, command, host, port, identification 
summary: Mit dem Befehl delete hostPort wird eine Host-Port-Identifizierung gelöscht. 
---
= Host-Port löschen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete hostPort` Befehl löscht eine Host-Port-ID.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Die Identifizierung ist ein Software-Wert, der den physischen Host-Port zum Controller darstellt. Durch Löschen der Identifizierung erkennt der Controller keine Anweisungen und Daten mehr vom Host-Port.

[IMPORTANT]
====
Dieser Befehl funktioniert in einer iSCSI-Umgebung nicht, in der die Host-Ports als Initiatoren gelten. Verwenden Sie stattdessen die `delete iscsiInitiator` Befehl. Siehe xref:delete-iscsiinitiator.adoc[ISCSI-Initiator löschen].

====


[[syntax]]
== Syntax

[source, cli]
----
delete hostPort [hostPortName]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`hostPort`
 a| 
Der Name des Host-Ports, den Sie löschen möchten. Schließen Sie den Namen des Host-Ports in eckige Klammern ([ ]) an. Wenn der Name des Host-Ports Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen auch in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


[[notes]]
== Hinweise

Ein Host-Port ist eine physische Verbindung auf einem Hostadapter, der sich auf einem Hostcomputer befindet. Ein Host-Port bietet einen Host-Zugriff auf die Volumes in einem Speicher-Array.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

5.20
