---
permalink: commands-a-z/delete-snapgroup.html 
sidebar: sidebar 
keywords: delete, snapgroup, command, entire, snapshot, group, option, associate, repository, volume 
summary: Der Befehl delete snapGroup löscht eine ganze Snapshot-Gruppe und optional die zugeordneten Repository Volumes. 
---
= Snapshot-Gruppe löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `delete snapGroup` Befehl einer ganzen Snapshot-Gruppe und optional den zugeordneten Repository-Volumes.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

[NOTE]
====
*Mögliche Schäden an der Speicher-Array-Konfiguration* -- Alle Daten in der Snapshot-Gruppe gehen verloren, sobald Sie diesen Befehl ausführen.

====


== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[delete snapGroup ["_snapGroupName_"]]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`snapGroup`
 a| 
Der Name der Snapshot-Gruppe, die Sie löschen möchten. Schließen Sie den Namen der Snapshot-Gruppe in doppelte Anführungszeichen (" ") in eckigen Klammern ([ ]) ein.



 a| 
`deleteRepositoryMembers`
 a| 
Der Parameter zum Löschen oder Speichern der Repository-Volumes. Um die Repository-Volumes zu löschen, setzen Sie diesen Parameter auf `TRUE`. Um die Repository-Volumes zu speichern, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `FALSE`.

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Benutzerbezeichnung verwenden. Benutzeretiketten können maximal 30 Zeichen lang sein.

Sie können eine Snapshot-Gruppe löschen, wenn sie leer ist oder Snapshot-Images enthält. Alle Snapshot Images in der Snapshot-Gruppe werden zusammen mit der Snapshot-Gruppe gelöscht. Wenn ein vorhandenes Snapshot-Image innerhalb der Snapshot-Gruppe ein Snapshot-Volume zugeordnet ist, wird jedes Snapshot-Volume angehalten und vom Snapshot-Image getrennt. Wenn Sie eine Snapshot-Gruppe löschen, wird auch das zugehörige Repository-Volume gelöscht. Standardmäßig werden alle Mitglied-Volumes im Repository-Volume als nicht verwendete, nicht zugeordnete Standard-Volumes aufbewahrt. Um die Mitgliedvolumes zu entfernen, legen Sie den fest `deleteRepositoryMembers` Parameter an `TRUE`, Oder verwenden Sie diesen Parameter nicht. Um die Mitgliedsvolumes zu behalten, legen Sie den fest `deleteRepositoryMembers` Parameter an `FALSE`.



== Minimale Firmware-Stufe

7.83
