---
permalink: commands-a-z/delete-storagearray-trustedcertificate.html 
sidebar: sidebar 
keywords: delete, storage, array, trusted, certificate, command, remove, specified, installed, web, servers 
summary: Der Befehl delete storageArray TrustedCertificate entfernt die vom angegebenen Benutzer installierten CA-Zertifikate von den Web-Servern des Arrays. 
---
= Installierte vertrauenswürdige CA-Zertifikate entfernen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `delete storageArray trustedCertificate` Mit dem Befehl werden die vom Benutzer installierten CA-Zertifikate von den Webservern des Arrays entfernt.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Security Admin“ vorhanden sein.



== Syntax

[listing, subs="+macros"]
----

pass:quotes[delete storageArray trustedCertificate [(allUserInstalled |
aliases=("_alias1_" ... "_aliasN_]"))]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allUserInstalled`
 a| 
Hier können Sie das Entfernen aller vom Benutzer installierten Zertifikate angeben.



 a| 
`aliases`
 a| 
Ermöglicht es Ihnen, ein oder mehrere CA-Zertifikate anzugeben, die unter Verwendung der Aliasnamen gelöscht werden sollen oder alle anzugeben. Die Aliase können von allen Controllern stammen. Schließen Sie alle Aliase in Klammern. Wenn Sie mehrere Alias eingeben, trennen Sie sie mit einem Leerzeichen.

|===


== Beispiele

[listing]
----

SMcli -n Array1 -c "delete storageArray trustedCertificate allUserInstalled;"

SMcli -n Array1 -c "delete storageArray trustedCertificate
   aliases=("19527b38-8d26-44e5-8c7f-5bf2ca9db7cf" "04bf744c-413a-49f1-9666-88d74189591d");"

SMcli completed successfully.
----


== Minimale Firmware-Stufe

8.40
