---
permalink: commands-a-z/disable-storagearray-externalkeymanagement-file.html 
sidebar: sidebar 
keywords: disable, storage, array, external, management, file, command, disable, security, key, full, disk, encryption, drives 
summary: Der Befehl „disable storageArray externaliKeyManagement file“ deaktiviert die Verwaltung externer Sicherheitsschlüssel für ein Speicherarray mit vollständigen Festplatten. 
---
= Externe Sicherheitsschlüsselverwaltung deaktivieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `disable storageArray externalKeyManagement file` Mit dem Befehl wird die Verwaltung externer Sicherheitsschlüssel für ein Speicher-Array mit vollständigen Festplatten-Verschlüsselung deaktiviert.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
disable storageArray externalKeyManagement
pass:quotes[file="_fileName_"]
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[saveFile=(_TRUE_ | _FALSE_)]
----


[[context]]
== Kontext

[NOTE]
====
Dieser Befehl ermöglicht das interne Verschlüsselungsmanagement als alternative Form der Laufwerkssicherheit.

====
[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in dem die interne Sicherheitsschlüsseldatei gespeichert wird. Beispiel:

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[IMPORTANT]
====
Der Dateiname muss über eine Erweiterung von verfügen `.slk`.

====


 a| 
`passPhrase`
 a| 
Eine Zeichenkette, die den Sicherheitsschlüssel verschlüsselt, sodass Sie den Sicherheitsschlüssel in einer externen Datei speichern können.



 a| 
`saveFile`
 a| 
Überprüft und speichert den Sicherheitsschlüssel in einer Datei. Auf einstellen `FALSE` So speichern und überprüfen Sie den Sicherheitsschlüssel nicht in einer Datei. Der Standardwert ist `TRUE`.

|===


[[notes]]
== Hinweise

Ihr Passphrase muss folgende Kriterien erfüllen:

* Muss zwischen acht und 32 Zeichen lang sein.
* Kein Leerzeichen.
* Muss mindestens einen Großbuchstaben enthalten.
* Muss mindestens einen Kleinbuchstaben enthalten.
* Muss mindestens eine Zahl enthalten.
* Muss mindestens ein nicht-alphanumerisches Zeichen enthalten, z. B. @ +.


[NOTE]
====
Wenn Ihr Passphrase diese Kriterien nicht erfüllt, erhalten Sie eine Fehlermeldung.

====


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40

8.70 fügt die hinzu `saveFile` Parameter.
