---
permalink: commands-a-z/download-controller-cacertificate.html 
sidebar: sidebar 
keywords: download, controller, certificate, command, install, root, intermediate, web, servers, validate, array, roles, context 
summary: Der Download-Controller caCertificate Befehl installiert die Root/Intermediate CA-Zertifikate auf den Web-Servern der Controller, um das signierte Web-Server-Zertifikat zu validieren. 
---
= Installieren Sie Stamm-/Zwischen-CA-Zertifikate – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `download controller caCertificate` Der Befehl installiert die Root-/Intermediate-CA-Zertifikate auf den Web-Servern der Controller, um das vom Webserver signierte Zertifikat zu validieren.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[context]]
== Kontext

Führen Sie diese Aktion für jeden Controller aus.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
download controller[(a|b)] caCertificate pass:quotes[[alias="_string_"]]
         pass:quotes[file="_filename_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`controller`
 a| 
Hier können Sie den Controller angeben, auf dem Sie das Root-/Intermediate-signiertes Zertifikat installieren möchten. Gültige Controller-IDs sind A oder b, wobei A der Controller in Steckplatz A ist und b der Controller in Steckplatz B ist Schließen Sie die Controller-Kennung in eckige Klammern ([ ]).



 a| 
`alias`
 a| 
Ermöglicht die Angabe eines Alias zur Darstellung des Root-/Zwischenzertifikats. Mit diesem Alias werden Informationen zu den Stamm-/Zwischenzertifikaten nachschlagen oder gelöscht. Ein Alias ist mit einem Root-/Zwischenzertifikat verknüpft und muss eindeutig sein.



 a| 
`file`
 a| 
Ermöglicht die Angabe der Datei, die das Root-/Zwischenzertifikat enthält. Zulässige Erweiterungen sind .pem, .cer, .crt und .der.

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "download controller[a] caCertificate alias="myAlias" file="C:\rootCA1.cer";"
SMcli -n Array1 -c "download controller[b] caCertificate file="C:\rootCA1.cer";"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
