---
permalink: commands-a-z/download-storagearray-drivefirmware-file.html 
sidebar: sidebar 
keywords: download, storage, array, drive, firmware, command, images, roles, supported 
summary: Mit dem Befehl herunterlad storageArray driveFirmware file werden Firmware-Images auf alle Laufwerke im Speicher-Array heruntergeladen. 
---
= Firmware des Speicherarrays herunterladen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `download storageArray driveFirmware file` Mit Befehl werden Firmware-Images auf alle Laufwerke im Speicher-Array heruntergeladen.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage-Admin“ oder „Support-Admin“ vorhanden sein.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[download storageArray driveFirmware file="_filename_"]
pass:quotes[[file="_filename2_"... file="_filenameN_"]]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname der Datei, die das Firmware-Image enthält. Schließen Sie den Dateipfad und den Dateinamen des Firmware-Images in doppelte Anführungszeichen („ “). Beispiel:

`file="C:\Program Files\CLI\dnld\sadrvfrm.dlp"`

Gültige Dateinamen haben ein `.dlp` Erweiterung.

|===


== Hinweise

Wenn Sie diesen Befehl ausführen, können Sie mehr als eine Firmware-Image-Datei auf die Laufwerke in einem Speicher-Array herunterladen. Die Anzahl der Firmware-Image-Dateien, die Sie herunterladen können, hängt vom Speicher-Array ab. Die Speicherverwaltungssoftware gibt einen Fehler zurück, wenn Sie versuchen, mehr Firmware-Image-Dateien herunterzuladen, als das Speicher-Array akzeptieren kann.

Sie können Downloads für mehrere Laufwerke gleichzeitig planen, einschließlich mehrerer Laufwerke in einer redundanten Volume-Gruppe. Jede Firmware-Image-Datei enthält Informationen über die Laufwerkstypen, auf denen das Firmware-Image ausgeführt wird. Die angegebenen Firmware-Images können nur auf ein kompatibles Laufwerk heruntergeladen werden. Verwenden Sie die `download drive firmware` Befehl zum Herunterladen eines Firmware-Images auf ein bestimmtes Laufwerk.

Der `download storageArray driveFirmware` Der Befehl blockiert alle I/O-Aktivitäten, bis entweder der Download-Versuch für jedes Bewerberlaufwerk durchgeführt oder Sie ausgeführt werden `stop storageArray downloadDriveFirmware` Befehl. Wenn der `download storageArray driveFirmware` Befehl beendet das Herunterladen des Firmware-Images, jedes Kandidatenlaufwerk zeigt den Download-Status für jedes Laufwerk an. Einer dieser Status wird zurückgegeben:

* Erfolgreich
* Nicht Erfolgreich Mit Grund
* Nie Mit Vernunft Versucht




== Minimale Firmware-Stufe

5.20
