---
permalink: commands-a-z/download-storagearray-firmware.html 
sidebar: sidebar 
keywords: download, storage, array, firmware, command, downloads, optionally, values, controllers, role, context, parameter 
summary: Mit dem Befehl storageArray Firmware herunterladen werden Firmware und optional NVSRAM-Werte für den Storage Array Controller heruntergeladen. 
---
= Laden Sie die Speicher-Array-Firmware/NVSRAM herunter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `download storageArray firmware` Mit Befehl werden die Firmware- und optional NVSRAM-Werte für den Storage Array Controller heruntergeladen.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Kontext

Wenn Sie nur NVSRAM-Werte herunterladen möchten, verwenden Sie die `downLoad storageArray NVSRAM` Befehl.



== Syntax

[source, cli, subs="+macros"]
----
download storageArray firmware [, NVSRAM ]
pass:quotes[file="_filename_" [, "_NVSRAM-filename_"]]
[downgrade=(TRUE | FALSE)
activateNow=(TRUE | FALSE)
healthCheckMelOverride=(TRUE | FALSE)
healthCheckNeedsAttnOverride=(TRUE | FALSE)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`NVSRAM`
 a| 
Dieser Parameter lädt beim Herunterladen einer Firmware-Datei eine Datei mit NVSRAM-Werten herunter. Fügen Sie bei diesem Parameter keine eckigen Klammern ein. Fügen Sie ein Komma nach dem ein `firmware` Parameter.



 a| 
`file`
 a| 
Dieser Parameter gibt den Dateipfad und den Dateinamen an, der die Firmware enthält. Schließen Sie den Dateipfad und den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\dnld\safrm.dlp"`

Gültige Dateinamen haben ein `.dlp` Erweiterung.



 a| 
`NVSRAM-filename`
 a| 
Dieser Parameter gibt den Dateipfad und den Dateinamen an, der die NVSRAM-Werte enthält. Schließen Sie den Namen der NVSRAM-Datei in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\dnld\safrm.dlp"` Gültige Dateinamen haben ein `.dlp` Erweiterung.

Fügen Sie beim Herunterladen von Firmware und NVSRAM ein Komma vor dem Dateinamen ein.



 a| 
`downgrade`
 a| 
[CAUTION]
====
*Mögliche Schäden an der Speicher-Array-Konfiguration* -- das Herunterladen einer früheren Version der Controller-Firmware oder NVSRAM falsch kann zu Schäden an den Controllern oder zu einem Verlust des Datenzugriffs führen. Wenden Sie sich vor Verwendung dieses Parameters an den technischen Support.

====
Mit dieser Einstellung kann eine frühere Firmware-Version geladen werden. Der Standardwert ist `FALSE`. Stellen Sie die ein `downgrade` Parameter an `TRUE` Wenn Sie eine frühere Firmware-Version herunterladen möchten.

[NOTE]
====
Dieser Parameter ist nicht gültig, wenn Sie nur NVSRAM herunterladen.

====


 a| 
`activateNow`
 a| 
Mit dieser Einstellung werden das Firmware-Image und das NVSRAM-Image aktiviert. Der Standardwert ist `TRUE`. Wenn Sie die einstellen `activateNow` Parameter an `FALSE`, Sie müssen die ausführen `activate storageArray firmware` Befehl zum Aktivieren der Firmware und des NVSRAM zu einem späteren Zeitpunkt.

[NOTE]
====
Dieser Parameter ist nicht gültig, wenn Sie nur NVSRAM heruntergeladen haben.

====


 a| 
`healthCheckMelOverride`
 a| 
Diese Einstellung überschreibt die Ergebnisse der Integritätsprüfung des Major Event Logs (MEL). DIE MEL-Validierung erfolgt weiterhin; sie wird nicht umgangen. Wenn die MEL-Prüfung fehlschlägt, können Sie den Fehler umgehen, indem Sie diesen Parameter verwenden, wenn Sie den Befehl ausführen.

Vor einem Download prüft der Controller das Ereignisprotokoll, um festzustellen, ob ein Ereignis eingetreten ist, das einen erfolgreichen Download der neuen Controller-Firmware verhindert. Wenn ein solches Ereignis aufgetreten ist, lädt der Controller normalerweise keine neue Firmware herunter.

Mit diesem Parameter wird der Controller zum Herunterladen der neuen Firmware gezwungen. Der Standardwert ist `FALSE`. Setzen Sie diesen Wert auf `TRUE` Wenn Sie den Controller zum Herunterladen einer neuen Controller-Firmware zwingen möchten.



 a| 
`healthCheckNeedsAttnOverride`
 a| 
Mit dieser Einstellung werden die Ergebnisse der Integritätsprüfung im Zusammenhang mit bestimmten Aufmerksamkeitsbedingungen für Anforderungen überschrieben. Erfordert eine Überprüfung der Aufmerksamkeit für eine bestimmte Gruppe von Bedingungen tritt noch auf; sie wird nicht umgangen. Wenn die Prüfung für die Achtung fehlschlägt, können Sie den Fehler mithilfe dieses Parameters umgehen, wenn Sie den Befehl ausführen.

Vor einem Download prüft der Controller bestimmte Aufmerksamkeitsbedingungen, um festzustellen, ob ein Fehler aufgetreten ist, der möglicherweise das erfolgreiche Herunterladen der neuen Controller-Firmware verhindert. Wenn ein solches Ereignis aufgetreten ist, lädt der Controller normalerweise keine neue Firmware herunter.

Mit diesem Parameter wird der Controller zum Herunterladen der neuen Firmware gezwungen. Der Standardwert ist `FALSE`. Setzen Sie diesen Wert auf `TRUE` Wenn Sie den Controller zum Herunterladen einer neuen Controller-Firmware zwingen möchten.

|===


== Minimale Firmware-Stufe

5.00

8.10 fügt die hinzu `*healthCheckMelOverride*` Parameter.

8.70 fügt hinzu `*healthCheckNeedsAttnOverride*` Parameter.
