---
permalink: commands-a-z/download-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: download, storage, array, management, key, certificate, command, intall, external, support, role 
summary: Der Befehl herunterlad storageArray keyManagementCertificate installiert die Zertifikate für das externe Verschlüsselungsmanagement auf dem Speicher-Array. 
---
= Installieren Sie das externe Schlüsselverwaltungszertifikat des Speicherarrays – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `download storageArray keyManagementCertificate` Befehl installiert die Zertifikate für das externe Verschlüsselungsmanagement auf dem Speicher-Array.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[download storageArray keyManagementClientCertificate certificateType=(client|server) file="_filename_" [privateKeyFile = "keyFileName"]]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`certificateType`
 a| 
Ermöglicht die Angabe des Zertifikatdatentyps. Gültige Auswahlmöglichkeiten sind `client` Oder `server`.



 a| 
`file`
 a| 
Ermöglicht die Angabe des vom Client signierten Zertifikats oder des Server Root-/Intermediate-CA-Zertifikats. Die Datei muss im PEM/DER-Format vorliegen.



 a| 
`privateKeyFile`
 a| 
Ermöglicht das Herunterladen eines privaten Schlüssels neben einem signierten Zertifikat. Der `privateKeyFile` Parameter muss mit dem Wert verwendet werden `certificateType=client`.

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "download storageArray keyManagementClientCertificate certificateType=client
   file="C:\serverSignedKeyMgmtClientCert.cer";"


SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
