---
permalink: commands-a-z/enable-controller-datatransfer.html 
sidebar: sidebar 
keywords: enable, controller, datatransfer, command, revive, quiesced, running, diagnostics, role, syntax, parameter, firmware level 
summary: Mit dem Befehl „Controller dataTransfer aktivieren“ wird ein Controller wiederbelebt, der während der Ausführung der Diagnose stillgelegt wurde. 
---
= Controller-Datentransfer aktivieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `enable controller dataTransfer` Befehl gibt einen Controller wieder, der während der Ausführung der Diagnose stillgelegt wurde.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli]
----
enable controller [(a|b)] dataTransfer
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`controller`
 a| 
Der Controller, den Sie beleben möchten. Gültige Controller-IDs sind `a` Oder `b`, Wo `a` Ist der Controller in Steckplatz A, und `b` Ist der Controller in Steckplatz B. Schließen Sie die Controller-Kennung in eckige Klammern ([ ]). Wenn Sie keinen Controller angeben, gibt die Storage-Managementsoftware einen Syntaxfehler aus.

|===


== Minimale Firmware-Stufe

6.10
