---
permalink: commands-a-z/enable-diskpool-security.html 
sidebar: sidebar 
keywords: enable, diskpool, security, command, convert, non secure, diskpool, support, arrays, role, context 
summary: Mit dem Sicherheitsbefehl Enable diskPool wird ein nicht sicherer Laufwerk-Pool in einen sicheren Laufwerk-Pool umgewandelt. 
---
= Datenträgerpool-Sicherheit aktivieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `enable diskPool security` Befehl konvertiert einen nicht sicheren Laufwerk-Pool in einen sicheren Laufwerk-Pool.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Alle Laufwerke aus dem Laufwerk-Pool müssen sicher sein.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[enable diskPool [_diskPoolName_]] security
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`diskPool`
 a| 
Der Name des Laufwerk-Pools, den Sie in den Status Security Enabled setzen möchten. Schließen Sie die Disk-Pool-Kennung in eckige Klammern ([ ]).

|===


[[notes]]
== Hinweise

Jeder Disk Pool-Name muss eindeutig sein. Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Benutzerbezeichnung verwenden. Benutzeretiketten können maximal 30 Zeichen lang sein.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.83
