---
permalink: commands-a-z/enable-volumegroup-security.html 
sidebar: sidebar 
keywords: enable, volumegroup, security, command, non secure, volume, group 
summary: Mit dem Sicherheitsbefehl Enable VolumeGroup wird eine nicht sichere Volume-Gruppe in eine sichere Volume-Gruppe konvertiert. 
---
= Volumegruppensicherheit aktivieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `enable volumeGroup security` Befehl konvertiert eine nicht sichere Volume-Gruppe in eine sichere Volume-Gruppe.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[enable volumeGroup [_volumeGroupName_]] security
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die Sie in den Status „Security Enabled“ einfügen möchten. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


== Hinweise

Diese Bedingungen müssen erfüllt sein, damit dieser Befehl erfolgreich ausgeführt wird.

* Bei allen Laufwerken in der Volume-Gruppe müssen es sich um Laufwerke mit vollständiger Festplattenverschlüsselung befinden.
* Die Laufwerkssicherheitsfunktion muss aktiviert sein.
* Der Sicherheitsschlüssel für das Speicher-Array muss festgelegt werden.
* Die Volume-Gruppe ist optimal und verfügt nicht über Repository-Volumes.


Durch die Controller-Firmware wird eine Sperre erstellt, durch die der Zugriff auf FDE-Laufwerke eingeschränkt wird. FDE-Laufwerke weisen einen Zustand auf, der als „Security-fähig“ bezeichnet wird. Wenn Sie einen Sicherheitsschlüssel erstellen, wird der Status auf „aktiviert“ gesetzt, was den Zugriff auf alle im Speicher-Array vorhandenen FDE-Laufwerke einschränkt.



== Minimale Firmware-Stufe

7.40
