---
permalink: commands-a-z/getting-started-with-authentication.html 
sidebar: sidebar 
keywords: authentication, users, access, system, assign, login credentials, associated, profile, include, specific, role, access, permissions, start 
summary: Zur Authentifizierung müssen Benutzer mit zugewiesenen Anmeldedaten auf das System zugreifen. Jede Benutzeranmeldung ist einem Benutzerprofil zugeordnet, das bestimmte Rollen und Zugriffsberechtigungen enthält. 
---
= Erste Schritte mit der Authentifizierung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zur Authentifizierung müssen Benutzer mit zugewiesenen Anmeldedaten auf das System zugreifen. Jede Benutzeranmeldung ist einem Benutzerprofil zugeordnet, das bestimmte Rollen und Zugriffsberechtigungen enthält.

Administratoren können die Systemauthentifizierung wie folgt implementieren:

* Verwendung von RBAC-Funktionen (rollenbasierte Zugriffssteuerung), die im Storage-Array durchgesetzt werden. Dazu gehören vordefinierte Benutzer und Rollen.
* Verbinden mit einem LDAP-Server und einem Verzeichnisdienst (Lightweight Directory Access Protocol), z. B. dem Active Directory von Microsoft, und Zuordnen der LDAP-Benutzer zu den eingebetteten Rollen des Speicherarrays.
* Verbindung mit einem Identitäts-Provider (IdP) über die Security Assertion Markup Language (SAML) 2.0 herstellen und dann Benutzer den eingebetteten Rollen des Speicherarrays zuordnen.
+
[NOTE]
====
SAML ist eine integrierte Funktion im Storage-Array (Firmware-Ebene 8.42 und höher) und kann nur über die Benutzeroberfläche von SANtricity System Manager konfiguriert werden.

====

