---
permalink: commands-a-z/recreate-storagearray-securitykey.html 
sidebar: sidebar 
keywords: recreate, external, security key 
summary: Der Befehl reproduzieren storageArray securityKey erzeugt einen Storage Array-Sicherheitsschlüssel für die Verwendung mit der externen Sicherheitsschlüsselverwaltungsfunktion. 
---
= Externen Sicherheitsschlüssel neu erstellen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `recreate storageArray securityKey` Der Befehl generiert einen Sicherheitsschlüssel für das Storage-Array erneut, um diesen mit der Funktion für das externe Sicherheitsschlüsselmanagement zu verwenden.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
recreate storageArray securityKey
passPhrase=pass:quotes[_"passPhraseString"_
file="_fileName"_]
[deleteOldKey=(TRUE | FALSE)]
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`passPhrase`
 a| 
Eine Zeichenkette, die den Sicherheitsschlüssel verschlüsselt, sodass Sie den Sicherheitsschlüssel in einer externen Datei speichern können. Schließen Sie den Passphrase in doppelte Anführungszeichen (" ").



 a| 
`file`
 a| 
Der Dateipfad und der Dateiname mit dem Sicherheitsschlüssel. Beispiel:

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
Der Dateiname muss über eine Erweiterung von verfügen `.slk`.

====


 a| 
`deleteOldKey`
 a| 
Setzen Sie diesen Parameter auf `TRUE` So löschen Sie den alten Sicherheitsschlüssel vom externen Schlüsselverwaltungsserver, nachdem der neue Sicherheitsschlüssel erstellt wurde. Die Standardeinstellung lautet `FALSE`.

|===


[[notes]]
== Hinweise

Ihr Passphrase muss folgende Kriterien erfüllen:

* Die Passphrase muss zwischen acht und 32 Zeichen lang sein.
* Der Passphrase muss mindestens einen Großbuchstaben enthalten.
* Der Passphrase muss mindestens einen Kleinbuchstaben enthalten.
* Der Passphrase muss mindestens eine Zahl enthalten.
* Der Passphrase muss mindestens ein nicht-alphanumerisches Zeichen enthalten, z. B. < > @ +.


[NOTE]
====
Wenn Ihr Passphrase diese Kriterien nicht erfüllt, erhalten Sie eine Fehlermeldung.

====


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.70

11.73 fügt die hinzu `deleteOldKey` Parameter.
