---
permalink: commands-a-z/remove-member-volume-from-consistency-group.html 
sidebar: sidebar 
keywords: remove, member, volume, consistency group 
summary: Mit dem Befehl set Consistency Group wird ein Mitglied-Volume aus einer vorhandenen Snapshot Consistency Group entfernt. 
---
= Mitgliedsvolume aus Konsistenzgruppe entfernen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set consistencyGroup` Mit dem Befehl wird ein Mitglied-Volume aus einer vorhandenen Snapshot Konsistenzgruppe entfernt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Kontext

Optional können Sie die Mitglieder des Repository-Volumes aus der Konsistenzgruppe löschen.



== Syntax

[source, cli, subs="+macros"]
----
set consistencyGroup pass:quotes[[_"consistencyGroupName"_]]
removeCGMemberVolume=pass:quotes["_memberVolumeName_"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`consistencyGroupName`
 a| 
Der Name der Konsistenzgruppe, aus der Sie ein Mitglied entfernen möchten. Schließen Sie den Namen der Konsistenzgruppe in doppelte Anführungszeichen („ ") in eckigen Klammern ([ ]) ein.



 a| 
`removeCGMemberVolume`
 a| 
Der Name des Mitgliedvolumes, das Sie entfernen möchten. Schließen Sie den Namen der Mitgliedsgruppe in doppelte Anführungszeichen (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Legt fest, ob alle Repository-Mitglieder aus der Konsistenzgruppe entfernt werden sollen.

|===


== Minimale Firmware-Stufe

7.83
