---
permalink: commands-a-z/remove-storagearray-directoryserver.html 
sidebar: sidebar 
keywords: remove, storage array, directory, server, role, mapping 
summary: Mit dem Befehl storageArray directoryServer entfernen werden die definierten Rollenzuordnungen für den angegebenen Verzeichnisserver entfernt. 
---
= Rollenzuordnung des Speicherarray-Verzeichnisservers entfernen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `remove storageArray directoryServer` Mit dem Befehl werden die definierten Rollenzuordnungen für den angegebenen Verzeichnisserver entfernt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
remove storageArray directoryServer pass:quotes[[_domainId_]]
    (allGroupDNs | groupDNs=pass:quotes[(_groupDN1 ... groupDNN_))]
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`directoryServer`
 a| 
Hier können Sie die Domäne mithilfe der Domänen-ID angeben, für die die Zuordnung entfernt werden soll.



 a| 
`allGroupDNs`
 a| 
Ermöglicht es Ihnen, alle Gruppen Distinguished Name Mappings aus der Domäne zu entfernen.



 a| 
`groupDNs`
 a| 
Ermöglicht Ihnen, die zu entfernenden Gruppen`' Distinguished Name (DN) anzugeben.

[NOTE]
====
Wenn Sie mehrere Gruppen eingeben, trennen Sie die Werte mit einem Leerzeichen.

====
|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "remove storageArray directoryServer ["domain1"]
                    groupDNs=("CN=company-distlist,OU=Managed,
                    OU=MyCompanyGroups,DC=hq,DC=mycompany,DC=com");"

SMcli -n Array1 -c "remove storageArray directoryServer ["domain1"]
                    allGroupDNs;"

SMcli completed successfully.
----