---
permalink: commands-a-z/remove-member-volume-from-consistency-group.html 
sidebar: sidebar 
keywords: remove, member, volume, consistency group 
summary: Mit dem Befehl set Consistency Group wird ein Mitglied-Volume aus einer vorhandenen Snapshot Consistency Group entfernt. 
---
= Entfernen Sie das Mitglied-Volume aus der Konsistenzgruppe
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set consistencyGroup` Mit dem Befehl wird ein Mitglied-Volume aus einer vorhandenen Snapshot Konsistenzgruppe entfernt.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

Optional können Sie die Mitglieder des Repository-Volumes aus der Konsistenzgruppe löschen.



== Syntax

[listing, subs="+macros"]
----
set consistencyGroup pass:quotes[[_"consistencyGroupName"_]]
removeCGMemberVolume=pass:quotes["_memberVolumeName_"]
[deleteRepositoryMembers=(TRUE | FALSE)]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`consistencyGroupName`
 a| 
Der Name der Konsistenzgruppe, aus der Sie ein Mitglied entfernen möchten. Schließen Sie den Namen der Konsistenzgruppe in doppelte Anführungszeichen („ ") in eckigen Klammern ([ ]) ein.



 a| 
`removeCGMemberVolume`
 a| 
Der Name des Mitgliedvolumes, das Sie entfernen möchten. Schließen Sie den Namen der Mitgliedsgruppe in doppelte Anführungszeichen (" ").



 a| 
`deleteRepositoryMembers`
 a| 
Legt fest, ob alle Repository-Mitglieder aus der Konsistenzgruppe entfernt werden sollen.

|===


== Minimale Firmware-Stufe

7.83
