---
permalink: commands-a-z/repair-volume-parity.html 
sidebar: sidebar 
keywords: repair, volume, parity 
summary: Der Parity-Befehl zum Reparieren des Volume repariert die Paritätsfehler auf einem Volume. 
---
= Volumeparität reparieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `repair volume parity` Befehl repariert die Paritätsfehler auf einem Volume.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

[CAUTION]
====
Wenn Volume-Paritäts- und Volume-Daten nicht übereinstimmen, sind Volume-Daten unter Umständen fehlerhaft – nicht die Paritäts-Volume. Das Reparieren der Volume-Parität zerstört falls erforderlich die Möglichkeit zur Reparatur defekter Volume-Daten.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
repair volume pass:quotes[[_volumeName_]] parity
parityErrorFile=pass:quotes[_"filename"_]
[verbose=(TRUE | FALSE)]
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`volume`
 a| 
Der Name des Datenträgers, für das Sie Parität reparieren. Umschließen Sie den Volumennamen in eckige Klammern ([ ]). Wenn der Volume-Name Sonderzeichen oder Ziffern hat, müssen Sie den Volume-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`parityErrorFile`
 a| 
Der Dateipfad und der Dateiname, der die Paritätsinformationen enthält, die Sie zum Reparieren der Fehler verwenden. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\sup\parfile.txt"`

[NOTE]
====
A `parityErrorFile` Ist das Ergebnis eines vorherigen `check volume parity` Betrieb.

====


 a| 
`verbose`
 a| 
Die Einstellung zum Erfassen von Fortschrittsdetails, z. B. „Fertigstellungsgrad“, und zum Anzeigen der Informationen, während die Volume-Parität repariert wird. Um Fortschrittsdetails zu erfassen, setzen Sie diesen Parameter auf `TRUE`. Um die Erfassung von Fortschrittsdetails zu verhindern, setzen Sie diesen Parameter auf `FALSE`.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
