---
permalink: commands-a-z/replace-drive-replacementdrive.html 
sidebar: sidebar 
keywords: replace, drive 
summary: Mit dem Befehl Ersatzlaufwerk ersetzen wird ein Laufwerk in einer Laufwerksgruppe ersetzt. 
---
= Laufwerk austauschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `replace drive replacementDrive` Befehl ersetzt ein Laufwerk in einer Volume-Gruppe.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Durch das Ersetzen eines Laufwerks in einer Volume-Gruppe wird die Zusammensetzung einer Volume-Gruppe neu definiert. Mit diesem Befehl können Sie ein Laufwerk durch ein nicht zugewiesenes Laufwerk oder ein vollständig integriertes Hot Spare ersetzen.



== Syntax

[source, cli]
----
replace (drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\]
 | <"wwID">)
replacementDrive=trayID,drawerID,slotID
[copyDrive][failDrive]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`drive`
 a| 
Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`.

Alle maximale Steckplatz-ID sind 24. Die Steckplatz-ID-Werte beginnen je nach Fachmodell bei 0 oder 1. Die Laufwerksfächer sind mit E2800 und E5700 Controllern kompatibel und besitzen die Steckplatz-ID-Nummern ab 0. Die Laufwerksfächer sind mit E2700 und E5600 Controllern kompatibel und verfügen ab 1 über die Steckplatz-ID.

Schließen Sie den Wert für Fach-ID, die Fach-ID und den Wert für die Steckplatz-ID in eckigen Klammern ([ ]) an.



 a| 
`drive`
 a| 
Der World Wide Identifier (WWID) des Laufwerks, das ersetzt werden soll. Schließen Sie die WWID in doppelte Anführungszeichen (" ") innerhalb der Winkel Klammern (< >).



 a| 
`replacementDrive`
 a| 
Der Speicherort des Laufwerks, den Sie für einen Austausch verwenden möchten. Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`. Die Steckplatz-ID-Werte sind `1` Bis `24`.

|===


== Hinweise

Der `drive` Der Parameter unterstützt sowohl Laufwerksfächer mit hoher Kapazität als auch Laufwerksfächer mit geringer Kapazität. Ein Laufwerksfach mit hoher Kapazität verfügt über Schubladen, die die Laufwerke halten. Die Schubladen ziehen aus dem Laufwerksfach, um Zugriff auf die Laufwerke zu ermöglichen. Ein Laufwerksfach mit geringer Kapazität verfügt nicht über Schubladen. Bei einem Laufwerksfach mit hoher Kapazität müssen Sie die Kennung (ID) des Laufwerksfachs, die ID des Fachs und die ID des Steckplatzes, in dem sich ein Laufwerk befindet, angeben. Bei einem Laufwerksfach mit niedriger Kapazität müssen Sie nur die ID des Laufwerksfachs und die ID des Steckplatzes angeben, in dem sich ein Laufwerk befindet. Bei einem Laufwerksfach mit geringer Kapazität kann die ID des Laufwerksfachs auf festgelegt werden, um einen Speicherort für ein Laufwerk zu ermitteln `0`, Und geben Sie die ID des Steckplatzes an, in dem sich ein Laufwerk befindet.



== Minimale Firmware-Stufe

7.10

7.60 fügt die hinzu `_drawerID_` Benutzereingaben.
