---
permalink: commands-a-z/reset-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: reset, installed, signed, certificate 
summary: Der Befehl Reset Controller arrayManagementSignedCertificate setzt das installierte unterzeichnete Zertifikat und die Root/Intermediate Zertifikate auf dem Controller zurück. Alle Root- und Zwischenzertifikate sowie alle signierten Zertifikate werden durch ein einziges selbstsigniertes Zertifikat ersetzt. 
---
= Installiertes signiertes Zertifikat zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset controller arrayManagementSignedCertificate` Mit dem Befehl werden das installierte signierte Zertifikat und die Root-/Zwischenzertifikate auf dem Controller zurückgesetzt. Alle Root- und Zwischenzertifikate sowie alle signierten Zertifikate werden durch ein einziges selbstsigniertes Zertifikat ersetzt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli]
----
reset controller [(a|b)] arrayManagementSignedCertificate
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`controller`
 a| 
Ermöglicht dem Benutzer, den Controller anzugeben, auf dem Sie die Root-/Zwischenzertifikate abrufen möchten. Gültige Controller-IDs sind A oder b, wobei A der Controller in Steckplatz A ist und b der Controller in Steckplatz B ist Schließen Sie die Controller-Kennung in eckige Klammern ([ ]).

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "reset controller [a] arrayManagementSignedCertificate;"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
