---
permalink: commands-a-z/reset-storagearray-socbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, soc, baseline 
summary: 'Der Befehl Reset storageArray SOCBaseline setzt die Baseline für alle SOC-Geräte (Switch-on-a-Chip) zurück, auf die über die Controller zugegriffen wird.' 
---
= Zurücksetzen der SOC-Baseline des Speicherarrays
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray SOCBaseline` Befehl setzt die Baseline für alle SOC-Geräte (Switch-on-a-Chip) zurück, auf die über die Controller zugegriffen wird.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Mit diesem Befehl wird die Baseline zurückgesetzt, indem alle SOC-Werte auf 0 gesetzt werden. Dieser Befehl gilt nur für Fibre Channel-Geräte in einer Arbitrated Loop-Topologie.



== Syntax

[source, cli]
----
reset storageArray SOCBaseline
----


== Parameter

Keine.



== Minimale Firmware-Stufe

6.16
