---
permalink: commands-a-z/reset-storagearray-volumedistribution.html 
sidebar: sidebar 
keywords: reset, storage array, volume, distribution 
summary: 'Der Befehl „Reset storageArray VolumeDistribution“ weist alle Volumes dem bevorzugten Controller neu zu (verschiebt).' 
---
= Speicherarray-Volumeverteilung zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray volumeDistribution` Befehl weist alle Volumes dem bevorzugten Controller neu zu (verschiebt).



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli]
----
reset storageArray volumeDistribution
----


[[parameters]]
== Parameter

Keine.



[[notes]]
== Hinweise

Wenn Sie diesen Befehl auf einem Host ohne Multi-Path-Treiber verwenden, müssen Sie I/O-Vorgänge für die Volumes anhalten, bis dieser Befehl ausgeführt wurde, um Anwendungsfehler zu vermeiden.

In bestimmten Host-Betriebssystemumgebungen muss der Multipath-Hosttreiber möglicherweise neu konfiguriert werden. Möglicherweise müssen Sie auch Änderungen am Betriebssystem vornehmen, um den neuen I/O-Pfad zu den Volumes zu erkennen.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

5.20
