---
permalink: commands-a-z/reset-storagearray-diagnosticdata.html 
sidebar: sidebar 
keywords: reset ,storage, array, diagnostic, data 
summary: Mit dem Befehl „Reset storageArray DiagnosticData“ wird der NVSRAM zurückgesetzt, der die Diagnosedaten für das Speicher-Array enthält. 
---
= Diagnosedaten des Speicherarrays zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray diagnosticData` Mit dem Befehl wird der NVSRAM zurückgesetzt, der die Diagnosedaten für das Speicher-Array enthält.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Durch diesen Befehl werden die Diagnosedaten nicht gelöscht. Mit diesem Befehl wird der Status „Aufmerksamkeit erforderlich“ durch den Status „Verfügbare Diagnosedaten“ ersetzt. Die alten Diagnosedaten werden automatisch überschrieben, sobald neue Daten erfasst werden. Auch der Speicher mit den Diagnosedaten wird gelöscht, wenn die Controller neu gebootet werden. Verwenden Sie vor dem Zurücksetzen der Diagnosedaten den `save storageArray diagnosticData` Befehl zum Speichern der Diagnosedaten in einer Datei.

[NOTE]
====
Führen Sie diesen Befehl nur mit Unterstützung des technischen Supports aus.

====


== Syntax

[source, cli]
----
reset storageArray diagnosticData
----


== Parameter

Keine.



== Minimale Firmware-Stufe

6.16
