---
permalink: commands-a-z/reset-storagearray-sasphybaseline.html 
sidebar: sidebar 
keywords: reset, storage array, sas, phy, baseline 
summary: 'Mit dem Befehl storageArray SASPHYBaseline zurücksetzen wird die SAS Physical Layer (SAS PHY) Baseline für alle Geräte zurückgesetzt und die Fehlerliste wird aus der .csv-Datei entfernt.' 
---
= SAS-PHY-Basislinie des Speicherarrays zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray SASPHYBaseline` Mit dem Befehl wird die Basislinie der SAS-physikalischen Schicht (SAS PHY) für alle Geräte zurückgesetzt und die Fehlerliste wird aus dem entfernt `.csv` Datei:



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Der `.csv` Die Datei wird erzeugt, wenn Sie den ausführen `save storageArray SASPHYCounts` Befehl.

[NOTE]
====
Der vorherigen Version des `reset storageArray SASPHYBaseline` Befehl gelöscht Fehleranzahl für alle Geräte außer den Laufwerken. Der `reset storageArray SASPHYBaseline` Mit dem Befehl werden jetzt die SAS-PHY-Basis für die Laufwerke sowie die anderen Geräte zurückgesetzt. Alle Fehler werden aus dem gelöscht `.csv` Datei:

====


[[syntax]]
== Syntax

[source, cli]
----
reset storageArray SASPHYBaseline
----


[[parameters]]
== Parameter

Keine.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10

7.83 setzt die SAS-PHY-Basislinie für Laufwerke zurück.
