---
permalink: commands-a-z/reset-storagearray-hostportstatisticsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, host, port, statistics, baseline 
summary: Mit dem Befehl „Reset storageArray hostPortStatisticsBaseline“ wird die Basislinie für die Statistiken des Speicherarrays für den Host-Port zurückgesetzt. 
---
= Basislinie der Host-Port-Statistiken des Speicherarrays zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray hostPortStatisticsBaseline` Der Befehl setzt die Basisdaten für den Host-Port des Speicherarrays zurück.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.



[[context]]
== Kontext

[NOTE]
====
Mit diesem Befehl wird die veraltete Version ersetzt xref:reset-storagearray-ibstatsbaseline.adoc[Zurücksetzen der Baseline-InfiniBand-Statistiken für das Speicher-Array], xref:reset-storagearray-iscsistatsbaseline.adoc[ISCSI-Basisplan für Speicher-Array zurücksetzen], und xref:reset-storagearray-iserstatsbaseline.adoc[Zurücksetzen des Speicher-Array iSER-Basisplans] Befehle.

====


[[syntax]]
== Syntax

[source, cli]
----

reset storageArray hostPortStatisticsBaseline type=(ISCSI| ISER | SRP | NVMEOF)
----


[[parameters]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`type`
 a| 
Hiermit können Sie angeben, welcher Statistiktyp gesammelt werden soll. Gültige Auswahlmöglichkeiten: `ISCSI`, `ISER`, `SRP`, und `NVMEOF`.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.41
