---
permalink: commands-a-z/reset-storagearray-iscsistatsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, iscsi, baseline 
summary: Mit dem Befehl „Reset storageArray iscsiStatsBaseline“ wird die iSCSI-Baseline für das Speicher-Array auf 0 zurückgesetzt. 
---
= iSCSI-Basislinie des Speicherarrays zurücksetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `reset storageArray iscsiStatsBaseline` Der Befehl setzt die iSCSI-Baseline für das Speicher-Array auf 0 zurück.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E4000, E2700, E5600, E2800 und E5700 Arrays, sofern alle SMcli-Pakete installiert sind.



== Rollen

Sie müssen über die Rolle Storage-Administrator verfügen, um diesen Befehl für ein E4000, E2800 oder E5700 Storage-Array auszuführen.

[NOTE]
====
Dieser Befehl ist veraltet und wird von ersetzt xref:reset-storagearray-hostportstatisticsbaseline.adoc[Zurücksetzen der Baseline-Statistiken für den Host-Port des Speicher-Arrays] Befehl.

====


== Syntax

[source, cli]
----
reset storageArray iscsiStatsBaseline
----


== Parameter

Keine.



== Hinweise

Mit diesem Befehl wird die Baseline für beide Controller im Speicher-Array auf 0 zurückgesetzt. Der Zweck des Rücksetzens beider Controller-Baselines besteht darin, sicherzustellen, dass die Anzahl der Controller zwischen den Controllern synchronisiert wird. Wenn ein Controller zurückgesetzt wird, aber der zweite Controller nicht zurückgesetzt wird, wird dem Host mitgeteilt, dass die Controller nicht synchronisiert sind. Der Gastgeber wird über die Zeitstempel informiert, die mit der Statistik gemeldet werden.



== Minimale Firmware-Stufe

7.10

8.41 dieser Befehl ist veraltet.
