---
permalink: commands-a-z/resume-ssdcache.html 
sidebar: sidebar 
keywords: resume, ssd, cache 
summary: Mit dem Befehl „ssdCache fortsetzen“ wird das Caching für alle Volumes mit dem SSD-Cache neu gestartet, der mit dem Befehl „ssdCache suspendieren“ vorübergehend angehalten wurde. 
---
= SSD-Cache fortsetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `resume ssdCache` Mit dem Befehl wird das Caching für alle Volumes neu gestartet, die den SSD-Cache verwenden, der vorübergehend mit dem angehalten wurde `suspend ssdCache` Befehl.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Support Admin verfügen.



== Syntax

[source, cli, subs="+macros"]
----
resume ssdCache pass:quotes[[_ssdCacheName_]]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, für den Sie Cache-Vorgänge fortsetzen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen hat oder nur aus Zahlen besteht, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
