---
permalink: commands-a-z/resume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: resume, asynchronous, mirror, group 
summary: Mit dem Befehl „Async MirrorGroup“ wird die Datenübertragung zwischen allen gespiegelten Paaren in einer asynchronen Spiegelgruppe fortgesetzt. 
---
= Setzen Sie die asynchrone Spiegelgruppe fort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `resume asyncMirrorGroup` Mit dem Befehl wird die Datenübertragung zwischen allen gespiegelten Paaren in einer asynchronen Spiegelgruppe fortgesetzt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Daten, die während der Aussetzung der asynchronen Spiegelgruppe auf die primären Volumes geschrieben wurden, werden sofort auf die sekundären Volumes geschrieben. Die regelmäßige Synchronisierung wird fortgesetzt, wenn ein Intervall für die automatische Synchronisierung festgelegt wurde.



== Syntax

[source, cli, subs="+macros"]
----
resume asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
[deleteRecoveryPointIfNecessary]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`asyncMirrorGroup`
 a| 
Der Name der asynchronen Spiegelgruppe, für die die Synchronisierung gestartet werden soll. Schließen Sie den Namen der asynchronen Spiegelgruppe in doppelte Anführungszeichen (" ") in eckigen Klammern ([ ]").



 a| 
`deleteRecoveryPointIfNecessary`
 a| 
Der Parameter zum Löschen des Wiederherstellungspunkts, wenn die wiederherstellbaren Synchronisierungsdaten den Zeitschwellenwert für die Wiederherstellung überschritten haben. Der Zeitpunkt der Wiederherstellung wird aus dem Zeitpunkt gemessen, zu dem die Daten im primären Storage Array eingefroren wurden.

|===


== Minimale Firmware-Stufe

7.84

8.10 fügt die hinzu `deleteRecoveryPointIfNecessary` Parameter

11.80 bietet Unterstützung für EF600 und EF300 Arrays
