---
permalink: commands-a-z/resume-snapvolume.html 
sidebar: sidebar 
keywords: resume, snapshot, volume 
summary: Der Befehl snapVolume fortsetzen setzt einen Snapshot Volume-Vorgang fort, der angehalten wurde. 
---
= Snapshot-Volume fortsetzen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `resume snapVolume` Mit dem Befehl wird ein Snapshot Volume-Vorgang fortgesetzt, der angehalten wurde.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
resume snapVolume pass:quotes[[_"snapVolumeName"_]] snapImage=pass:quotes[_"snapCGID:imageID"_]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`snapVolume`
 a| 
Der Name des Snapshot-Volumes, für das Sie den Betrieb fortsetzen möchten. Schließen Sie den Namen des Snapshot-Volumes in doppelte Anführungszeichen (" ") in eckigen Klammern ([ ]) ein.



 a| 
`snapImage`
 a| 
Der Name des Snapshot-Images, für das die Vorgänge des Snapshot-Volumes fortgesetzt werden sollen. Der Name eines Snapshot-Images besteht aus zwei Teilen:

* Der Name der Snapshot-Gruppe
* Eine Kennung für das Snapshot-Image in der Snapshot-Gruppe


Die Kennung für das Snapshot-Image kann eine der folgenden sein:

* Ein Integer-Wert, der die Sequenznummer des Snapshots in der Snapshot-Gruppe ist.
* `NEWEST` - Verwenden Sie diese Option, wenn Sie das neueste Snapshot-Image anzeigen möchten, das in der Snapshot-Gruppe erstellt wurde.
* `OLDEST` - Verwenden Sie diese Option, wenn Sie das früheste Snapshot-Image anzeigen möchten, das in der Snapshot-Gruppe erstellt wurde.


Schließen Sie den Namen des Snapshot-Bildes in doppelte Anführungszeichen (" ").

|===


== Hinweise

Der Name eines Snapshot-Bildes hat zwei Teile, die durch einen Doppelpunkt (:) getrennt sind:

* Die Kennung der Snapshot-Gruppe
* Die Kennung des Snapshot-Images


Wenn Sie beispielsweise die Vorgänge des Snapshot-Volumes für das Snapshot-Image 12345 in einer Snapshot-Gruppe mit dem Namen SnapGroup1 fortsetzen möchten, würden Sie diesen Befehl verwenden:

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:12345";
----
Um die Vorgänge des Snapshot-Volumes für das aktuellste Snapshot-Image in einer Snapshot-Gruppe mit dem Namen SnapGroup1 fortzusetzen, verwenden Sie diesen Befehl:

[listing]
----
resume snapVolume ["snapVol1"] snapImage="snapGroup1:newest";
----


== Minimale Firmware-Stufe

7.83
