---
permalink: commands-a-z/revive-volumegroup.html 
sidebar: sidebar 
keywords: revive, volume, group 
summary: Der Befehl „VolumeGroup neu beleben“ zwingt die angegebene Volume-Gruppe und die zugehörigen ausgefallenen Laufwerke auf den optimalen Zustand. 
---
= Volume-Gruppe wiederbeleben – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `revive volumeGroup` Der Befehl erzwingt die angegebene Volume-Gruppe und die zugehörigen ausgefallenen Laufwerke zum optimalen Status.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Speichersystem auszuführen, müssen Sie die Rolle Storage Admin oder Support Admin haben.



[[context]]
== Kontext

[NOTE]
====
*Möglicher Verlust des Datenzugriffs* -- die korrekte Verwendung dieses Befehls hängt von der Datenkonfiguration auf allen Laufwerken in der Volume-Gruppe ab. Versuchen Sie niemals, ein Laufwerk wiederzubeleben, es sei denn, Sie werden durch technischen Support überwacht.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
revive volumeGroup pass:quotes[[_volumeGroupName_]]
----


[[parameter]]
== Parameter

|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die auf den optimalen Status eingestellt werden soll. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
