---
permalink: commands-a-z/revive-snapvolume.html 
sidebar: sidebar 
keywords: revive, snapshot, volume 
summary: Der Befehl Revive SnapVolume erzwingt ein angegebenes Snapshot-Volumen zum optimalen Status. 
---
= Snapshot-Volume wiederbeleben – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `revive snapVolume` Durch den Befehl wird ein angegebenes Snapshot-Volume in den optimalen Zustand versetzt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Kontext

Das Snapshot Volumen kann einer der folgenden sein:

* Ein Standalone-Snapshot-Volume
* Ein Snapshot-Volume, das Mitglied einer Konsistenzgruppe ist


Wenn sich das Snapshot Volume nicht im Fehlerzustand befindet, zeigt die Firmware eine Fehlermeldung an und führt diesen Befehl nicht aus.

[NOTE]
====
Dieser Befehl kann nicht für ein Snapshot-Volume verwendet werden, das in der Online-Volume-Kopie verwendet wird.

====


== Syntax

[source, cli, subs="+macros"]
----
revive snapVolume pass:quotes[[_snapVolumeName_]]
----


== Parameter

|===
| Parameter | Beschreibung 


 a| 
`snapVolume`
 a| 
Der Name des Snapshot-Volumes, das Sie auf den Status „optimal“ setzen möchten. Schließen Sie den Namen des Snapshot-Volumes in eckige Klammern ([ ]). Wenn der Name des Snapshot-Volumes Sonderzeichen hat oder nur aus Zahlen besteht, müssen Sie den Namen des Snapshot-Volumes in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.



== Minimale Firmware-Stufe

7.83
