---
permalink: commands-a-z/save-storagearray-ibstats.html 
sidebar: sidebar 
keywords: save, storage, array, infiniband, statistics 
summary: Mit dem Befehl „Save storageArray ibStats“ werden die InfiniBand-Performancestatistiken des Speicherarrays in einer Datei gespeichert. 
---
= InfiniBand-Statistiken des Speicherarrays speichern – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray ibStats` Mit dem Befehl werden die InfiniBand-Performance-Statistiken des Speicherarrays in einer Datei gespeichert.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.

[NOTE]
====
Dieser Befehl ist veraltet und wird von ersetzt xref:save-storagearray-hostportstatistics.adoc[Speichern Sie die Host-Port-Statistiken des Speicher-Arrays] Befehl.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
save storageArray ibStats [raw | baseline]
file=pass:quotes["_filename_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`raw`
 a| 
Die Statistiken, die erfasst werden, sind alle Statistiken vom Start-of-Day des Controllers. Schließen Sie den Parameter in eckigen Klammern ([ ]).



 a| 
`baseline`
 a| 
Die Statistiken, die erfasst werden, sind sämtliche Statistiken aus dem Zeitpunkt, an dem die Controller mithilfe des auf null zurückgesetzt wurden `reset storageArray ibStatsBaseline` Befehl. Schließen Sie den Parameter in eckigen Klammern ([ ]).



 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in den Sie die Leistungsstatistiken speichern möchten. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\sup\ibstat.csv"`

Der Standardname der Datei, die die InfiniBand-Performance-Statistiken enthält, ist `ib-statistics.csv`. Sie können jeden beliebigen Dateinamen verwenden, aber Sie müssen den verwenden `.csv` Erweiterung.

|===


[[notes]]
== Hinweise

Wenn Sie die InfiniBand-Baseline-Statistiken seit dem Start des Controllers nicht zurückgesetzt haben, ist die Zeit zu Beginn des Tages die Standardbasiszeit.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.32

8.41 dieser Befehl ist veraltet.
