---
permalink: commands-a-z/save-storagearray-dbmvalidatorinfo.html 
sidebar: sidebar 
keywords: save, storage, array, dbm, validator, information, file 
summary: Mit dem Befehl speicherungArray dbmValidatorInfo speichern werden die Validierungsinformationen für ein Speicherarray in einer XML-Datei gespeichert. 
---
= Speichern der DBM-Validator-Informationsdatei des Speicherarrays – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray dbmValidatorInfo` Mit dem Befehl werden die Datenbankmanagement-Validierungsinformationen (DBM) für ein Speicherarray in einer XML-Datei gespeichert.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle „Security Admin“ verfügen.



== Kontext

Der technische Support kann diese XML-Datei verwenden, um eine gültige Zeichenfolge (einen Sicherheitscode) zu generieren. Der Validierer-String muss in enthalten sein `load storageArray dbmDatabase` Befehl beim Wiederherstellen eines Speicher-Arrays zurück in eine bereits vorhandene Konfiguration.



== Syntax

[source, cli, subs="+macros"]
----
save storageArray dbmValidatorInfo file=pass:quotes["_filename_"] dbmDatabase=pass:quotes["_filename_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname des DBM-Validierers, der für den technischen Support erforderlich ist. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Array Backups \DBMvalidator.xml"` Dieser Befehl fügt nicht automatisch eine Dateierweiterung an die gespeicherte Datei an. Sie müssen die Erweiterung .XML angeben, wenn Sie den Dateinamen eingeben.



 a| 
`dbmDatabase`
 a| 
Der Dateipfad und der Dateiname der DBM-Datenbank, aus der Sie die XML-Informationsdatei generieren möchten. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`dbmDatabase="C:\Array Backups \DBMbackup_03302010.dbm"` Dieser Befehl fügt nicht automatisch eine Dateierweiterung an die gespeicherte Datei an. Sie müssen die Erweiterung .dbm angeben, wenn Sie den Dateinamen eingeben.

|===


== Hinweise

Wenn Sie die XML-Informationsdatei generieren, um eine gültige Zeichenfolge zu erhalten, müssen Sie diesen Befehl ausführen, während Sie mit dem Controller verbunden sind, in dem Sie die Datenbank wiederherstellen möchten. Im folgenden Beispiel wird das Format der XML-Datei angezeigt:

[listing]
----
<?xml version="1.0" encoding="utf-8"?>
<DbmImageMetadata>
<Controllers>
<A>1IT0nnnnnnnnnABCD</A>
<B>1T0nnnnnnnnnABCD</B>
</Controllers>
<Header>
<ImageVersion>1</ImageVersion>
<TimeStamp>1269388283</TimeStamp>
</Header>
<Trailer>
<CRC>nnnnnnnnnn</CRC><
/Trailer>
</DbmImageMetadata>
----


== Minimale Firmware-Stufe

7.75
