---
permalink: commands-a-z/save-storagearray-performancestats.html 
sidebar: sidebar 
keywords: save, storage, array, performance, statistics 
summary: Der Befehl „Save storageArray performceStats“ speichert die Leistungsstatistiken in einer Datei. 
---
= Leistungsstatistiken für Speicherarrays speichern – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray performanceStats` Mit dem Befehl werden die Performance-Statistiken in einer Datei gespeichert.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Führen Sie vor Verwendung dieses Befehls das aus `set session performanceMonitorInterval` Befehl und das `set session performanceMonitorIterations` Befehl zum Festlegen, wie oft Statistiken erfasst werden.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
save storageArray performanceStats file=pass:quotes["_filename_"]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in den Sie die Leistungsstatistiken speichern möchten. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\sastat.csv"`

Der Standardname der Datei, die die Performance-Statistiken enthält, ist `performanceStatistics.csv`. Sie können jeden beliebigen Dateinamen verwenden, aber Sie müssen den verwenden `.csv` Erweiterung.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
