---
permalink: commands-a-z/save-alldrives-logfile.html 
sidebar: sidebar 
keywords: save, drive log 
summary: Der Befehl „Logfile speichern“ speichert die Laufwerksprotokolle in einer Datei. 
---
= Laufwerksprotokoll speichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save allDrives logFile` Befehl speichert die Laufwerksprotokolle in einer Datei.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Die Protokolldaten für die Laufwerke werden vom Storage Array für jedes Laufwerk verwaltet.

[NOTE]
====
Führen Sie diesen Befehl nur aus, wenn Sie vom technischen Support dazu aufgefordert werden.

====


== Syntax

[source, cli, subs="+macros"]
----
save allDrives logFile=pass:quotes["_filename_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`*logFile*`
 a| 
Der Dateipfad und der Dateiname, in den die Laufwerksprotokolle gespeichert werden sollen. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\drive01.zip"`

[NOTE]
====
Dieser Befehl fügt nicht automatisch eine Dateierweiterung an die gespeicherte Datei an. Sie müssen beim Eingeben des Dateinamens die Erweiterung .zip angeben.

====
|===


== Minimale Firmware-Stufe

6.10
