---
permalink: commands-a-z/save-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, external, key management, certificate 
summary: Der Befehl save storageArray keyManagementCertificate ruft das installierte Zertifikat ab. 
---
= Installiertes externes Schlüsselverwaltungszertifikat abrufen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray keyManagementCertificate` Befehl ruft das installierte Zertifikat ab.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----

save storageArray keyManagementCertificate certificateType=pass:quotes["_certificateType_"]
file=pass:quotes["_filename_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`certificateType`
 a| 
Hier können Sie den zu installierenden Zertifikatstyp angeben. Gültige Auswahlmöglichkeiten: `client` Oder `server`.



 a| 
`file`
 a| 
Ermöglicht die Angabe des Dateinamens für das signierte Zertifikat oder das Server-CA-Zertifikat.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
