---
permalink: commands-a-z/save-controller-arraymanagementsignedcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, server, certificate, sign, request, csr 
summary: 'Der Befehl Save Controller arrayManagementCSR ruft die installierte Server Certificate Signing Request (CSR) für den Controller ab, sodass Sie Zertifikatdetails anzeigen können.' 
---
= Installiertes Serverzertifikat abrufen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save controller arrayManagementCSR` Befehl ruft die Zertifikatsignierungsanforderung (CSR) für den Controller ab, damit Sie die Zertifikatdetails anzeigen können.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----

save controller [(a|b)] arrayManagementCSR file=pass:quotes["_filename_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`controller`
 a| 
Hier können Sie den Controller angeben, von dem Sie das signierte Zertifikat herunterladen möchten. Gültige Controller-IDs sind A oder b, wobei A der Controller in Steckplatz A ist und b der Controller in Steckplatz B ist Schließen Sie die Controller-Kennung in eckige Klammern ([ ]).



 a| 
`file`
 a| 
Hier können Sie die Datei angeben, für die die signierte Zertifikatdatei des Controllers gespeichert werden soll.

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "save controller [a] aarrayManagementCSR
   file="C:\controllerAcertificate.cer";"

SMcli -n Array1 -c "save controller [b] arrayManagementCSR
   file="C:\controllerBcertificate.cer";"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
