---
permalink: commands-a-z/save-storagearray-sasphycounts.html 
sidebar: sidebar 
keywords: save, storage, array, sas, phy, counts 
summary: 'Mit dem Befehl save storageArray SASPHYCounts werden die SAS Physical Layer (SAS PHY) Zähler in einer Datei gespeichert.' 
---
= Speichern der SAS-PHY-Zählungen des Speicherarrays – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray SASPHYCounts` Mit dem Befehl werden die Zähler der SAS-physischen Schicht (SAS PHY) in einer Datei gespeichert.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Führen Sie zum Zurücksetzen der SAS-PHY-Zähler das aus `reset storageArray SASPHYBaseline` Befehl.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
save storageArray SASPHYCounts file=pass:quotes["_filename_"]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in den Sie die SAS-PHY-Zähler speichern möchten. Schließen Sie den Dateipfad und den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\sasphy.csv"`

Der Standardname der Datei, die die SAS-PHY-Fehlerstatistiken enthält, ist `sas-phy-error-log.csv`. Sie können jeden beliebigen Dateinamen verwenden, aber Sie müssen den verwenden `.csv` Erweiterung.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
