---
permalink: commands-a-z/save-storagearray-rlscounts.html 
sidebar: sidebar 
keywords: save, storage, array, rls, counts 
summary: 'Mit dem Befehl „Storage Array RLSChales speichern“ werden die Zähler für den Leseverbindungsstatus (RLS) in einer Datei gespeichert.' 
---
= RLS-Anzahl des Speicher-Arrays speichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray RLSCounts` Befehl speichert die Zähler für den Leseverbindungsstatus (RLS) in einer Datei.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
save storageArray RLSCounts file=pass:quotes["_filename_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in den Sie die RLS-Zähler speichern möchten. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\rlscnt.csv"`

Der Standardname der Datei, die die RLS-Zählungen enthält, lautet `read-link-status.csv`. Sie können jeden beliebigen Dateinamen verwenden, aber Sie müssen den verwenden `.csv` Erweiterung.

|===


== Hinweise

Führen Sie die folgenden Schritte aus, um RLS-Zähler effektiver in einer Datei zu speichern:

. Führen Sie die aus `reset storageArray RLSBaseline` Befehl zum Festlegen aller RLS-Zähler auf 0.
. Sie können das Storage-Array für eine festgelegte Zeit laufen lassen (z. B. zwei Stunden).
. Führen Sie die aus `save storageArray RLSCounts file`=“[.code]``_filename_``„, Befehl.




== Minimale Firmware-Stufe

6.10
