---
permalink: commands-a-z/save-storagearray-keymanagementcertificate.html 
sidebar: sidebar 
keywords: retrieve, installed, external, key management, certificate 
summary: Der Befehl save storageArray keyManagementCertificate ruft das installierte Zertifikat ab. 
---
= Abrufen des installierten externen Verschlüsselungsmanagementzertifikats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray keyManagementCertificate` Befehl ruft das installierte Zertifikat ab.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E4000, E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle „Security Admin“ verfügen.



== Kontext

[NOTE]
====
Dieser Befehl gilt nur für externes Verschlüsselungsmanagement.

====


== Syntax

[source, cli, subs="+macros"]
----

save storageArray keyManagementCertificate certificateType=pass:quotes["_certificateType_"]
file=pass:quotes["_filename_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`certificateType`
 a| 
Hier können Sie den zu installierenden Zertifikatstyp angeben. Gültige Auswahlmöglichkeiten: `client` Oder `server`.



 a| 
`file`
 a| 
Ermöglicht die Angabe des Dateinamens für das signierte Zertifikat oder das Server-CA-Zertifikat.

|===


== Minimale Firmware-Stufe

8.40
