---
permalink: commands-a-z/save-storagearray-configuration.html 
sidebar: sidebar 
keywords: save, storage, array, configuration 
summary: Der Befehl Speicherarray-Konfiguration speichern erstellt eine Skriptdatei, mit der Sie die aktuelle Speicherarray-Volume-Konfiguration neu erstellen können. 
---
= Speicherarray-Konfiguration speichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `save storageArray configuration` Befehl erstellt eine Skriptdatei, mit der Sie die aktuelle Speicherarray-Volume-Konfiguration neu erstellen können.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen. Die Verwendung dieses Befehls mit dem LDAP-Parameter ist jedoch auf solche mit der Rolle Security Admin beschränkt.



== Kontext

[NOTE]
====
Dieser Befehl speichert keine Konfigurationsdaten für die Remote-Spiegelung oder für Volume-Kopien im aktuellen Storage Array in eine Datei.

====


== Syntax

[source, cli, subs="+macros"]
----
save storageArray configuration file=pass:quotes["_filename_"]
(allconfig|[globalSettings=(TRUE | FALSE)]
[volumeConfigAndSettings=(TRUE | FALSE)]
[hostTopology=(TRUE | FALSE)]
[lunMappings=(TRUE | FALSE)])
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`file`
 a| 
Der Dateipfad und der Dateiname, in dem die Konfigurationseinstellungen gespeichert werden sollen. Schließen Sie den Dateinamen in doppelte Anführungszeichen (" "). Beispiel:

`file="C:\Program Files\CLI\logs\saconf.cfg"`

Der Standardname der Datei, die die Konfigurationseinstellungen enthält, lautet `storage-array-configuration.cfg`. Dieser Befehl fügt nicht automatisch eine Dateierweiterung an die gespeicherte Datei an. Beim Eingeben des Dateinamens müssen Sie eine Dateierweiterung angeben.



 a| 
`allConfig`
 a| 
Die Einstellung zum Speichern aller Konfigurationswerte in der Datei. (Wenn Sie diesen Parameter auswählen, sind alle Konfigurationsparameter auf festgelegt `TRUE` .)



 a| 
`globalSettings`
 a| 
Die Einstellung zum Speichern der globalen Einstellungen in der Datei. Um die globalen Einstellungen zu speichern, setzen Sie diesen Parameter auf `TRUE`. Um das Speichern der globalen Einstellungen zu verhindern, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `TRUE`.



 a| 
`volumeConfigAndSettings`
 a| 
Die Einstellung zum Speichern der Volume-Konfigurationseinstellungen und aller globalen Einstellungen in der Datei. Um die Einstellungen für die Volume-Konfiguration und die globalen Einstellungen zu speichern, setzen Sie diesen Parameter auf `TRUE`. Um das Speichern der Volume-Konfigurationseinstellungen und der globalen Einstellungen zu verhindern, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `TRUE`.



 a| 
`hostTopology`
 a| 
Die Einstellung zum Speichern der Hosttopologie in der Datei. Um die Hosttopologie zu speichern, setzen Sie diesen Parameter auf `TRUE`. Um das Speichern der Hosttopologie zu verhindern, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `FALSE`.



 a| 
`lunMappings`
 a| 
Einstellung zum Speichern der LUN- oder NSID-Zuordnung in der Datei. Um die LUN- oder NSID-Zuordnung zu speichern, setzen Sie diesen Parameter auf `TRUE`. Um zu verhindern, dass die LUN oder NSID-Zuordnung gespeichert wird, setzen Sie diesen Parameter auf `FALSE`. Der Standardwert ist `FALSE`.

|===


== Hinweise

Wenn Sie diesen Befehl verwenden, können Sie beliebige Kombinationen der Parameter für die globale Einstellung, die Einstellung der Volume-Konfiguration, die Host-Topologie oder die LUN-Zuordnung angeben. Wenn Sie alle Einstellungen eingeben möchten, verwenden Sie die `allConfig` Parameter. Sie müssen entweder den verwenden `allConfig` Parameter oder ein oder mehrere der anderen vier Parameter.



== Minimale Firmware-Stufe

6.10
