---
permalink: commands-a-z/set-auditlog.html 
sidebar: sidebar 
keywords: set, audit log 
summary: Mit dem Befehl AuditLog festlegen werden die Einstellungen für das Prüfprotokoll konfiguriert. 
---
= Einstellungen für das Überwachungsprotokoll festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set auditLog` Befehl konfiguriert die Einstellungen für das Prüfprotokoll.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set auditLog (logLevel={all | writeOnly} |
    fullPolicy={overwrite | preventSystemAccess} |
    pass:quotes[maxRecords=_n_] | pass:quotes[warningThreshold=_n_)]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`logLevel`
 a| 
Ermöglicht die Angabe der Protokollierungsebene. Gültige Auswahlmöglichkeiten: `all` Und `writeOnly`. Der Standardwert ist `writeOnly`.



 a| 
`fullPolicy`
 a| 
Ermöglicht die Festlegung der Richtlinie, wenn das Protokoll voll ist. Gültige Auswahlmöglichkeiten: `overwrite` Und `preventSystemAccess`.



 a| 
`maxRecords`
 a| 
Ermöglicht dem Benutzer, die maximale Anzahl von Datensätzen anzugeben, die dort gespeichert werden sollen `n` Ist eine Ganzzahl, die bei 30000 beginnt und um 50000 endet.



 a| 
`warningThreshold`
 a| 
Mit dieser Option können Sie festlegen, in welchem Prozentsatz eine Warnmeldung gesendet wird, um anzugeben, dass das Prüfprotokoll sich bald voll nähert, wenn die vollständige Richtlinie auf festgelegt ist `preventSystemAccess`. Verwenden Sie ganzzahlige Werte zwischen 0 und 100. Wenn Sie diesen Parameter auf 0 (Null) setzen, werden die Warnmeldungen deaktiviert.

|===


[[examples]]
== Beispiele

[listing]
----

SMcli -n Array1 -c "set auditLog logLevel=writeOnly fullPolicy=preventSystemAccess maxRecords=40000 warningThreshold=90;"

SMcli completed successfully.
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.40
