---
permalink: commands-a-z/set-storagearray-vaaienabled.html 
sidebar: sidebar 
keywords: enable, disable, vaai 
summary: 'Der Befehl Set storageArray vaaiEnabled aktiviert oder deaktiviert die VMware vStorage API Array-Architektur (VAAI) für ein Storage-Array.' 
---
= VAAI aktivieren oder deaktivieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray vaaiEnabled` Befehl aktiviert oder deaktiviert die VMware vStorage API Array-Architektur (VAAI) für ein Storage-Array.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Beim Speicher-Array ist VAAI aktiviert. Verwenden Sie diesen Befehl, um VAAI zu deaktivieren, wenn Sie VAAI nicht ausführen möchten oder wenn VAAI Probleme mit dem Speicher-Array verursacht. Das einzige betroffene Storage Array ist das Storage Array, auf dem der Befehl ausgeführt wird.



[[syntax]]
== Syntax

[source, cli]
----
set storageArray vaaiEnabled=(TRUE | FALSE)
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`vaaiEnabled`
 a| 
Die Einstellung zum ein- oder Ausschalten von VAAI. Um VAAI zu aktivieren, setzen Sie diesen Parameter auf `TRUE`. Um VAAI auszuschalten, setzen Sie diesen Parameter auf `FALSE`. Die Standardeinstellung ist, dass VAAI eingeschaltet ist.

|===


[[notes]]
== Hinweise

[NOTE]
====
Mit VAAI können einige Storage-Aufgaben von der Server-Hardware auf ein Storage-Array ausgelagert werden. Durch das verlagern der Storage-Aufgaben auf ein Storage-Array wird die Host-Performance gesteigert, da die vom Host zu leistenden Aufgaben reduziert werden müssen.

====
[NOTE]
====
Zeigen Sie die VAAI-Einstellung mit dem an `show storageArray odxSetting` Name:

====


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.20
