---
permalink: commands-a-z/set-storagearray-isnslisteningport.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, listen, port 
summary: Der Befehl Set storageArray isnsListeningPort setzt den iSNS Server Listening Port. 
---
= Abhörport des iSNS-Servers des Speicherarrays festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray isnsListeningPort` Mit dem Befehl wird der Listening-Port des iSNS-Servers festgelegt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set storageArray isnsListeningPort=pass:quotes[_listeningPortIPAddress_]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`isnsListeningPort`
 a| 
Die IP-Adresse, die Sie für den Listening-Port des iSNS-Servers verwenden möchten. Der Wertebereich für den Listening-Port ist `49152` Bis `65535`. Der Standardwert ist `53205`.

Der Listening-Port befindet sich auf dem Server und führt die folgenden Aktivitäten aus:

* Überwacht eingehende Client-Verbindungsanforderungen
* Verwaltet den Datenverkehr zum Server


Wenn ein Client eine Netzwerksitzung mit einem Server anfordert, erhält der Listener die tatsächliche Anforderung. Wenn die Client-Informationen mit den Listener-Informationen übereinstimmen, gewährt der Listener eine Verbindung zum Datenbankserver.

|===


[[notes]]
== Hinweise

Ein Listening-Port befindet sich auf dem Datenbankserver und ist für folgende Aktivitäten verantwortlich:

* Zuhören (Überwachung) für eingehende Client-Verbindungsanforderungen
* Verwalten des Datenverkehrs zum Server


Wenn ein Client eine Netzwerksitzung mit einem Server anfordert, erhält ein Listener die tatsächliche Anforderung. Wenn die Client-Informationen mit den Listener-Informationen übereinstimmen, gewährt der Listener eine Verbindung zum Datenbankserver.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10
