---
permalink: commands-a-z/set-storagearray-unnameddiscoverysession.html 
sidebar: sidebar 
keywords: set, storage, array, unnamed, discovery, session 
summary: Mit dem Befehl Set storageArray unnameDiscoverySession kann das Storage Array an nicht genannten Discovery Sessions teilnehmen. 
---
= Unbenannte Erkennungssitzung für Speicherarray festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray unnamedDiscoverySession` Durch den Befehl kann das Speicher-Array an nicht benannten Ermittlungssitzungen teilnehmen.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Syntax

[source, cli]
----
set storageArray unnamedDiscoverySession=(TRUE | FALSE)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`unnamedDiscoverySession`
 a| 
Dieser Parameter schaltet unbenannte Ermittlungssitzungen ein oder aus. Setzen Sie den Parameter auf `TRUE` Um nicht benannte Ermittlungssitzungen zu aktivieren. Setzen Sie den Parameter auf `FALSE` So deaktivieren Sie nicht benannte Ermittlungssitzungen.

|===


== Hinweise

Discovery ist der Prozess, bei dem Initiatoren die verfügbaren Ziele bestimmen. Die Erkennung erfolgt beim Einschalten/Initialisieren und auch bei Änderungen der Bustopologie, z. B. wenn ein zusätzliches Gerät hinzugefügt wird.

Eine nicht benannte Ermittlungssitzung ist eine Ermittlungssitzung, die ohne Angabe einer Ziel-ID in der Login-Anforderung eingerichtet wird. Bei nicht benannten Ermittlungssitzungen stehen den Zielen weder die Ziel-ID noch die Zielportalgruppen-ID zur Verfügung.



== Minimale Firmware-Stufe

7.10
