---
permalink: commands-a-z/set-storagearray-autoloadbalancingenable.html 
sidebar: sidebar 
keywords: set, storage, array, enable, disable, automatic, load, balance 
summary: Der Befehl Set storageArray autoLoadBalancingEnable aktiviert oder deaktiviert die Funktion Automatic Load Balancing. 
---
= Stellen Sie das Speicherarray auf Aktivieren oder Deaktivieren des automatischen Lastausgleichs ein
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set storageArray autoLoadBalancingEnable` Befehl aktiviert oder deaktiviert die Funktion Automatischer Lastenausgleich.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Syntax

[listing]
----
set storageArray autoLoadBalancingEnable=(TRUE | FALSE)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`storageArray`
 a| 
Zeigt an, dass dieser Parameter auf einem Speicher-Array arbeitet.



 a| 
`autoLoadBalancingEnable`
 a| 
Dieser Parameter schaltet den automatischen Lastausgleich am Controller ein oder aus. Setzen Sie den Parameter auf `TRUE` Zum Einschalten des automatischen Lastverteilungsabwuchtes. Setzen Sie den Parameter auf `FALSE` So deaktivieren Sie den automatischen Lastenausgleich.

|===


== Was ist der automatische Lastausgleich?

Die Funktion Automatic Load Balancing bietet ein verbessertes I/O-Ressourcenmanagement, das dynamisch auf Laständerungen im Laufe der Zeit reagiert und die Eigentümerschaft der Volume-Controller automatisch angepasst wird, um Probleme bei der Lastverteilung, die zwischen den Controllern verschoben werden, zu beheben.

Die Auslastung jedes Controllers wird kontinuierlich überwacht und, zusammen mit den auf den Hosts installierten Multipath-Treibern, kann bei Bedarf automatisch ausgeglichen werden. Wenn die Workload automatisch auf die Controller umverteilt wird, entlastet der Storage-Administrator die manuelle Anpassung der Eigentümerschaft der Volume Controller, um Laständerungen am Storage Array zu bewältigen.

Wenn der automatische Lastenausgleich aktiviert ist, führt er folgende Funktionen aus:

* Automatische Überwachung und ausgewogene Nutzung von Controller-Ressourcen
* Bei Bedarf passt die Volume-Controller-Eigentümerschaft automatisch an, was die I/O-Bandbreite zwischen Hosts und Storage Array optimiert.




== Aktivieren und Deaktivieren des automatischen Lastauswuchtes

Der automatische Lastausgleich ist auf allen Storage-Arrays, die mit SANtricity OS (Controller-Software) 8.30 oder höher ausgeliefert werden, standardmäßig aktiviert. Linux-, Windows- und VMware Multipath-Treiber können die Funktion Automatischer Lastausgleich verwenden. Wenn Sie Ihren Controller von SANtricity OS (Controller-Software) 8.25 oder früher auf 8.30 oder höher aktualisieren, ist der automatische Lastausgleich standardmäßig auf dem Speicher-Array deaktiviert.

Aus den folgenden Gründen möchten Sie den automatischen Lastausgleich auf Ihrem Speicher-Array deaktivieren:

* Sie möchten die Controller-Eigentumsrechte eines bestimmten Volumes nicht automatisch ändern, um einen Workload-Ausgleich zu schaffen.
* Sie arbeiten in einer hoch abgestimmten Umgebung, in der die Lastverteilung gezielt eingerichtet ist, um eine bestimmte Verteilung zwischen den Controllern zu erreichen.


Wählen Sie im SANtricity Storage Manager die Menüoption *Speicherarray* *Konfiguration* *Automatischer Lastenausgleich* aus, um die Funktion Automatischer Lastenausgleich für ein einzelnes Speicherarray zu aktivieren oder zu deaktivieren.

Wählen Sie im SANtricity System Manager *Einstellungen* *System* aus, scrollen Sie nach unten zum Abschnitt *zusätzliche Einstellungen*, klicken Sie auf den Link E**nable/Disable Automatic Load Balancing** und wählen Sie das Kontrollkästchen**Automatic Load Balancing* aktivieren/deaktivieren**, um die Funktion für ein einzelnes Speicher-Array zu aktivieren bzw. zu deaktivieren.



== Beispiele

[listing]
----
SMcli -n Array1 -c "set storageArray autoLoadBalancingEnable=true;"

SMcli completed successfully.
----
[NOTE]
====
Eine aktive Bedingung „Drive Lost Primary Path“ führt dazu, dass der automatische Lastausgleich nicht in der Lage ist, Workloads auszugleichen. Diese Bedingung muss inaktiv sein, um sicherzustellen, dass die Workloads durch die Funktion Automatischer Lastenausgleich ausgeglichen werden.

====


== Minimale Firmware-Stufe

8.30
