---
permalink: commands-a-z/set-storagearray-isnsserverrefresh.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, refresh 
summary: Der Befehl Set storageArray isnsServerRefresh aktualisiert die Netzwerkaddress-Informationen für den iSNS-Server. 
---
= Aktualisierung des iSNS-Servers des Speicherarrays festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray isnsServerRefresh` Mit dem Befehl werden die Netzwerkaddress-Informationen für den iSNS-Server aktualisiert.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Dieser Befehl ist nur für IPv4 gültig.



== Syntax

[source, cli]
----
set storageArray isnsServerRefresh
----


== Parameter

Keine.



== Hinweise

Wenn der DHCP-Server nicht voll in Betrieb ist oder wenn der DHCP-Server nicht reagiert, kann die Aktualisierung zwei bis drei Minuten dauern.

Der `set storageArray isnsServerRefresh` Befehl gibt einen Fehler aus, wenn Sie die Konfigurationsmethode nicht auf DHCP festgelegt haben. Um die Konfigurationsmethode auf DHCP einzustellen, verwenden Sie das `set storageArray isnsIPV4ConfigurationMethod` Befehl.



== Minimale Firmware-Stufe

7.10
