---
permalink: commands-a-z/set-volumegroup-forcedstate.html 
sidebar: sidebar 
keywords: set, volume, group, forced, state 
summary: Der Befehl Set volumeGroup forceedState verschiebt eine Volume-Gruppe in einen Forced-Zustand. 
---
= Erzwungener Status der Volume-Gruppe festlegen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set volumeGroup forcedState` Befehl verschiebt eine Volume-Gruppe in einen Forced-Status.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Verwenden Sie diesen Befehl, wenn das ausgeführt wird `start volumeGroup import` Der Befehl verschiebt die Volume-Gruppe nicht in einen importierten Status oder wenn der Importvorgang aufgrund von Hardwarefehlern nicht funktioniert. Im Status „erzwungen“ kann die Volume-Gruppe importiert werden, und Sie können die Hardwarefehler erkennen.



== Syntax

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]] forcedState
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die Sie in den Status „gezwungen“ setzen möchten. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


== Hinweise

Sie können die Laufwerke, die eine Volume-Gruppe umfassen, von einem Speicher-Array zu einem anderen Speicher-Array verschieben. Die CLI bietet drei Befehle, mit denen Sie die Laufwerke verschieben können. Die Befehle lauten `start volumeGroup export`, `start volumeGroup import`, und `set volumeGroup forcedState`.

Im Status „erzwungen“ können Sie einen Importvorgang für die Volume-Gruppe durchführen.



== Minimale Firmware-Stufe

7.10
