---
permalink: commands-a-z/set-volume-logicalunitnumber.html 
sidebar: sidebar 
keywords: set, volume, map 
summary: 'Mit dem Befehl Set Volume logicalUnitNumber wird die Zuordnung der Logical Unit Number (LUN) oder Namespace ID (NSID) zwischen einem Volume und einer Host- oder Host-Gruppe definiert.' 
---
= Legen Sie die Volume-Zuordnung fest
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set volume logicalUnitNumber` Befehl definiert die Zuordnung der Logical Unit Number (LUN) oder Namespace ID (NSID) zwischen einem Volume und einer Host- oder Host-Gruppe.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

Dieser Befehl gilt für Volumes entweder in einer Volume-Gruppe oder für Festplatten-Pool.

[NOTE]
====
Dieser Befehl kann nicht für ein Snapshot-Volume verwendet werden, das in der Online-Volume-Kopie verwendet wird.

====


== Syntax

[listing, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] | volume <"wwID"> | accessVolume)
pass:quotes[logicalUnitNumber=_lun_]
pass:quotes[(host="_hostName_"] |
hostGroup=pass:quotes[("_hostGroupName_"] | defaultGroup)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volume`
 a| 
Der Name des Volumes, für das die Nummer der logischen Einheit definiert werden soll. Umschließen Sie den Volumennamen in eckige Klammern ([ ]). Wenn der Volume-Name Sonderzeichen oder Ziffern hat, müssen Sie den Volume-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`volume`
 a| 
Der World Wide Identifier (WWID) des Volumens, für das Sie die Nummer der logischen Einheit definieren möchten. Schließen Sie die WWID in doppelte Anführungszeichen (" ") innerhalb der Winkel Klammern (< >).



 a| 
`accessVolume`
 a| 
Die Nummer der logischen Einheit für das Zugriffsvolumen. Die Nummer der logischen Einheit ist die einzige Eigenschaft, die Sie für das Zugriffsvolumen festlegen können.



 a| 
`logicalUnitNumber`
 a| 
Die Nummer der logischen Einheit oder der Namespace-ID, die Sie verwenden möchten, um einem bestimmten Host zuzuordnen. Dieser Parameter weist den Host auch einer Host-Gruppe zu.

[NOTE]
====
Die angegebene Nummer der logischen Einheit oder Namespace-ID darf nicht bereits verwendet werden und muss sich innerhalb des vom Host-Betriebssystem unterstützten Bereichs befinden. Es wird kein Fehler geben, wenn Sie das Volume einer logischen Gerätenummer oder Namespace-ID zuordnen, die nicht vom Host unterstützt wird, aber der Host kann nicht auf das Volume zugreifen.

====


 a| 
`host`
 a| 
Der Name des Hosts, dem das Volume zugeordnet ist. Schließen Sie den Hostnamen in doppelte Anführungszeichen (" ").



 a| 
`hostGroup`
 a| 
Der Name der Host-Gruppe, der das Volume zugeordnet ist. Schließen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen (" "). `defaultGroup` Ist die Host-Gruppe, die den Host enthält, dem das Volume zugeordnet ist.

|===


== Hinweise

Eine Host-Gruppe ist ein optionales topologisches Element, das Sie definieren können, ob Sie eine Sammlung von Hosts bestimmen möchten, die Zugriff auf dieselben Volumes haben. Die Host-Gruppe ist eine logische Einheit. Definieren Sie eine Host-Gruppe nur, wenn Sie über zwei oder mehr Hosts verfügen, die den Zugriff auf dieselben Volumes teilen können.

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Bindestriche und Unterstrichen für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Das Zugriffs-Volume ist das Volume in einer SAN-Umgebung, das für die in-Band-Kommunikation zwischen der Storage-Managementsoftware und dem Storage-Array-Controller verwendet wird. Dieses Volume verwendet eine LUN- oder NSID-Adresse und verbraucht 20 MB Speicherplatz, der nicht zur Speicherung von Applikationsdaten verfügbar ist. Ein Zugriffs-Volume ist nur für bandinterne gemanagte Storage-Arrays erforderlich. Wenn Sie den angeben `accessVolume` Parameter, die einzige Eigenschaft, die Sie einstellen können, ist die `logicalUnitNumber` Parameter.



== Minimale Firmware-Stufe

7.83 fügt Snapshot-Volumen für Disk-Pools hinzu.
