---
permalink: commands-a-z/set-isertarget.html 
sidebar: sidebar 
keywords: set, iser, target 
summary: Der Befehl set iserTarget definiert Eigenschaften für ein iSER-Ziel. 
---
= ISER-Ziel festlegen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set iserTarget` Befehl definiert Eigenschaften für ein iSER-Ziel.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.

[NOTE]
====
Dieser Befehl ist veraltet und wird von ersetzt xref:set-target.adoc[Legen Sie die Zieleigenschaften fest] Befehl.

====


== Syntax

[listing, subs="+macros"]
----
set iserTarget pass:quotes[["_userLabel_"]]
authenticationMethod=(none | chap) |
chapSecret=pass:quotes[_securityKey_] |
targetAlias=pass:quotes["_userLabel_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`iserTarget`
 a| 
Das iSER-Ziel, für das Sie Eigenschaften festlegen möchten. Schließen Sie die ein `_userLabel_` In Doppelzitat-Marken (" "). Sie müssen auch die einschließen `_userLabel_` In eckigen Klammern ([ ]), wenn die Benutzerkabel ein Ziel-Alias oder Winkel-Klammern (< >) ist, wenn die Benutzerbezeichnung ein iSCSI-qualifizierter Name (IQN) ist.



 a| 
`authenticationMethod`
 a| 
Die Mittel zur Authentifizierung Ihrer iSCSI-Sitzung.



 a| 
`chapSecret`
 a| 
Der Sicherheitsschlüssel, den Sie zur Authentifizierung einer Peer-Verbindung verwenden möchten.



 a| 
`targetAlias`
 a| 
Der neue Name, den Sie für das Ziel verwenden möchten. Schließen Sie den Namen in doppelte Anführungszeichen (" ").

|===


== Hinweise

Challenge Handshake Authentication Protocol (CHAP) ist ein Protokoll, das den Peer einer Verbindung authentifiziert. CHAP basiert auf den Gleichgesinnten, die ein _secret_ teilen. Ein Geheimnis ist ein Sicherheitsschlüssel, der einem Kennwort ähnelt.

Verwenden Sie die `chapSecret` Parameter zum Einrichten der Sicherheitsschlüssel für Initiatoren, die eine gegenseitige Authentifizierung erfordern. Der CHAP-Schlüssel muss zwischen 12 und 57 Zeichen lang sein. In dieser Tabelle werden die gültigen Zeichen aufgeführt.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Platzbedarf
 a| 
!
 a| 
„
 a| 
#
 a| 
US-Dollar
 a| 
%
 a| 
Und
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
A
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
ICH
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
Q
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
A
 a| 
b
 a| 
c
 a| 
d
 a| 
E
 a| 
f
 a| 
G



 a| 
H
 a| 
Ich
 a| 
j
 a| 
k
 a| 
l
 a| 
M
 a| 
n
 a| 
o
 a| 
p
 a| 
q
 a| 
r
 a| 
S



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
X
 a| 
Y
 a| 
z
 a| 
{
 a| 
.
 a| 
}
 a| 
~
 a| 

|===


== Minimale Firmware-Stufe

8.20

8.41 dieser Befehl ist veraltet.
