---
permalink: commands-a-z/set-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: set, asynchronous, mirror, group 
summary: Der Befehl set async MirrorGroup ändert die Synchronisierungseinstellungen und Warnschwellenwerte, die der Controller-Eigentümer der primären Seite der asynchronen Spiegelgruppe bei der ersten Synchronisierung oder Neusynchronisierung verwendet. 
---
= Legen Sie die asynchrone Spiegelgruppe fest
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set asyncMirrorGroup` Befehl ändert die Synchronisierungseinstellungen und Warnschwellenwerte, die der Controller-Eigentümer der primären Seite der asynchronen Spiegelgruppe bei der ersten Synchronisierung oder Neusynchronisierung verwendet.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800 und E5700 Arrays. Solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800 oder E5700 Storage-Array auszuführen, müssen Sie über die Rolle „Storage-Admin“ oder „Support-Admin“ verfügen.



== Kontext

Das Ändern der Synchronisierungseinstellungen wirkt sich auf die Synchronisierungsvorgänge aller gespiegelten Paare innerhalb der asynchronen Spiegelgruppe aus.



== Syntax

[listing, subs="+macros"]
----
set asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
[volume="repos_xxxx" increaseRepositoryCapacity (repositoryVolume=("repos_xxxx")]
[syncInterval=pass:quotes[_integer_] (minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_] (minutes | hours | days)]
[warningRecoveryThreshold=integer (minutes | hours | days)]
[userLabel=pass:quotes["_New_asyncMirrorGroupName_"]]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[role=(primary | secondary)]
[autoResync=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`asyncMirrorGroup`
 a| 
Der Name der asynchronen Spiegelgruppe, die Sie ändern möchten. Schließen Sie den Namen der asynchronen Spiegelgruppe in eckige Klammern ([ ]). Wenn der Name der asynchronen Spiegelgruppe Sonderzeichen oder Ziffern hat, müssen Sie den Namen in doppelte Anführungszeichen („ “) in eckige Klammern setzen.



 a| 
`volume`
 a| 
Der Name eines asynchronen Spiegelgruppe-Repository-Volumes, für das Sie die Kapazität erhöhen möchten.

Der Name eines Repository Volumes besteht aus zwei Teilen:

* Der Begriff „Repos“
* Eine vierstellige numerische Kennung, die die Speicherverwaltungssoftware dem Namen des Repository-Volumes zuweist


Schließen Sie den Namen des Repository-Volumes in doppelte Anführungszeichen (" ").



 a| 
`syncInterval`
 a| 
Geben Sie die Zeitspanne zwischen dem automatischen Senden von Updates geänderter Daten vom lokalen Speicher-Array an das Remote-Speicher-Array an. Sie können die Dauer in Minuten, Stunden oder Tagen angeben.



 a| 
`warningSyncThreshold`
 a| 
Geben Sie die Wartezeit an, bis eine Warnung ausgelöst wird, wenn die Synchronisierung aller Volumes innerhalb der asynchronen Spiegelgruppe länger als die festgelegte Zeit dauert. Sie können die Dauer in Minuten, Stunden oder Tagen angeben.



 a| 
`warningRecoveryThreshold`
 a| 
Geben Sie die Wartezeit an, bis eine Warnung ausgelöst wird, wenn die automatische Datenaktualisierung für das Point-in-Time-Image auf dem Remote-Speicher-Array älter als die festgelegte Zeit ist. Definieren Sie den Schwellenwert ab Ende der vorherigen Aktualisierung. Sie können die Dauer in Minuten, Stunden oder Tagen angeben.

[NOTE]
====
Sie müssen festlegen, dass der Schwellenwert für den Wiederherstellungspunkt doppelt so groß ist wie der Schwellenwert für das Synchronisierungsintervall.

====


 a| 
`userLabel`
 a| 
Den neuen Namen, den Sie der asynchronen Spiegelgruppe geben möchten. Verwenden Sie diesen Parameter, wenn Sie die asynchrone Spiegelgruppe umbenennen möchten. Schließen Sie den neuen asynchronen Spiegelgruppe-Namen in doppelte Anführungszeichen (" ").



 a| 
`warningThresholdPercent`
 a| 
Geben Sie den Prozentwert an, der bestimmt, wann eine Warnung ausgelöst wird, wenn die Kapazität eines Spiegelspeicher-Volumes den definierten Prozentsatz erreicht. Definieren Sie den Schwellenwert um den Prozentsatz (%) der verbleibenden Kapazität.



 a| 
`role`
 a| 
Verwenden Sie diesen Parameter, um die asynchrone Spiegelgruppe auf eine primäre Rolle heranzustufen oder die asynchrone Spiegelgruppe auf eine sekundäre Rolle herabstufen. Um die asynchrone Spiegelgruppe als primäre Rolle zu definieren, setzen Sie diesen Parameter auf `primary`. Um die asynchrone Spiegelgruppe als sekundäre Rolle zu definieren, setzen Sie diesen Parameter auf `secondary`.



 a| 
`autoResync`
 a| 
Die Einstellungen für die automatische Neusynchronisierung zwischen den primären Volumes und den sekundären Volumes eines asynchronen gespiegelten Paares innerhalb einer asynchronen Spiegelgruppe. Dieser Parameter verfügt über die folgenden Werte:

* `enabled` -- Automatische Neusynchronisierung ist eingeschaltet. Sie müssen nichts weiter tun, um das primäre Volume und das sekundäre Volume neu zu synchronisieren.
* `disabled` -- Automatische Neusynchronisierung ist deaktiviert. Zum erneuten Synchronisieren des primären Volumes und des sekundären Volumes müssen Sie den ausführen `start asyncMirrorGroup` Befehl.


|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Wenn Sie diesen Befehl verwenden, können Sie einen oder mehrere Parameter angeben. Sie müssen jedoch nicht alle Parameter verwenden.

Ein asynchrones Spiegelgruppe-Repository-Volume ist ein erweiterbares Volume, das als zusammengegliederte Sammlung von bis zu 16 Standard-Volume-Einheiten strukturiert ist. Zu Beginn verfügt ein erweiterbares Repository Volume nur über ein einzelnes Volume. Die Kapazität des erweiterbaren Repository Volumes entspricht exakt der des einzelnen Volumes. Sie können die Kapazität eines erweiterbaren Repository-Volumes erhöhen, indem Sie ihm zusätzliche nicht verwendete Repository-Volumes hinzufügen. Die zusammengesetzte, erweiterbare Repository-Volume-Kapazität wird dann zur Summe der Kapazitäten aller verketteten Standard-Volumes.



== Minimale Firmware-Stufe

7.84
