---
permalink: commands-a-z/set-snapvolume-mediascanenabled.html 
sidebar: sidebar 
keywords: set, snapshot, volume, media, scan 
summary: Mit dem Befehl sSet SnapVolume mediaScanEnabled wird ein Medien-Scan auf den Laufwerken ausgeführt, die für ein Snapshot-Volume verwendet wurden. 
---
= Snapshot-Volume-Medienscan festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set snapVolume mediaScanEnabled` Mit dem Befehl wird ein Medien-Scan auf den Laufwerken ausgeführt, die für ein Snapshot-Volume verwendet wurden.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Optional können Sie auch eine Redundanzprüfung der Daten durchführen.



== Syntax

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]]
mediaScanEnabled=(TRUE | FALSE) [redundancyCheckEnabled=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`snapVolume`
 a| 
Der Name des Snapshot-Volumes, für das Sie Eigenschaften festlegen. Schließen Sie die Snapshot-Volume-Kennung in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]).



 a| 
`mediaScanEnabled`
 a| 
Die Einstellung zum ein- und Ausschalten des Medienscans für die Snapshot-Lautstärke. Um den Medienscan zu aktivieren, setzen Sie diesen Parameter auf `TRUE`. Um den Medienscan auszuschalten, setzen Sie diesen Parameter auf `FALSE`. (Wenn die Medienüberprüfung auf Speicherarray-Ebene deaktiviert ist, hat dieser Parameter keine Auswirkung.)



 a| 
`redundancyCheckEnabled`
 a| 
Die Einstellung zum ein- oder Ausschalten der Redundanzprüfung während eines Medienscans. Um die Redundanzprüfung zu aktivieren, setzen Sie diesen Parameter auf `TRUE` . Um die Redundanzprüfung auszuschalten, setzen Sie diesen Parameter auf `FALSE`.

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.



== Minimale Firmware-Stufe

7.83
