---
permalink: commands-a-z/set-snmptrapdestination-trapreceiverip.html 
sidebar: sidebar 
keywords: update, snmp, trap, destination 
summary: Der Befehl set snmpTrapReceiverIP aktiviert oder deaktiviert das Senden von Authentifizierungsfehlern für ein SNMP-Trap-Ziel. Ein Fehler tritt auf, wenn der SNMP-Agent eine Nachricht von einem SNMP-Manager empfangen hat, aber die Nachricht einen ungültigen Community-Namen oder Benutzernamen enthielt. 
---
= Aktualisieren Sie das SNMP-Trap-Ziel
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set snmpTrapDestination trapReceiverIP` Befehl schaltet das Senden von Authentifizierungsfehlern für ein SNMP-Trap-Ziel ein oder aus. Ein Fehler tritt auf, wenn der SNMP-Agent eine Nachricht von einem SNMP-Manager empfangen hat, aber die Nachricht einen ungültigen Community-Namen oder Benutzernamen enthielt.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage-Admin“ oder „Support-Admin“ vorhanden sein.



== Syntax

[listing, subs="+macros"]
----
set snmpTrapDestination trapReceiverIP=ipAddress
(communityName=pass:quotes["_communityName_"] | (userName=pass:quotes["_userName_"] [engineId=(local | engineId)]))
[sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`trapReceiverIP`
 a| 
Die IP-Adresse des SNMP-Managers, an den Sie Trap-Nachrichten senden möchten.



 a| 
`communityName`
 a| 
Der Name der SNMP-Community, für die Sie Trap-Nachrichten senden möchten.



 a| 
`userName`
 a| 
Der Name des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten.



 a| 
`engineId`
 a| 
Die Engine-ID des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten. Die Engine-ID ist erforderlich, wenn mehr als ein USM-Benutzer mit demselben Benutzernamen vorhanden ist. Der Wert kann „[.code]``local``„ Zur Angabe des lokalen SNMP-Agenten ist der autorisierende Agent oder eine hexadezimale Ziffernfolge, in der eine Remote-SNMP-Agent-Engine-ID angegeben wird.



 a| 
`sendAuthenticationFailureTraps`
 a| 
Dieser Parameter aktiviert oder deaktiviert das Senden von Authentifizierungsfehlern an einen SNMP-Manager. Um Authentifizierungsfehler zu senden, setzen Sie den Parameter auf `TRUE`. Um zu verhindern, dass Authentifizierungsfehler gesendet werden, setzen Sie den Parameter auf `FALSE`. Die Standardeinstellung lautet `TRUE`.

|===


== Minimale Firmware-Stufe

8.30
