---
permalink: commands-a-z/set-iscsiinitiator.html 
sidebar: sidebar 
keywords: set, iscsi, initiator 
summary: Der Befehl set iscsiInitiator setzt die Attribute für einen iSCSI-Initiator. 
---
= Setzen Sie den iSCSI-Initiator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set iscsiInitiator` Mit dem Befehl werden die Attribute für einen iSCSI-Initiator festgelegt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.

[NOTE]
====
Dieser Befehl ist veraltet und wird von ersetzt xref:set-initiator.adoc[Legt den Initiator fest] Befehl.

====


== Syntax

[source, cli, subs="+macros"]
----
set iscsiInitiator (pass:quotes[["_initiatorUserLabel_"]] | <"_iscsiInitiatorName_">)
(userLabel=pass:quotes["_newName_"] |
host=pass:quotes["_newHostName_"] |
chapSecret=pass:quotes["_newSecurityKey_"])
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`initiatorUserLabel`
 a| 
die iscsi-Initiator-Benutzerbezeichnung des iSCSI-Initiators, für den Sie Attribute festlegen möchten. Schließen Sie das iSCSI-Initiator-Benutzeretikett in doppelten Anführungszeichen („ “) in eckigen Klammern ([ ]).

[NOTE]
====
Starten Sie die Initiator-Benutzerbeschriftung mit dem Host-Namen, mit dem der Host-Port verbunden ist. Da auf einem Host mehr als eine Host-Port-Kennung vorhanden sein kann, verwenden Sie ein eindeutiges Suffix für die Host-Port-ID. Wenn der Hostname lautet `ICTM1590S02H1` Die Bezeichnung des Initiators wird wie folgt angezeigt:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`iscsiInitiatorName`
 a| 
Der Name des Initiators, für den Sie Attribute festlegen möchten. Schließen Sie die ein `iscsiInitiatorName` In Doppelzitat-Markierungen (" ") innerhalb Winkel Klammern ( ).

[NOTE]
====
Der `iscsiInitiatorName` Ist der qualifizierte iSCSI-Name (iqn). Ein Beispiel:

====
[listing]
----
set iscsiInitiator <"iqn.2016-11.com.vmware.iscsi:ictm1509s02h1">
----


 a| 
`userLabel`
 a| 
Die neue Benutzerbezeichnung, die Sie für den iSCSI-Initiator verwenden möchten. Schließen Sie das neue Benutzungsetikett in doppelte Anführungszeichen (" ").

[NOTE]
====
Als Best Practice empfiehlt es sich, mit dem Initiator-Benutzernamen, mit dem der Host-Port verbunden ist, zu beginnen. Da auf einem Host mehr als eine Host-Port-Kennung vorhanden sein kann, verwenden Sie ein eindeutiges Suffix für die Host-Port-ID. Wenn der Hostname lautet `ICTM1590S02H1` Anschließend wird unten ein Beispiel für die Bezeichnung eines Initiators angezeigt:

====
[listing]
----
set iscsiInitiator ["ICTM1590S02H1_AA"]
----


 a| 
`host`
 a| 
Der Name des neuen Hosts, mit dem der Host-Port verbunden ist. Schließen Sie den Hostnamen in doppelte Anführungszeichen (" "). Im Folgenden sehen Sie ein Beispiel:

[listing]
----
["ICTM1590S02H2"]
----


 a| 
`chapSecret`
 a| 
Der Sicherheitsschlüssel, den Sie zur Authentifizierung einer Peer-Verbindung verwenden möchten. Schließen Sie den Sicherheitsschlüssel in doppelte Anführungszeichen („ “).

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Bindestriche und Unterstrichen für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Challenge Handshake Authentication Protocol (CHAP) ist ein Protokoll, das den Peer einer Verbindung authentifiziert. CHAP basiert auf den Gleichgesinnten, die ein _secret_ teilen. Ein Geheimnis ist ein Sicherheitsschlüssel, der einem Kennwort ähnelt.

Verwenden Sie die `chapSecret` Parameter zum Einrichten der Sicherheitsschlüssel für Initiatoren, die eine gegenseitige Authentifizierung erfordern. Der CHAP-Schlüssel muss zwischen 12 und 57 Zeichen lang sein. In dieser Tabelle werden die gültigen Zeichen aufgeführt.

[cols="1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a,1a"]
|===


 a| 
Platzbedarf
 a| 
!
 a| 
„
 a| 
#
 a| 
US-Dollar
 a| 
%
 a| 
Und
 a| 
'
 a| 
(
 a| 
)
 a| 
*
 a| 



 a| 
,
 a| 
-
 a| 
.
 a| 
/
 a| 
0
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7



 a| 
8
 a| 
9
 a| 
:
 a| 
;
 a| 
<
 a| 
=
 a| 
>
 a| 
?
 a| 
@
 a| 
A
 a| 
B
 a| 
C



 a| 
D
 a| 
E
 a| 
F
 a| 
G
 a| 
H
 a| 
ICH
 a| 
J
 a| 
K
 a| 
L
 a| 
M
 a| 
N
 a| 
O



 a| 
P
 a| 
Q
 a| 
R
 a| 
S
 a| 
T
 a| 
U
 a| 
V
 a| 
W
 a| 
X
 a| 
Y
 a| 
Z
 a| 
[



 a| 
\
 a| 
]
 a| 
^
 a| 
_
 a| 
'
 a| 
A
 a| 
b
 a| 
c
 a| 
d
 a| 
E
 a| 
f
 a| 
G



 a| 
H
 a| 
Ich
 a| 
j
 a| 
k
 a| 
l
 a| 
M
 a| 
n
 a| 
o
 a| 
p
 a| 
q
 a| 
r
 a| 
S



 a| 
t
 a| 
u
 a| 
v
 a| 
w
 a| 
X
 a| 
Y
 a| 
z
 a| 
{
 a| 
.
 a| 
}
 a| 
~
 a| 

|===


== Minimale Firmware-Stufe

7.10

8.41 dieser Befehl ist veraltet.
