---
permalink: commands-a-z/set-snapvolume-mediascanenabled.html 
sidebar: sidebar 
keywords: set, snapshot, volume, media, scan 
summary: Mit dem Befehl sSet SnapVolume mediaScanEnabled wird ein Medien-Scan auf den Laufwerken ausgeführt, die für ein Snapshot-Volume verwendet wurden. 
---
= Snapshot-Volume-Medienscan festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set snapVolume mediaScanEnabled` Mit dem Befehl wird ein Medien-Scan auf den Laufwerken ausgeführt, die für ein Snapshot-Volume verwendet wurden.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Optional können Sie auch eine Redundanzprüfung der Daten durchführen.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]]
mediaScanEnabled=(TRUE | FALSE) [redundancyCheckEnabled=(TRUE | FALSE)]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`snapVolume`
 a| 
Der Name des Snapshot-Volumes, für das Sie Eigenschaften festlegen. Schließen Sie die Snapshot-Volume-Kennung in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]).



 a| 
`mediaScanEnabled`
 a| 
Die Einstellung zum ein- und Ausschalten des Medienscans für die Snapshot-Lautstärke. Um den Medienscan zu aktivieren, setzen Sie diesen Parameter auf `TRUE`. Um den Medienscan auszuschalten, setzen Sie diesen Parameter auf `FALSE`. (Wenn die Medienüberprüfung auf Speicherarray-Ebene deaktiviert ist, hat dieser Parameter keine Auswirkung.)



 a| 
`redundancyCheckEnabled`
 a| 
Die Einstellung zum ein- oder Ausschalten der Redundanzprüfung während eines Medienscans. Um die Redundanzprüfung zu aktivieren, setzen Sie diesen Parameter auf `TRUE` . Um die Redundanzprüfung auszuschalten, setzen Sie diesen Parameter auf `FALSE`.

|===


[[notes]]
== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.83
