---
permalink: commands-a-z/set-storagearray-usersession.html 
sidebar: sidebar 
keywords: set, storage, array, user, session 
summary: Mit dem Befehl set storageArray userSession können Sie in System Manager ein Timeout einstellen, sodass die inaktiven Benutzersitzungen nach einer bestimmten Zeit getrennt werden. 
---
= Speicherarray-Benutzersitzung festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray userSession` Mit Befehl können Sie in System Manager eine Zeitüberschreitung einstellen, so dass die inaktiven Sitzungen des Benutzers nach einer bestimmten Zeit getrennt werden.



== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



== Kontext

Verwenden Sie diesen Befehl, um eine der folgenden Vorgänge auszuführen:

* Legen Sie für Benutzersitzungen eine Zeitüberschreitung in Sekunden fest. Der Wert für die minimale Zeitüberschreitung beträgt 900 Sekunden (15 Minuten).
* Deaktivieren Sie die Sitzungszeitpunkte, indem Sie den Wert auf 0 setzen.




== Parameter

Keine.



== Syntax

[source, cli]
----
set storageArray userSession sessionTimeout=n
----


== Minimale Firmware-Stufe

8.41
