---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: Der Befehl Set storageArray ControllerHealthImageAllowOverWrite setzt ein Flag auf einen Controller, um ein vorhandenes Controller-Zustandsabbild auf Storage Arrays zu überschreiben, die die Funktion des Controller-Zustandsabbilds unterstützen. 
---
= Festlegen des Integritätsimages des Speicherarray-Controllers, das Überschreiben zulässt – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray controllerHealthImageAllowOverWrite` Befehl setzt ein Flag auf einem Controller, um es einem neuen Controller-Zustandsabbild zu ermöglichen, ein vorhandenes Controller-Zustandsabbild auf Storage Arrays zu überschreiben, die die Funktion des Controller-Zustandsabbilds unterstützen.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Wenn das Storage-Array die Funktion für das Integritätsabbild des Controllers nicht unterstützt, gibt der Befehl einen Fehler aus.

[NOTE]
====
Mit der Firmware-Version 8.20 der `coreDumpAllowOverWrite` Parameter wird durch das ersetzt `controllerHealthImageAllowOverWrite` Parameter.

====


[[syntax]]
== Syntax

[source, cli]
----
set storageArray controllerHealthImageAllowOverWrite
----


[[parameters]]
== Parameter

Keine.



[[notes]]
== Hinweise

Wenn das Controller-Zustandsabbild abgerufen wird, nimmt das `allow overwrite` Flag ist gesetzt. Wenn das Controller-Zustandsabbild nicht abgerufen wird, läuft das Image innerhalb von 48 Stunden ab, danach läuft `allow overwrite` Flag ist gesetzt. Wenn Sie das verwenden `set storageArray controllerHealthImageAllowOverWrite` Befehl zum Festlegen des `allow overwrite` Flag: Auf die 48-Stunden-Verfallfrist wird verzichtet, als ob das Bild abgerufen worden wäre.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.86

8.20 ersetzt die `*coreDumpAllowOverWrite*` Parameter mit `controllerHealthImageAllowOverWrite` Parameter.
