---
permalink: commands-a-z/set-drive-serviceallowedindicator.html 
sidebar: sidebar 
keywords: set, drive, service, action, allowed, indicator 
summary: Mit dem Befehl Laufwerk einstellen serviceAllowedIndicator wird die Anzeigeleuchte Wartungsmaßnahme zulässig an einem Laufwerk oder Laufwerken in Laufwerksfächern, die die Funktion Wartungszuzulassen unterstützen, ein- oder ausgeschaltet. 
---
= Indikator für zulässige Laufwerksdienstaktion festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set drive serviceAllowedIndicator` Mit dem Befehl wird die Anzeigeleuchte Wartungsmaßnahme zulässig an einem Laufwerk oder Laufwerken in Laufwerksfächern aktiviert oder deaktiviert, die die Funktion für die Kontrollleuchte Serviceaktion zulässig unterstützen.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Wenn das Speicherarray die Funktion „Anzeige für Serviceaktion zulässig“ nicht unterstützt, gibt dieser Befehl einen Fehler aus. Wenn das Speicher-Array den Befehl unterstützt, die Kontrollleuchte jedoch nicht einschalten oder ausschalten kann, gibt dieser Befehl einen Fehler aus.



== Syntax

[source, cli, subs="+macros"]
----
set (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
serviceAllowedIndicator=(on | off)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`drive` Oder `drives`
 a| 
Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`.

Alle maximale Steckplatz-ID sind 24. Die Steckplatz-ID-Werte beginnen je nach Fachmodell bei 0 oder 1. Die Laufwerksfächer sind mit E2800 und E5700 Controllern kompatibel und besitzen die Steckplatz-ID-Nummern ab 0. Die Laufwerksfächer sind mit E2700 und E5600 Controllern kompatibel und verfügen ab 1 über die Steckplatz-ID.

Schließen Sie den Wert für Fach-ID, die Fach-ID und den Wert für die Steckplatz-ID in eckigen Klammern ([ ]) an.



 a| 
`serviceAllowedIndicator`
 a| 
Die Einstellung zum ein- und Ausschalten der Kontrollleuchte Serviceaktion zulässig. Um die Anzeigeleuchte Serviceaktion zulässig einzuschalten, setzen Sie diesen Parameter auf `on`. Um die Anzeigeleuchte „Serviceaktion erlaubt“ auszuschalten, setzen Sie diesen Parameter auf `off`.

|===


== Hinweise

Der `drive` Der Parameter unterstützt sowohl Laufwerksfächer mit hoher Kapazität als auch Laufwerksfächer mit geringer Kapazität. Ein Laufwerksfach mit hoher Kapazität verfügt über Schubladen, die die Laufwerke halten. Die Schubladen ziehen aus dem Laufwerksfach, um Zugriff auf die Laufwerke zu ermöglichen. Ein Laufwerksfach mit geringer Kapazität verfügt nicht über Schubladen. Bei einem Laufwerksfach mit hoher Kapazität müssen Sie die Kennung (ID) des Laufwerksfachs, die ID des Fachs und die ID des Steckplatzes, in dem sich ein Laufwerk befindet, angeben. Bei einem Laufwerksfach mit niedriger Kapazität müssen Sie nur die ID des Laufwerksfachs und die ID des Steckplatzes angeben, in dem sich ein Laufwerk befindet. Bei einem Laufwerksfach mit geringer Kapazität kann die ID des Laufwerksfachs auf festgelegt werden, um einen Speicherort für ein Laufwerk zu ermitteln `0`, Und geben Sie die ID des Steckplatzes an, in dem sich ein Laufwerk befindet.



== Minimale Firmware-Stufe

6.16

7.60 fügt die hinzu `drawerID` Benutzereingaben.
