---
permalink: commands-a-z/set-storagearray-autosupportremotediag.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, remote, diagnostics, feature, individual, E2800, E5700, arrays 
summary: Der Befehl Set storageArray autoSupportRemoteDiag aktiviert oder deaktiviert die AutoSupport OnDemand Remote Diagnostics-Funktion. Mit dieser Funktion kann der technische Support per Fernzugriff Support-Daten anfordern, um Probleme zu diagnostizieren. 
---
= Aktivieren oder deaktivieren Sie die AutoSupport-Funktion für die Ferndiagnose
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray autoSupportRemoteDiag` Mit dem Befehl wird die AutoSupport OnDemand-Ferndiagnosefunktion ein- oder ausgeschaltet. Mit dieser Funktion kann der technische Support per Fernzugriff Support-Daten anfordern, um Probleme zu diagnostizieren.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E4000, E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Kontext

Bevor Sie diese Funktion aktivieren, aktivieren Sie zunächst die AutoSupport-Funktion und dann die AutoSupport OnDemand-Funktion auf dem Storage-Array.

Sie müssen die drei Funktionen in der folgenden Reihenfolge aktivieren:

. Aktivieren Sie AutoSupport
. Aktivieren Sie AutoSupport OnDemand
. AutoSupport Remote Diagnostics aktivieren




== Syntax

[source, cli]
----
set storageArray autoSupportRemoteDiag (enable | disable)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`enable | disable`
 a| 
Ermöglicht dem Benutzer, die AutoSupport-Ferndiagnosefunktion zu aktivieren oder zu deaktivieren. Wenn AutoSupport und AutoSupport OnDemand deaktiviert sind, wird die Aktion Aktivieren fehlerhaft und der Benutzer wird aufgefordert, diese zuerst zu aktivieren.

|===


== Beispiele

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportRemoteDiag enable;"

SMcli completed successfully.
----


== Verifizierung

Verwenden Sie die `show storageArray autoSupport` Befehl, um zu sehen, ob Sie die Funktion aktiviert haben. In den ersten drei Zeilen der angezeigten Ausgabe wird der Enable-Status der AutoSupport-Funktion angezeigt, gefolgt von der AutoSupport OnDemand-Funktion und der AutoSupport Remote-Diagnose-Funktion:

[listing]
----
The AutoSupport feature is enabled on this storage array.
The AutoSupport OnDemand feature is enabled on this storage array.
The AutoSupport Remote Diagnostics feature is enabled on this storage array.
----


== Minimale Firmware-Stufe

8.40
