---
permalink: commands-a-z/set-hostgroup.html 
sidebar: sidebar 
keywords: set, host, group 
summary: Der Befehl Set hostGroup benennt eine Host-Gruppe. 
---
= Hostgruppe festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set hostGroup` Mit dem Befehl wird eine Host-Gruppe umbenannt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set hostGroup pass:quotes[[_hostGroupName_]]
userLabel=pass:quotes["_newHostGroupName_"]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`hostGroup`
 a| 
Der Name der Host-Gruppe, die Sie umbenennen möchten. Fügen Sie den Namen der Host-Gruppe in eckige Klammern ([ ]) ein. Wenn der Name der Host-Gruppe Sonderzeichen oder Zahlen hat, müssen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`userLabel`
 a| 
Der neue Name für die Host-Gruppe. Schließen Sie den Namen der neuen Host-Gruppe in doppelte Anführungszeichen (" ").

|===


[[notes]]
== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Bindestriche und Unterstrichen für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
