---
permalink: commands-a-z/set-snmptrapdestination-trapreceiverip.html 
sidebar: sidebar 
keywords: update, snmp, trap, destination 
summary: Der Befehl set snmpTrapReceiverIP aktiviert oder deaktiviert das Senden von Authentifizierungsfehlern für ein SNMP-Trap-Ziel. Ein Fehler tritt auf, wenn der SNMP-Agent eine Nachricht von einem SNMP-Manager empfangen hat, aber die Nachricht einen ungültigen Community-Namen oder Benutzernamen enthielt. 
---
= SNMP-Trap-Ziel aktualisieren – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set snmpTrapDestination trapReceiverIP` Befehl schaltet das Senden von Authentifizierungsfehlern für ein SNMP-Trap-Ziel ein oder aus. Ein Fehler tritt auf, wenn der SNMP-Agent eine Nachricht von einem SNMP-Manager empfangen hat, aber die Nachricht einen ungültigen Community-Namen oder Benutzernamen enthielt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Speichersystem auszuführen, müssen Sie die Rolle Storage Admin oder Support Admin haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
set snmpTrapDestination trapReceiverIP=ipAddress
(communityName=pass:quotes["_communityName_"] | (userName=pass:quotes["_userName_"] [engineId=(local | engineId)]))
[sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`trapReceiverIP`
 a| 
Die IP-Adresse des SNMP-Managers, an den Sie Trap-Nachrichten senden möchten.



 a| 
`communityName`
 a| 
Der Name der SNMP-Community, für die Sie Trap-Nachrichten senden möchten.



 a| 
`userName`
 a| 
Der Name des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten.



 a| 
`engineId`
 a| 
Die Engine-ID des SNMP-Benutzers, für den Sie Trap-Nachrichten senden möchten. Die Engine-ID ist erforderlich, wenn mehr als ein USM-Benutzer mit demselben Benutzernamen vorhanden ist. Der Wert kann „[.code]``local``„ Zur Angabe des lokalen SNMP-Agenten ist der autorisierende Agent oder eine hexadezimale Ziffernfolge, in der eine Remote-SNMP-Agent-Engine-ID angegeben wird.



 a| 
`sendAuthenticationFailureTraps`
 a| 
Dieser Parameter aktiviert oder deaktiviert das Senden von Authentifizierungsfehlern an einen SNMP-Manager. Um Authentifizierungsfehler zu senden, setzen Sie den Parameter auf `TRUE`. Um zu verhindern, dass Authentifizierungsfehler gesendet werden, setzen Sie den Parameter auf `FALSE`. Die Standardeinstellung lautet `TRUE`.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.30
