---
permalink: commands-a-z/set-storagearray-icmppingresponse.html 
sidebar: sidebar 
keywords: set, storage, array, icmp, response 
summary: Der Befehl Set storageArray icmpPingResponse gibt die Standardwerte für verhandelbare Einstellungen für Sitzungen und Verbindungen zurück, die den Ausgangspunkt für die Verhandlungen des Speicher-Arrays darstellen. 
---
= ICMP-Antwort des Speicherarrays festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray icmpPingResponse` Befehl gibt die Standardwerte für die verhandelbaren Einstellungen für Sitzungen und Verbindungen zurück, die den Ausgangspunkt für das Speicher-Array für Verhandlungen darstellen.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli]
----
set storageArray icmpPingResponse=(TRUE | FALSE)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`icmpPingResponse`
 a| 
Dieser Parameter schaltet Echoanforderungsmeldungen ein oder aus. Setzen Sie den Parameter auf `TRUE` So aktivieren Sie Echoanforderungsmeldungen. Setzen Sie den Parameter auf `FALSE` So deaktivieren Sie Echoanforderungsmeldungen.

|===


== Hinweise

Das Internet Control Message Protocol (ICMP) wird von Betriebssystemen in einem Netzwerk verwendet, um Fehlermeldungen, Testpakete und Informationsmeldungen im Zusammenhang mit der IP zu senden, z. B. ein angeforderter Dienst ist nicht verfügbar oder ein Host oder Router konnte nicht erreicht werden. Der ICMP-Antwortbefehl sendet ICMP Echo Request-Meldungen und erhält ICMP Echo Response-Meldungen, um zu ermitteln, ob ein Host erreichbar ist und welche Zeit es dauert, bis Pakete von und zu diesem Host gelangen.



== Minimale Firmware-Stufe

7.10
