---
permalink: commands-a-z/set-tray-attribute.html 
sidebar: sidebar 
keywords: set, tray, attribute 
summary: Mit dem Befehl Fach einstellen werden benutzerdefinierte Attribute für ein Fach festgelegt 
---
= Tray-Attribut festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set tray` Mit Befehl werden benutzerdefinierte Attribute für ein Fach festgelegt



== Syntax

[source, cli, subs="+macros"]
----
set tray pass:quotes[[_trayID_]] (chassisName | assetTag)=pass:quotes["_userID_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`tray`
 a| 
Gibt ein bestimmtes Fach an, für das das Attribut festgelegt werden soll. Die Werte für die Fach-ID sind 0 bis 99. Sie müssen Klammern ([ ]) um den Gehäuse-ID-Wert legen.



 a| 
`chassisName`
 a| 
Den Chassis-Namen oder die Nummer, mit der das neue Gehäuse angegeben werden soll. Chassisnamen können eine beliebige Kombination aus alphanumerischen Zeichen mit einer maximalen Länge von 32 Zeichen sein. Alphabetische Zeichen können groß oder klein sein. Sie können auch das Unterstrich-Zeichen (_) und das Bindestrich (-) verwenden. Leerzeichen in einem Chassis-Namen können nicht verwendet werden. Sie müssen Anführungszeichen („ “) um den Chassis-Namen herum setzen.



 a| 
`assetTag`
 a| 
Asset-Tag-Name oder -Nummer, um das neue Gehäuse anzugeben. Asset-Tags können eine beliebige Kombination aus alphanumerischen Zeichen mit einer maximalen Länge von zehn Zeichen sein. Alphabetische Zeichen können groß oder klein sein. Sie können auch das Unterstrich-Zeichen (_) und das Bindestrich (-) verwenden. Sie können keine Leerzeichen in einem Asset-Tag-Namen verwenden. Sie müssen Anführungszeichen („ “) um den Namen der Asset-Tag-Nummer legen.

|===


== Minimale Firmware-Stufe

6.16
