---
permalink: commands-a-z/set-email-smtp-delivery-method.html 
sidebar: sidebar 
keywords: specify, email, smtp, delivery method, individual, E2800, E5700, arrays 
summary: 'Mit dem Befehl Set storageArray AutoSupport deliveryMethod wird die Bereitstellungsmethode für das Senden von AutoSupport-Nachrichten an E-Mail (SMTP) eingerichtet.' 
---
= Geben Sie die SMTP-Bereitstellungsmethode (E-Mail) an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray autoSupport deliveryMethod` Mit dem Befehl wird die Bereitstellungsmethode zum Senden von AutoSupport-Meldungen an E-Mail (SMTP) eingerichtet.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E4000, E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Administrator oder Support-Administrator verfügen.



== Syntax

[source, cli, subs="+macros"]
----
set storageArray autoSupport deliveryMethod=email
mailRelayServer=pass:quotes["_serverAddress_" senderEmail="_emailAddress_"] destinationAddress="destination1@example.com" destinationAddress="destination2@example.com";
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`deliveryMethod`
 a| 
Ermöglicht dem Benutzer, die Bereitstellungsmethode für die AutoSupport-Sammlung festzulegen. Gültige Auswahlmöglichkeiten:

* E-Mail
* HTTPS


[NOTE]
====
Wenn die E-Mail-Methode konfiguriert ist, werden AutoSupport OnDemand und Remote Diagnostics deaktiviert.

====


 a| 
`mailRelayServer`
 a| 
Ermöglicht dem Benutzer, den Mail-Relay-Server für die AutoSupport-Sammlung anzugeben.



 a| 
`senderEmail`
 a| 
Ermöglicht dem Benutzer die Angabe der E-Mail-Adresse für die AutoSupport-Sammlung.



 a| 
`destinationAddress`
 a| 
E-Mail-Adresse, an die AutoSupport-Dispatches gesendet werden. Dieser Parameter kann mehrmals bereitgestellt werden, um das Senden von Dispatches an mehrere Adressen zu ermöglichen.

|===


=== Beispiele

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportConfig deliveryMethod=email mailRelayServer=\"mailserver.company.com\" senderEmail=\"user@company.com\";"

SMcli completed successfully.
----


=== Verifizierung

Senden Sie mit dem eine Testmeldung `_start storageArray autoSupport deliveryTest_` Befehl, um zu überprüfen, ob Ihre Bereitstellungsmethoden korrekt eingerichtet sind.



== Minimale Firmware-Stufe

8.40
