---
permalink: commands-a-z/set-storagearray-passwordlength.html 
sidebar: sidebar 
keywords: set, storage, array, password, length 
summary: Mit dem Befehl Set storageArray Passwordlength kann der Admin-Benutzer eine Mindestlänge für alle neuen oder aktualisierten Passwörter im Speicher-Array festlegen. 
---
= Speicherarray-Passwortlänge festlegen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `set storageArray passwordlength` Befehl ermöglicht dem Admin-Benutzer, eine Mindestlänge für alle neuen oder aktualisierten Passwörter im Speicher-Array festzulegen.



== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Security Admin-Rolle haben.



== Syntax

[source, cli]
----
set storageArray passwordLength=<INTEGER>
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`password length`
 a| 
Ermöglicht das Festlegen der erforderlichen Mindestlänge für alle neuen oder aktualisierten Passwörter.



 a| 
`INTEGER`
 a| 
Ermöglicht die Festlegung der erforderlichen Mindestlänge zwischen 0 und 30 für alle neuen oder aktualisierten Passwörter.

|===


== Beispiele

[listing]
----

SMcli <array_ip> -u <username> -p <password> -c "set storageArray passwordLength=0;"

SMcli completed successfully.
----


== Minimale Firmware-Stufe

8.41 fügt den Befehl hinzu.
