---
permalink: commands-a-z/set-storagearray-odxenabled.html 
sidebar: sidebar 
keywords: enable, disable, odx 
summary: 'Der Befehl Set storageArray odxEnabled aktiviert oder deaktiviert den Offloaded Data Transfer (ODX) für ein Storage-Array.' 
---
= Aktivieren oder Deaktivieren von ODX
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `set storageArray odxEnabled` Befehl schaltet den Offloaded Data Transfer (ODX) für ein Storage-Array ein oder aus.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage-Admin“ oder „Support-Admin“ vorhanden sein.



== Kontext

Im Storage-Array ist ODX aktiviert. Verwenden Sie diesen Befehl, um ODX zu deaktivieren, wenn Sie ODX nicht ausführen möchten oder wenn ODX Probleme im Storage-Array verursacht. Das einzige betroffene Storage Array ist das Storage Array, auf dem der Befehl ausgeführt wird.



== Syntax

[listing]
----
set storageArray odxEnabled=(TRUE | FALSE)
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`odxEnabled`
 a| 
Die Einstellung zum ein- oder Ausschalten von ODX. Um ODX zu aktivieren, setzen Sie diesen Parameter auf `TRUE`. Um ODX auszuschalten, setzen Sie diesen Parameter auf `FALSE`. Die Standardeinstellung ist, dass ODX aktiviert ist.

|===


== Hinweise

ODX bietet eine Möglichkeit zum Datentransfer ohne gepufferte Lese- und gepufferte Schreibvorgänge und erfordert beim Datentransfer keine direkte Host-Beteiligung. Wenn ODX nicht aktiviert ist, werden Daten vom Quell-Storage auf den Host gelesen und anschließend vom Host auf den Ziel-Storage geschrieben. Bei einem ODX-fähigen Datentransfer werden die Storage-Infrastruktur direkt gemanagt. Die Daten werden direkt vom Quell-Storage auf den Ziel-Storage verschoben, ohne auf den Host zu zugreifen.



== Minimale Firmware-Stufe

8.20
