---
permalink: commands-a-z/show-volumegroup.html 
sidebar: sidebar 
keywords: show, volume, group 
summary: Der Befehl show VolumeGroup gibt Informationen zu einer Volume-Gruppe zurück. 
---
= Volume-Gruppe anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show volumeGroup` Befehl gibt Informationen zu einer Volume-Gruppe zurück.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Admin oder Storage-Monitor verfügen.



== Kontext

Dieser Befehl gibt diese Informationen zu einer Volume-Gruppe zurück:

* Der Status (z. B. optimal, degraded, failed, missing)
* Der Kapazität
* Der aktuelle Besitzer (die Steuerung in Steckplatz A oder die Steuerung in Steckplatz B)
* RAID-Level
* Der Laufwerkstyp (HDD oder SSD)
* Der Schnittstellentyp des Laufwerks (Fibre Channel, iSCSI, InfiniBand, SAS)
* Schutz vor Verlust des Fachs (ja oder nein)
* Secure-fähig: Gibt an, ob die Volume-Gruppe aus allen sicheren Laufwerken besteht. Sichere Laufwerke können entweder FDE- oder FIPS-Laufwerke sein.
* Secure – gibt an, ob die Laufwerkssicherheit aktiviert ist (dies wird als sicher aktiviert bezeichnet).
* Den damit verbundenen Volumes und der freien Kapazität
* Die zugehörigen Laufwerke
* Data Assurance-Funktionen und das Vorhandensein von Volumes, die Data Assurance unterstützen
* Funktionen für die Ressourcenbereitstellung




== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, für die Informationen angezeigt werden sollen. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


== Hinweise

Dieser Befehl gibt Informationen zu den Volume-Gruppen zurück, wie im folgenden Beispiel gezeigt:

[listing]
----
Name:              SecureGroup

      Status:         Optimal
      Capacity:       120.000 GB
      Current owner: Controller in slot A

      Quality of Service (QoS) Attributes

         RAID level:                  5
         Drive media type:            Hard Disk Drive
         Drive interface type:        SAS
         Shelf loss protection:       No
         Secure Capable:              Yes
         Secure:                      No
         Data Assurance (DA) capable: Yes
         DA enabled volume present:   No
         Resource-provisioned:           Yes


      Total Volumes:          1
         Standard volumes:    1
         Repository volumes:  0
         Free Capacity:       110.000 GB

      Associated drives - present (in piece order)
      Total drives present: 5

         Tray     Slot
         99       1
         99       2
         99       3
         99       4
         99       5
----


== Minimale Firmware-Stufe

6.10
