---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: Der Befehl show storageArray unconfiguredIscsiInitiatoren gibt eine Liste der Initiatoren zurück, die vom Storage Array erkannt wurden, aber noch nicht in der Topologie des Storage-Arrays konfiguriert sind. 
---
= Zeigt nicht konfigurierte iSCSI-Initiatoren des Speicherarrays an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray unconfiguredIscsiInitiators` Der Befehl gibt eine Liste der Initiatoren zurück, die vom Storage-Array erkannt wurden, jedoch noch nicht in der Topologie des Storage-Arrays konfiguriert sind.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Admin oder Storage-Monitor verfügen.

Dieser Befehl ist veraltet. Der Befehl, der ihn ersetzt, ist link:show-storagearray-unconfiguredinitiators.html["Storage Array ohne KonfigurationsInitiatoren anzeigen"].



== Syntax

[source, cli]
----
show storageArray unconfiguredIscsiInitiators
----


== Parameter

Keine.



== Minimale Firmware-Stufe

7.10

8.50 hat diesen Befehl abgelehnt.
