---
permalink: commands-a-z/show-storagearray-lunmappings.html 
sidebar: sidebar 
keywords: show, storage, array, lun, map 
summary: 'Der Befehl show storageArray lunMappings gibt Informationen aus dem Speicher-Array-Profil über die LUN (Logical Unit Number) oder Namespace ID (NSID)-Zuordnungen im Speicher-Array zurück.' 
---
= Speicherarray-LUN-Zuordnungen anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray lunMappings` Der Befehl gibt Informationen aus dem Speicher-Array-Profil über die Zuordnung der Logical Unit Number (LUN) oder Namespace ID (NSID) im Speicher-Array zurück.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.



[[context]]
== Kontext

Es werden immer standardmäßige Gruppen-LUN oder NSID-Zuordnungen angezeigt. Wenn Sie diesen Befehl ohne Parameter ausführen, gibt dieser Befehl alle LUN- oder NSID-Zuordnungen zurück.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
show storageArray lunMappings (host pass:quotes[["_hostName_"]] |
hostgroup pass:quotes[["_hostGroupName_"]])
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`host`
 a| 
Der Name eines bestimmten Hosts, für den die LUN- oder NSID-Zuordnungen angezeigt werden sollen. Schließen Sie den Hostnamen in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.



 a| 
`hostGroup`
 a| 
Der Name einer bestimmten Host-Gruppe, für die die LUN- oder NSID-Zuordnungen angezeigt werden sollen. Schließen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]).

|===


[[notes]]
== Hinweise

Dieser Befehl gibt Informationen zur Hosttopologie zurück, die diesem Beispiel ähnlich sind.

[listing]
----
MAPPINGS (Storage Partitioning - Enabled (0 of 16 used))
VOLUME NAME  LUN  CONTROLLER  ACCESSIBLE BY  VOLUME STATUS
Access Volume 7   A,B         Default Group  Optimal
21           21   B           Default Group  Optimal
22           22   B           Default Group  Optimal
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
