---
permalink: commands-a-z/show-volumecopy-sourcecandidates.html 
sidebar: sidebar 
keywords: show, volume, copy, source, candidates 
summary: Der Befehl show VolumeCopy SourceCandidates gibt Informationen zu den Kandidatenvolumes zurück, die Sie als Quelle für einen Kopiervorgang verwenden können. Dieser Befehl gilt für Snapshot-Volume-Kopierpaare. 
---
= Kandidaten für Volume-Kopierquellen anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show volumeCopy sourceCandidates` Der Befehl gibt Informationen zu den Kandidatenvolumes zurück, die Sie als Quelle für einen Kopiervorgang des Volumes verwenden können. Dieser Befehl gilt für Snapshot-Volume-Kopierpaare.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.



== Syntax

[source, cli]
----
show volumeCopy sourceCandidates
----


== Parameter

Keine.



== Hinweise

Dieser Befehl gibt Quellinformationen zu Volume-Kopien zurück, wie in diesem Beispiel gezeigt.

[listing]
----
Volume Name: finance
   Capacity: 4.0 GB
   Volume Group: 1
Volume Name: engineering
   Capacity: 4.0 GB
   Volume Group: 2
----