---
permalink: commands-a-z/show-storagearray-unreadablesectors.html 
sidebar: sidebar 
keywords: show, storage, array, unreadable, sectors 
summary: Der Befehl show storageArray unreadableSectors gibt eine Tabelle mit den Adressen aller Sektoren im Speicher-Array zurück, die nicht gelesen werden können. 
---
= Nicht lesbare Sektoren des Speicherarrays anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray unreadableSectors` Befehl gibt eine Tabelle mit den Adressen aller Sektoren im Speicher-Array zurück, die nicht gelesen werden können.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.



[[context]]
== Kontext

Die zurückgegebene Tabelle ist mit Spaltenüberschriften für die folgenden Informationen organisiert:

* Datenträger-Benutzeretikett
* Logical Unit Number (LUN)
* Zugriff durch (Host oder Host-Gruppe)
* Datum/Uhrzeit
* Volume-relative logische Block-Adresse (hexadezimales Format -- 0xnnnnnnnnnnn)
* Position des Laufwerks (Fach t, Steckplatz s)
* Laufwerk-relative logische Blockadresse (hexadezimales Format -- 0xnnnnnnnnnnn)
* Fehlertyp


Die Daten werden zunächst nach dem Datenträger-Benutzernamen sortiert und zweitens nach der logischen Blockadresse (LBA). Jeder Eintrag in der Tabelle entspricht einem einzelnen Sektor.



[[syntax]]
== Syntax

[source, cli]
----
show storageArray unreadableSectors
----


[[parameters]]
== Parameter

Keine.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10
