---
permalink: commands-a-z/show-ssd-cache.html 
sidebar: sidebar 
keywords: show, ssd, cache 
summary: Mit dem Befehl show ssdCache werden Informationen zum SSD-Cache angezeigt. 
---
= Zeigt den SSD-Cache an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `show ssdCache` Mit Befehl werden Informationen zum SSD-Cache angezeigt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E2700, E5600, E2800, E5700, EF600- und EF300-Arrays, sofern alle SMcli-Pakete installiert sind



== Rollen

Sie müssen über die Rolle Support Admin verfügen, um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array ausführen zu können.



== Syntax

[listing, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, für den Sie Informationen abrufen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen oder Ziffern hat, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Hinweise

Dieser Befehl gibt die SSD-Cache-Informationen zurück, die diesem Beispiel ähnlich sind.

[listing]
----
SSD Cache name: my_cache

Status:                              Optimal
Type:                                Read Only
I/O characteristic type:             File System
Maximum capacity allowed:            1,862.645 GB
Current capacity:                    557.792 GB
Additional capacity allowed          1,304.852 GB
Drive capacities:                    All 278.896 GB
Quality of Service (QoS) Attributes
   Security capable:                 No
   Secure:                           No
   Data Assurance (DA) capable:      No
Associated drives:

Tray     Slot
0        4
0        11
Volumes using SSD cache:             volume_test
----


== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
