---
permalink: commands-a-z/show-asyncmirrorgroup-synchronizationprogress.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, group, synchronization, progress 
summary: Der Befehl show async cMirrorGroup SynchronisationProgress zeigt den Fortschritt der periodischen Synchronisierung der asynchronen Spiegelgruppe zwischen dem lokalen und dem Remote-Speicher-Array an. 
---
= Fortschritt der asynchronen Spiegelgruppensynchronisierung anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show asyncMirrorGroup synchronizationProgress` Der Befehl zeigt den Status der Synchronisierung der asynchronen Spiegelgruppe zwischen dem lokalen und dem Remote-Speicher-Array an.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Dieser Befehl gibt den Fortschritt der Datensynchronisierung für alle gespiegelten Paare innerhalb der asynchronen Spiegelgruppe zurück. Dieser Befehl zeigt den Fortschritt als Prozentsatz der abgeschlossenen Datensynchronisierung an.

[NOTE]
====
Es gibt zwei Arten der Synchronisierung: Die erste Synchronisierung und die periodische Synchronisierung. Der anfängliche Synchronisierungsfortschritt für die asynchrone Spiegelgruppe wird im Dialogfeld *long running Operations* und durch Ausführen des angezeigt `show storageArray longRunningOperations` Befehl.

====


== Syntax

[source, cli, subs="+macros"]
----
show asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
[synchronizationProgress]
[summary]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`asyncMirrorGroup`
 a| 
Der Name einer asynchronen Spiegelgruppe, für die die Synchronisierung der asynchronen Spiegelgruppe zwischen dem lokalen und dem Remote-Speicher-Array angezeigt werden soll. Schließen Sie den Namen der asynchronen Spiegelgruppe in eckige Klammern ([ ]). Wenn der Name der asynchronen Spiegelgruppe Sonderzeichen oder Ziffern hat, müssen Sie den Namen der asynchronen Spiegelgruppe in doppelten Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`synchronizationProgress`
 a| 
Dieser Parameter zeigt den periodischen Synchronisierungsfortschritt der asynchronen Spiegelgruppe an.



 a| 
`summary`
 a| 
Mit diesem Parameter wird eine kurze Liste von Informationen zur Synchronisierung der asynchronen Spiegelgruppe zwischen dem lokalen und dem Remote-Speicher-Array angezeigt.

|===


== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
