---
permalink: commands-a-z/show-volumecopy.html 
sidebar: sidebar 
keywords: show, volume, copy 
summary: Der Befehl show VolumeCopy gibt Informationen zu den Vorgängen für Volume-Kopien zurück. 
---
= Volumekopie anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show volumeCopy` Der Befehl gibt Informationen zu Vorgängen beim Volume-Kopieren zurück.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.



[[context]]
== Kontext

Dieser Befehl gibt folgende Informationen zu Volume-Kopiervorgängen zurück:

* Der Kopierstatus
* Der Startzeitstempel
* Der Zeitstempel für die Fertigstellung
* Die Kopierpriorität
* Das Quell-Volume World Wide Identifier (WWID) oder das Ziel-Volume WWID
* Die Einstellung des Schreibschutzattributs für Zielvolumen


Sie können Informationen zu einem bestimmten Volume-Kopie-Paar oder zu allen Volume-Kopie-Paaren im Storage-Array abrufen. Dieser Befehl gilt für Snapshot-Volume-Kopierpaare.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
show volumeCopy (allVolumes | source pass:quotes[["_sourceName_"]] |
target pass:quotes[["_targetName_"]])
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allVolumes`
 a| 
Die Einstellung zur Ausgabe von Informationen zu Volume-Kopiervorgängen für alle Volume-Copy-Paare.



 a| 
`source`
 a| 
Der Name des Quellvolumens, zu dem Informationen abgerufen werden sollen. Schließen Sie den Namen des Quell-Volumes in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.



 a| 
`target`
 a| 
Der Name des Zielvolumens, zu dem Informationen abgerufen werden sollen. Schließen Sie den Namen des Zielvolumens in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.

|===