---
permalink: commands-a-z/show-snmpsystemvariables.html 
sidebar: sidebar 
keywords: show, snmp, mib ii, system, group, variables 
summary: 'Der Befehl show snmpSystemVariables gibt Informationen über die SNMP-Systemvariablen (Simple Network Management Protocol) zurück. Die Systemvariablen werden in einer Management Information Base II (MIB-II)-Datenbank verwaltet.' 
---
= SNMP MIB II-Systemgruppenvariablen anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show snmpSystemVariables` Der Befehl gibt Informationen zu den SNMP-Systemvariablen (Simple Network Management Protocol) zurück. Die Systemvariablen werden in einer Management Information Base II (MIB-II)-Datenbank verwaltet.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Rolle Storage Admin, Support Admin oder Storage Monitor haben.



[[syntax]]
== Syntax

[source, cli]
----
show snmpSystemVariables
----


[[parameters]]
== Parameter

Keine.



[[notes]]
== Hinweise

Dieser Befehl gibt Informationen zu SNMP-Systemvariablen zurück, die diesem Beispiel ähnlich sind.

[listing]
----
SYSTEM VARIABLES
    Sys Name: NONE
    Sys Contact: NONE
    Sys Location: NONE
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

8.30
