---
permalink: commands-a-z/show-snapvolume.html 
sidebar: sidebar 
keywords: show, snapshot, volumes 
summary: Der Befehl show SnapVolume gibt Informationen über ein oder mehrere Snapshot-Volumes zurück. 
---
= Snapshot-Volumes anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show snapVolume` Befehl gibt Informationen über ein oder mehrere Snapshot-Volumes zurück.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Syntax

[source, cli, subs="+macros"]
----
show (allSnapVolumes | snapVolume pass:quotes[["_snapVolumeName_"]] |
snapVolumes pass:quotes[["_snapVolumeName1_" ... "_snapVolumeNamen_"]])
[summary]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allSnapVolumes`
 a| 
Der Parameter, um Informationen über alle Snapshot-Volumes im Speicher-Array zurückzugeben.



 a| 
`snapVolume`
 a| 
Der Name eines Snapshot-Volumes, über das Sie Informationen abrufen möchten. Schließen Sie den Namen des Snapshot-Volumes in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.



 a| 
`snapVolumes`
 a| 
Die Namen mehrerer Snapshot-Volumen, für die Sie Informationen abrufen möchten. Geben Sie die Namen der Snapshot Volumen mithilfe dieser Regeln ein:

* Schließen Sie alle Namen in eckige Klammern ([ ]).
* Schließen Sie jeden dieser Namen in doppelte Anführungszeichen (" ").
* Trennen Sie jede der Namen mit einem Leerzeichen.




 a| 
`summary`
 a| 
Der Parameter, um eine kurze Liste von Informationen über die Snapshot-Volumes zurückzugeben.

|===


== Hinweise

Sie können eine beliebige Kombination aus alphanumerischen Zeichen, Unterstrich (_), Bindestrich (-) und Pfund (#) für die Namen verwenden. Namen können maximal 30 Zeichen lang sein.

Dieser Befehl gibt Informationen zum Snapshot Volume zurück, wie im folgenden Beispiel gezeigt:

[listing]
----
SNAPSHOT VOLUME (SNAPSHOT-IMAGE BASED) SUMMARY
----
[listing]
----
SUMMARY

 Total Snapshot Volumes: 1
   Most Recent Snapshot Volume: Day month date hh:mm:ss yyyy
   Status: 1 Optimal, 0 Non Optimal

   Name        Type       Status     Capacity    Associated Base Volume
   2_SV_0001   Standard   Optimal    3.000 GB    2
----
[listing]
----
   Snapshot Volume Timestamp   Snapshot Image Timestamp    Mode
   1/23/12 6:44:31 PM IST      1/23/12 6:27:36 PM IST      Read Write
----
[listing]
----
   Total Repository Capacity   Available Repository Capacity
   1.199 GB                    0.125 MB (0%)
----
Die Größe des Monitors bestimmt, wie die Informationen umschließt und wie die Informationen angezeigt werden.



== Minimale Firmware-Stufe

7.83
