---
permalink: commands-a-z/show-replaceabledrives.html 
sidebar: sidebar 
keywords: show, replaceable, drives 
summary: Mit dem Befehl ErsatzlaufeLaufwerke anzeigen werden alle austauschbaren Laufwerke in einem Storage-Array angezeigt. 
---
= Austauschbare Laufwerke anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show replaceableDrives` Mit dem Befehl werden alle austauschbaren Laufwerke in einem Speicher-Array angezeigt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Der Befehl gibt für jedes austauschbare Laufwerk im Speicher-Array die folgenden Informationen zurück:

* Die Position des Fachs und die Position des Schlitzes
* Der Name der Volume-Gruppe, zu der das Laufwerk gehört
* Der World Wide Name (WWN)
* Der Status des Laufwerks




[[syntax]]
== Syntax

[source, cli]
----
show replaceableDrives
----


[[example-output]]
== Beispielausgabe

[listing]
----
Replaceable drive at Tray 0, Slot 3
                Volume group: 2
                World-wide name: 5000c50028785aff0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 23
                Volume group: 2
                World-wide name: 5000c500095d46df0000000000000000
                Status: Removed
Replaceable drive at Tray 0, Slot 24
                Volume group: 2
                World-wide name: 5000c500287854d70000000000000000
                Status: Removed
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10
