---
permalink: commands-a-z/show-storagearray-unconfigurediscsiinitiators.html 
sidebar: sidebar 
keywords: show, storage, array, unconfigured, iscsi, initiators 
summary: Der Befehl show storageArray unconfiguredIscsiInitiatoren gibt eine Liste der Initiatoren zurück, die vom Storage Array erkannt wurden, aber noch nicht in der Topologie des Storage-Arrays konfiguriert sind. 
---
= Nicht konfigurierte iSCSI-Initiatoren des Speicherarrays anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray unconfiguredIscsiInitiators` Der Befehl gibt eine Liste der Initiatoren zurück, die vom Storage-Array erkannt wurden, jedoch noch nicht in der Topologie des Storage-Arrays konfiguriert sind.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.

Dieser Befehl ist veraltet. Der Befehl, der ihn ersetzt, ist link:show-storagearray-unconfiguredinitiators.html["Storage Array ohne KonfigurationsInitiatoren anzeigen"].



[[syntax]]
== Syntax

[source, cli]
----
show storageArray unconfiguredIscsiInitiators
----


[[parameters]]
== Parameter

Keine.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10

8.50 hat diesen Befehl abgelehnt.
