---
permalink: commands-a-z/show-allhostports.html 
sidebar: sidebar 
keywords: show, host, ports 
summary: Der Befehl show allHostPorts gibt Informationen über konfigurierte Host-Ports zurück. 
---
= Host-Ports anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show allHostPorts` Befehl gibt Informationen zu konfigurierten Host-Ports zurück.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Bei allen Host-Ports, die mit einem Speicher-Array verbunden sind, gibt dieser Befehl folgende Informationen aus:

* Die Host-Port-ID
* Der Name des Host-Ports
* Der Host-Typ




== Syntax

[source, cli]
----
show allHostPorts
----


== Parameter

Keine.



== Hinweise

Dieser Befehl gibt Informationen über den HBA-Host-Port zurück, die diesem Beispiel ähnlich sind.

[listing]
----
HOST PORT IDENTIFIER     HOST PORT NAME  HOST TYPE
12:34:56:54:33:22:22:22  Jupiter1        Solaris
12:34:56:78:98:98:88:88  Pluto1          Windows 2000/Server 2003 Clustered
54:32:12:34:34:55:65:66  Undefined       Undefined
----


== Minimale Firmware-Stufe

5.40
