---
permalink: commands-a-z/show-volume.html 
sidebar: sidebar 
keywords: show, thin, volume 
summary: Der Befehl show Volume gibt den Erweiterungsverlauf bzw. die verbrauchte Kapazität für das angegebene Thin-Volume oder die angegebenen Volumes zurück. 
---
= Thin Volume anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `show volume` Der Befehl gibt den Verlauf der Erweiterung oder die verbrauchte Kapazität für das angegebene Thin Volume oder die angegebenen Volumes zurück.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage Admin“ oder „Storage Monitor“ lauten.



== Syntax

[listing, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]])
(consumedCapacity |
(expansionHistory pass:quotes[[file=_fileName_]]))
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allVolumes`
 a| 
Dieser Parameter gibt Informationen zu allen Thin Volumes im Speicher-Array zurück.



 a| 
`volume`
 a| 
Der Name eines Thin-Volumes, für das Sie Informationen abrufen. Schließen Sie den Namen des dünnen Volumens in eckige Klammern ([ ]). Wenn der Name des Thin-Volumes Sonderzeichen oder Ziffern hat, müssen Sie den Thin-Volume-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`volumes`
 a| 
Die Namen mehrerer Thin Volumes, für die Sie Informationen abrufen möchten. Geben Sie die Namen der Volumes mithilfe folgender Regeln ein:

* Schließen Sie alle Namen in eckige Klammern ([ ]).
* Trennen Sie jede der Namen mit einem Leerzeichen.


Wenn die Volume-Namen Sonderzeichen oder Ziffern enthalten, geben Sie die Namen unter Verwendung folgender Regeln ein:

* Schließen Sie alle Namen in eckige Klammern ([ ]).
* Schließen Sie jeden dieser Namen in doppelte Anführungszeichen (" ").
* Trennen Sie jede der Namen mit einem Leerzeichen.




 a| 
`consumedCapacity`
 a| 
Die Einstellung, um eine kurze Liste von Informationen über die verbrauchte Kapazität der Thin Volumes anzuzeigen.



 a| 
`expansionHistory`
 a| 
Die Einstellung, um eine kurze Liste von Informationen über den Erweiterungsverlauf der Thin Volumes anzuzeigen.



 a| 
`file`
 a| 
Der `file` Parameter gibt eine Datei an, die die Ausgabe des protokolliert `expansionHistory` Parameter. Der `file` Ist nur gültig, wenn Sie mit dem verwendet werden `expansionHistory` Parameter. Ein ungültiger Dateiname führt zum Fehlschlagen des Befehls.

|===


== Hinweise

Mit dem `expansionHistory` Parameter: Der Befehl gibt Informationen zurück, die ähnlich dem unten gezeigten Beispiel sind.

`Thin volume name: volume-nameRepository volume Name: REPOS_NNNN`

[cols="4*"]
|===
| Protokollierte Zeit | Erweiterungstyp | Beginnen Sie Mit Der Kapazität | End-Kapazität 


 a| 
MM/TT/JJJJ HH:MM:SS
 a| 
Manuell Automatisch
 a| 
NNNNNNNNNNNN Byte
 a| 
NNNNNNNNNNNN Byte

|===
Mit dem `consumedCapacity` Parameter: Der Befehl gibt Informationen zurück, die ähnlich dem unten gezeigten Beispiel sind.

[cols="5*"]
|===
| Datenmenge | Bereitgestellte Kapazität | Verbrauchte Kapazität | Kontingente | % Prov. Belegt 


 a| 
`volumeName`
 a| 
500.000 GB
 a| 
230.000 GB
 a| 
700.000 GB
 a| 
46 % erzielt

|===


== Minimale Firmware-Stufe

7.83
