---
permalink: commands-a-z/show-volumegroup-importdependencies.html 
sidebar: sidebar 
keywords: show, volume, group, import, dependencies 
summary: Der Befehl show VolumeGroup importAbhängigkeiten zeigt eine Liste der Abhängigkeiten für die Laufwerke in einer Volume-Gruppe an, die von einem Storage Array zu einem zweiten Storage Array verschoben werden sollen. 
---
= Zeigen Sie die Importabhängigkeiten der Volume-Gruppen an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `show volumeGroup importDependencies` Der Befehl zeigt eine Liste der Abhängigkeiten für die Laufwerke in einer Volume-Gruppe an, die von einem Storage Array auf ein zweites Storage Array verschoben werden sollen.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage Admin“ oder „Storage Monitor“ lauten.



== Syntax

[listing, subs="+macros"]
----
pass:quotes[show volumeGroup [_volumeGroupName_]] importDependencies
[cancelImport=(TRUE | FALSE)]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, für die Importabhängigkeiten angezeigt werden sollen. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).



 a| 
`cancelImport`
 a| 
Die Einstellung zum Hochfahren der Laufwerke nach dem Lesen der Volume-Gruppenabhängigkeiten. Um die Laufwerke herunterzufahren, setzen Sie diesen Parameter auf `TRUE`. Um die Laufwerke weiterhin zu drehen, setzen Sie diesen Parameter auf `FALSE`.

|===


== Hinweise

Dieser Befehl gibt die Abhängigkeiten einer bestimmten Volume-Gruppe zurück, die sich in einem exportierten Zustand oder in einem Forced-Status befinden muss. Wenn eine Entscheidung getroffen wird, die aufgeführten Abhängigkeiten beizubehalten, dann die `cancelImport` Parameter können durchgesetzt werden, um die Laufwerke wieder nach unten zu schalten.

Sie müssen den ausführen `show volumeGroup importDependencies` Befehl vor dem Ausführen des `start volumeGroup import` Befehl.



== Minimale Firmware-Stufe

7.10
