---
permalink: commands-a-z/show-storagearray-autosupport.html 
sidebar: sidebar 
keywords: show, autosupport, configuration, e2800, e5700, storage, arrays 
summary: Mit dem Befehl show storageArray AutoSupport werden die AutoSupport Bundle Erfassungseinstellungen für das Speicher-Array angezeigt. 
---
= Zeigt die AutoSupport-Konfiguration an
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray autoSupport` Mit dem Befehl werden die Einstellungen für die AutoSupport-Bundle-Sammlung für das Speicher-Array angezeigt.



== Unterstützte Arrays

Dieser Befehl kann entweder für die E4000, E2800, E5700, EF600 und EF300 Storage-Arrays ausgeführt werden.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Rolle Storage-Admin oder Support-Admin oder Storage-Monitor verfügen.



== Kontext

Mit der Ausgabe des Befehls über diesen Befehl werden die folgenden Konfigurationsinformationen angezeigt:

* Der Aktivierungsstatus für diese Managementdomäne der AutoSupport-Funktion, der Funktion AutoSupport OnDemand und der Funktion AutoSupport Remote Diagnostics
* Lieferparameter, die von der konfigurierten Liefermethode abhängig sind:
+
** Bereitstellungsmethode ist E-Mail (SMTP): Zieladresse, E-Mail-Relay-Server und Absender-E-Mail-Adresse werden angezeigt
** Die Liefermethode lautet HTTP oder HTTPS:
+
*** Direkte Verbindung – Ziel-IP-Adresse wird angezeigt
*** Proxy-Serververbindung: Host-Adresse, Portnummer und Authentifizierungsdetails werden angezeigt
*** Automatische Proxy-Konfigurationsskript (PAC)-Verbindung – der Speicherort des Skripts wird angezeigt




* Täglich und wöchentlich bevorzugte Zeitbereiche von AutoSupport
* Informationen über die ASUP Funktionen, die Seriennummer des Gehäuses und die konfigurierten täglichen und wöchentlichen Zeitpläne




== Syntax

[source, cli]
----
show storageArray autoSupport
----


== Parameter

Keine.



=== Beispiele

[listing]
----

  SMcli -n Array1 -c "show storageArray autoSupport;"

   The AutoSupport feature is enabled on this storage array.
   The AutoSupport OnDemand feature is enabled on this storage array.
   The AutoSupport Remote Diagnostics feature is enabled on this storage array.

  Delivery Method: Email (SMTP)
    Destination email address: autosupport@netapp.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: Email (SMTP)
    Destination email address: destination1@example.com, destination2@example.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: 52428800

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: Unlimited

   The AutoSupport daily schedule preferred time range is from 12:00 AM to 01:00 AM.
   The AutoSupport weekly schedule preferred time range is from 10:00 PM to 11:00 PM on Thursday, Saturday.

   AutoSupport Capable  AutoSupport OnDemand Capable  Chassis Serial Number  Daily Schedule  Weekly Schedule
   Yes (enabled)        Yes                           SX94500434             12:55 AM        10:08 PM on Thursdays

   SMcli completed successfully.
----


== Minimale Firmware-Stufe

8.40
