---
permalink: commands-a-z/show-syncmirror-candidates.html 
sidebar: sidebar 
keywords: show, synchronous, mirror, volume, candidates 
summary: Der Befehl show SyncMirror Candidate gibt Informationen über die Kandidaten-Volumes auf einem Remote-Speicher-Array zurück, die Sie als sekundäre Volumes in einer Konfiguration mit synchronous Mirroring verwenden können. 
---
= Kandidaten für synchrone Spiegelungsvolumes anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show syncMirror candidates` Der Befehl gibt Informationen zu den Kandidaten-Volumes auf einem Remote-Speicher-Array zurück, die Sie als sekundäre Volumes in einer synchronen Spiegelung-Konfiguration verwenden können.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage Array, mit einigen Einschränkungen. Wenn Sie den Befehl im E2700 oder E5600 Array ausführen, gelten keine Einschränkungen.

[NOTE]
====
Dieser Befehl wird auf Plattformen E4000, E2800, E5700, EF600 und EF300 nicht unterstützt.

====


== Rollen

K. A.



== Kontext

[NOTE]
====
In früheren Versionen dieses Befehls war die Feature-ID `remoteMirror`. Diese Feature-ID ist nicht mehr gültig und wird durch ersetzt `syncMirror`.

====


== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[show syncMirror candidates primary="_volumeName_"
remoteStorageArrayName="_storageArrayName_"]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`primary`
 a| 
Der Name des lokalen Volumes, den Sie für das primäre Volume im Remote-gespiegelten Paar möchten. Schließen Sie den primären Volumennamen in doppelte Anführungszeichen (" ").



 a| 
`remoteStorageArrayName`
 a| 
Das Remote-Storage-Array, das mögliche Volumes für ein sekundäres Volume enthält. Wenn der Name des Remote-Storage-Arrays Sonderzeichen enthält, müssen Sie auch den Namen des Remote-Storage-Arrays in doppelte Anführungszeichen („ “) einschließen.

|===


== Minimale Firmware-Stufe

5.40
