---
permalink: commands-a-z/show-storagearray-unconfiguredinitiators.html 
sidebar: sidebar 
keywords: show, unconfigured, initiators 
summary: Der Befehl show storageArray unconfiguredInitiatoren gibt eine Liste von Initiatoren zurück, die vom Storage Array erkannt wurden, aber noch nicht in der Topologie des Storage-Arrays konfiguriert sind. 
---
= Nicht konfigurierte Initiatoren anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show storageArray unconfiguredInitiators` Der Befehl gibt eine Liste der Initiatoren zurück, die vom Storage-Array erkannt wurden, jedoch noch nicht in der Topologie des Storage-Arrays konfiguriert sind.



== Unterstützte Arrays

Dieser Befehl gilt für einzelne E4000, E2800, E5700, EF600, EF300, EF50 und EF80 Speicherarrays. Er funktioniert nicht auf E2700 oder E5600 Speicherarrays.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage Array auszuführen, müssen Sie die Rolle Storage Admin oder Storage Monitor haben.

Dieser Befehl ersetzt das link:show-storagearray-unconfigurediscsiinitiators.html["Storage Array undconfig - IscsiInitiatoren anzeigen"] Befehl.



== Syntax

[source, cli]
----
show storageArray unconfiguredInitiators
----


== Parameter

Keine.



== Minimale Firmware-Stufe

8.50
