---
permalink: commands-a-z/show-ssd-cache.html 
sidebar: sidebar 
keywords: show, ssd, cache 
summary: Mit dem Befehl show ssdCache werden Informationen zum SSD-Cache angezeigt. 
---
= SSD-Cache anzeigen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `show ssdCache` Mit Befehl werden Informationen zum SSD-Cache angezeigt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000-, E2800-, E5700-, EF600-, EF300-, EF50- oder EF80-Speicherarray auszuführen, müssen Sie die Support Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]]
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, für den Sie Informationen abrufen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen oder Ziffern hat, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


[[notes]]
== Hinweise

Dieser Befehl gibt die SSD-Cache-Informationen zurück, die diesem Beispiel ähnlich sind.

[listing]
----
SSD Cache name: my_cache

Status:                              Optimal
Type:                                Read Only
I/O characteristic type:             File System
Maximum capacity allowed:            1,862.645 GB
Current capacity:                    557.792 GB
Additional capacity allowed          1,304.852 GB
Drive capacities:                    All 278.896 GB
Quality of Service (QoS) Attributes
   Security capable:                 No
   Secure:                           No
   Data Assurance (DA) capable:      No
Associated drives:

Tray     Slot
0        4
0        11
Volumes using SSD cache:             volume_test
----


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
