---
permalink: commands-a-z/show-storagearray-lunmappings.html 
sidebar: sidebar 
keywords: show, storage, array, lun, map 
summary: 'Der Befehl show storageArray lunMappings gibt Informationen aus dem Speicher-Array-Profil über die LUN (Logical Unit Number) oder Namespace ID (NSID)-Zuordnungen im Speicher-Array zurück.' 
---
= Anzeigen der LUN-Zuordnungen des Speicherarrays
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `show storageArray lunMappings` Der Befehl gibt Informationen aus dem Speicher-Array-Profil über die Zuordnung der Logical Unit Number (LUN) oder Namespace ID (NSID) im Speicher-Array zurück.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Storage Admin“ oder „Storage Monitor“ lauten.



== Kontext

Es werden immer standardmäßige Gruppen-LUN oder NSID-Zuordnungen angezeigt. Wenn Sie diesen Befehl ohne Parameter ausführen, gibt dieser Befehl alle LUN- oder NSID-Zuordnungen zurück.



== Syntax

[listing, subs="+macros"]
----
show storageArray lunMappings (host pass:quotes[["_hostName_"]] |
hostgroup pass:quotes[["_hostGroupName_"]])
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`host`
 a| 
Der Name eines bestimmten Hosts, für den die LUN- oder NSID-Zuordnungen angezeigt werden sollen. Schließen Sie den Hostnamen in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.



 a| 
`hostGroup`
 a| 
Der Name einer bestimmten Host-Gruppe, für die die LUN- oder NSID-Zuordnungen angezeigt werden sollen. Schließen Sie den Namen der Host-Gruppe in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]).

|===


== Hinweise

Dieser Befehl gibt Informationen zur Hosttopologie zurück, die diesem Beispiel ähnlich sind.

[listing]
----
MAPPINGS (Storage Partitioning - Enabled (0 of 16 used))
VOLUME NAME  LUN  CONTROLLER  ACCESSIBLE BY  VOLUME STATUS
Access Volume 7   A,B         Default Group  Optimal
21           21   B           Default Group  Optimal
22           22   B           Default Group  Optimal
----


== Minimale Firmware-Stufe

6.10
