---
permalink: commands-a-z/show-allsnmpcommunities.html 
sidebar: sidebar 
keywords: show, snmp, communities 
summary: 'Der Befehl show allSnmpCommunities gibt Informationen über die für das Speicher-Array definierten Simple Network Management Protocol (SNMP)-Communities zurück. SNMP-Communitys sind Sammlungen von Geräten wie Routern, Switches, Druckern, Speichergeräten, Gruppiert, um die Geräte zu verwalten und zu überwachen.' 
---
= Zeigen Sie SNMP-Communitys an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `show allSnmpCommunities` Der Befehl gibt Informationen zu den für das Storage-Array definierten SNMP-Communities (Simple Network Management Protocol) zurück. SNMP-Communitys sind Sammlungen von Geräten wie Routern, Switches, Druckern, Speichergeräten, Gruppiert, um die Geräte zu verwalten und zu überwachen.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Storage-Array. Der Betrieb erfolgt nicht auf E2700 oder E5600 Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, müssen Sie über die Rolle Storage-Admin oder -Support-Admin oder Storage-Monitor verfügen.



== Kontext

Die zurückgegebenen Informationen umfassen Folgendes:

* Die Gesamtzahl der Communitys
* Die Gesamtzahl der Trap-Ziele
* Die Namen der SNMP-Communitys




== Syntax

[listing, subs="+macros"]
----
show pass:quotes[(allSnmpCommunities |
snmpCommunity communityName="_snmpCommunityName_"] |
snmpCommunities pass:quotes[[_snmpCommunityName1_ ... _snmpCommunityNameN_]])
[summary]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`allSnmpCommunities`
 a| 
Dieser Parameter gibt Informationen über alle SNMP-Communitys im Speicher-Array zurück.



 a| 
`communityName`
 a| 
Der Name der SNMP-Community, für die Sie Informationen abrufen möchten. Schließen Sie den SNMP-Community-Namen in doppelte Anführungszeichen (" ").



 a| 
`snmpCommunities`
 a| 
Die Namen mehrerer SNMP-Communities, für die Sie Informationen abrufen möchten. Geben Sie die Namen der SNMP-Communitys ein, indem Sie folgende Regeln verwenden:

* Schließen Sie alle Namen in eckige Klammern ([ ]).
* Schließen Sie jeden dieser Namen in doppelte Anführungszeichen (" ").
* Trennen Sie jede der Namen mit einem Leerzeichen.




 a| 
`summary`
 a| 
Dieser Parameter gibt eine Liste der Gesamtzahl der SNMP-Communitys und der Gesamtzahl der SNMP-Trap-Ziele zurück. Wenn Sie diesen Parameter verwenden, werden alle Detailinformationen nicht angezeigt.

|===


== Hinweise

SNMP unterstützt eine oder mehrere _Communities_ zu denen Manager und verwaltete Geräte gehören. SNMP-Anforderungen enthalten eine _Community-Zeichenfolge_ in den Datenpaketen, die über das Netzwerk übergeben werden und als Rohkennwort fungieren. SNMP-Agenten können GET- oder SET-Anforderungen mit einer nicht erkannten Community-Zeichenfolge ablehnen. Eine Community-Zeichenfolge ist auch in TRAP-Benachrichtigungen enthalten, die ebenfalls vom Agenten an den Manager gesendet werden.

Der eingebettete SNMP-Agent unterstützt SOWOHL IPV4 als auch IPV6.

Dieser Befehl gibt SNMP-Community-Informationen zurück, die diesem Beispiel ähnlich sind.

[listing]
----
SNMP COMMUNITIES------------------------------
SUMMARY
   Total SNMP Communities: 2
   Total SNMP Trap Destinations: 1
DETAILS
   SNMP Community: TestComm1
   SNMP Permission: Read Only
      Associated Trap Destination:
      Trap Receiver IP Address: 10.113.173.133
      Send Authentication Failure Traps: true
   SNMP Community: Test2
   SNMP Permission: Read Only
      Associated Trap Destination:
----


== Minimale Firmware-Stufe

8.30
