---
permalink: commands-a-z/smcli-autosupportschedule-show.html 
sidebar: sidebar 
keywords: display, autosupport, message, collection, schedule 
summary: Der Befehl SMcli -autoSupportSchedule show zeigt den Zeitplan für die Erfassung und Verarbeitung von täglichen und wöchentlichen AutoSupport Meldungen an. 
---
= Zeigen Sie den Zeitplan für die Erfassung von AutoSupport-Meldungen an
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `SMcli -autoSupportSchedule show` Der Befehl zeigt den Zeitplan für die Erfassung und Verarbeitung von täglichen und wöchentlichen AutoSupport Meldungen an.



== Unterstützte Arrays

Dieser Befehl gilt für alle E2700 und E5600 Storage-Arrays gleichzeitig in der Management-Domäne. Dies gilt nicht für E2800 oder E5700 Storage-Arrays.



== Kontext

[NOTE]
====
Dieser Befehl ist ein SMcli-Befehl und kein Skript-Befehl. Sie müssen diesen Befehl über eine Befehlszeile ausführen. Sie können diesen Befehl nicht aus dem Skript-Editor in der Speicher-Management-Software ausführen.

====
Beachten Sie Folgendes bei der Planung der automatischen Support Bundle-Sammlung:

* Wenn AutoSupport aktiviert ist, sendet die Managementsoftware sowohl tägliche AutoSupport Meldungen als auch wöchentliche AutoSupport-Meldungen.
* Die Verwaltungssoftware wählt zufällig eine Tageszeit für tägliche und wöchentliche Nachrichten sowie einen Wochentag für wöchentliche Nachrichten aus.
* Die Managementsoftware versucht alle, sicherzustellen, dass keine zwei Storage Arrays innerhalb einer Management-Domäne gleichzeitig geplante AutoSupport-Nachrichten senden.
* Verwenden der `SMcli -autoSupportSchedule reset` Sie können einen Bereich (Granularität auf Stundenebene) der bevorzugten Zeiten angeben, um sowohl tägliche als auch wöchentliche Meldungen für die Storage Arrays in Ihrer Management-Domäne zu senden. Für den Zeitplan für wöchentliche Meldungen verwenden Sie den Befehl, um die bevorzugten Wochentage auszuwählen.




== Syntax

[listing]
----
SMcli -autoSupportSchedule show
----


== Parameter

Keine.



== Minimale Firmware-Stufe

8.25



== Beispiel

Die Ausgabe zeigt sowohl die bevorzugten Zeitbereiche, gefolgt vom täglichen und wöchentlichen Zeitplan.

[NOTE]
====
Wenn Sie nicht bevorzugte Zeitbereiche für beide Zeitpläne und bevorzugten Wochentage auswählen, zeigt dieser Befehl den täglichen Zeitplan und den wöchentlichen Zeitplan an, den die Speichermanagement-Software zufällig ausgewählt hat.

====
[listing]
----
SMcli -autoSupportSchedule show
The AutoSupport daily schedule preferred time range is from 12:00 AM to 01:00 AM.
The AutoSupport weekly schedule preferred time range is from 10:00 PM to 11:00 PM on Thursday, Saturday.

Name           Daily Schedule         Weekly Schedule
Accounting     12:55 AM               10:08 PM on Thursdays
Finance        12:02 AM               10:30 PM on Saturdays

SMcli completed successfully.
----