---
permalink: commands-a-z/start-ssdcache-locate.html 
sidebar: sidebar 
keywords: start, ssd, cache, locate 
summary: 'Der Befehl Start ssdCache Locate identifiziert die Solid State Disks (SSDs), die logisch gruppiert sind, um den SSD-Cache zu bilden, indem die Kontrollleuchten auf den SSDs blinken.' 
---
= SSD-Cache-Lokalisierung starten – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start ssdCache locate` Der Befehl identifiziert die Solid State Disks (SSDs), die logisch gruppiert sind, um den SSD-Cache zu bilden, indem die Kontrolllampen auf den SSDs blinkt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000-, E2800-, E5700-, EF600-, EF300-, EF50- oder EF80-Speicherarray auszuführen, müssen Sie die Support Admin-Rolle haben.



[[context]]
== Kontext

Verwenden Sie die `stop ssdCache locate` Befehl zum Ausschalten der Kontrollleuchten auf den Laufwerken.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, den Sie suchen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
