---
permalink: commands-a-z/start-drivechannel-locate.html 
sidebar: sidebar 
keywords: start, drive, channel, locate 
summary: Der Befehl Start driveChannel Locate identifiziert die Laufwerksfächer, die mit einem bestimmten Laufwerkskanal verbunden sind, indem die Anzeigeleuchten für das Laufwerksfach eingeschaltet werden, das mit dem Laufwerkskanal verbunden ist. 
---
= Starten Sie die Laufwerkskanalsuche – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start driveChannel locate` Der Befehl identifiziert die Laufwerksfächer, die mit einem bestimmten Laufwerkskanal verbunden sind, indem die Kontrollleuchten für das Laufwerksfach, das mit dem Laufwerkskanal verbunden ist, eingeschaltet werden.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Verwenden Sie die `stop driveChannel locate` Befehl zum Ausschalten der Kontrollleuchten auf dem Laufwerksfach



[[syntax]]
== Syntax

[source, cli]
----
start driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] locate
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`driveChannel`
 a| 
Die Identifikationsnummer des zu lokelenden Laufwerkskanals. Gültige Werte für die Identifikationsnummer für den Laufwerkskanal sind `1`, `2`, `3`, `4`, `5`, `6`, `7`, Oder `8`. Schließen Sie die ID-Nummer des Laufwerkskanals in eckige Klammern ([ ]).

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.10

7.15 fügt der Laufwerkskanalkennung ein Update hinzu.
