---
permalink: commands-a-z/start-volumegroup-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, volume, group, resource, provision 
summary: Der Befehl „Start VolumeGroup resourceProvisioning“ ermöglicht die Ressourcenbereitstellung für eine bestimmte Volume-Gruppe und startet einen asynchronen Vorgang zur Ressourcenbereitstellung auf jedem Volume der Volume-Gruppe. Für die Ressourcenbereitstellung müssen alle Laufwerke in der Volume-Gruppe die DELBE-Funktion von NVMe unterstützen. 
---
= Starten Sie die Bereitstellung von Volume-Gruppenressourcen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start volumeGroup resourceProvisioning` Befehl aktiviert die Ressourcenbereitstellung auf einer bestimmten Volume-Gruppe und startet einen asynchronen Vorgang zur Ressourcenbereitstellung auf jedem Volume in der Volume-Gruppe. Für die Ressourcenbereitstellung müssen alle Laufwerke in der Volume-Gruppe die DELBE-Funktion von NVMe unterstützen.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der EF600, EF300, EF50 und EF80 Systeme; sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem EF600-, EF300-, EF50- und EF80-Speicherarray auszuführen, müssen Sie über die Rollen Storage Admin oder Support Admin verfügen.



[[context]]
== Kontext

Um die Ressourcenbereitstellung für eine Volume-Gruppe zu deaktivieren, verwenden Sie den Befehl Full Provisioning mit der Option zum Deaktivieren der Ressourcenbereitstellung. Eine Volume-Gruppe wird bei der Erstellung als Ressource bereitgestellt, wenn alle Laufwerke DELBE-fähig und die Speicher-Arrays sind `resourceProvisionedVolumes` Einstellung lautet `true`.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup[_volumeGroupName_]] resourceProvisioning
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroupName`
 a| 
Die Volume-Gruppe, die die Ressourcenbereitstellung aktivieren soll. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

11.73
