---
permalink: commands-a-z/start-syncmirror-primary-synchronize.html 
sidebar: sidebar 
keywords: start, synchronous, mirror, synchronization 
summary: Der Befehl SyncMirror Primary Sync starten startet die Synchronisierung der synchronen Spiegelung. 
---
= Synchronisierung der synchronen Spiegelung starten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start syncMirror primary synchronize` Befehl startet die Synchronisierung der synchronen Spiegelung.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E4000, E2700, E5600, E2800 und E5700 Arrays, sofern alle SMcli-Pakete installiert sind.



== Rollen

Sie müssen über die Rolle Storage-Administrator verfügen, um diesen Befehl für ein E4000, E2800 oder E5700 Storage-Array auszuführen.



== Kontext

[NOTE]
====
In früheren Versionen dieses Befehls war die Feature-ID `remoteMirror`. Diese Feature-ID ist nicht mehr gültig und wird durch ersetzt `syncMirror`.

====


== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start syncMirror primary ["_volumeName_"]] synchronize
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`primary`
 a| 
Der Name des primären Volumes, für das die Synchronisierung gestartet werden soll. Schließen Sie den primären Volumennamen in doppelte Anführungszeichen (" ") innerhalb von eckigen Klammern ([ ]) ein.

|===


== Minimale Firmware-Stufe

6.10
