---
permalink: commands-a-z/start-drive-erase.html 
sidebar: sidebar 
keywords: start, drive, erase 
summary: Mit dem Befehl „Start Drive Lösch“ werden alle Daten von einem oder mehreren Laufwerken gelöscht. 
---
= Starten Sie das Löschen des Laufwerks
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `start drive erase` Durch Befehl werden alle Daten von einem oder mehreren Laufwerken gelöscht.



== Unterstützte Arrays

Dieser Befehl gilt für ein einzelnes E2800, E5700, EF600 oder EF300 Array. Das System läuft mit E2700 und E5600Storage-Arrays.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Rolle „Security Admin“ vorhanden sein.



== Kontext

Führen Sie diesen Befehl nur aus, wenn Sie alle Daten auf einem Laufwerk dauerhaft entfernen möchten. Wenn das Laufwerk sicher aktiviert ist, wird das angezeigt `start drive erase` Die Befehlsoption führt ein kryptografisches Löschen aus und setzt die Sicherheitsattribute des Laufwerks wieder auf sicher-fähig zurück.

[NOTE]
====
Der Löschvorgang kann nicht rückgängig gemacht werden. Stellen Sie sicher, dass Sie bei Verwendung dieses Befehls das richtige Laufwerk auswählen.

====


== Syntax

[listing, subs="+macros"]
----
start drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]] erase
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`drive`
 a| 
Geben Sie bei Laufwerksfächern mit hoher Kapazität den Wert für Fach-ID, die Fach-ID und den Wert für Steckplatz-ID für das Laufwerk an. Geben Sie für Laufwerksfächer mit geringer Kapazität den Wert für die Fach-ID und den Wert für die Steckplatz-ID für das Laufwerk an. Die Werte für Fach-ID sind `0` Bis `99`. Werte für Schublade-ID sind `1` Bis `5`.

Alle maximale Steckplatz-ID sind 24. Die Steckplatz-ID-Werte beginnen je nach Fachmodell bei 0 oder 1. Die Laufwerksfächer sind mit E2800 und E5700 Controllern kompatibel und besitzen die Steckplatz-ID-Nummern ab 0. Die Laufwerksfächer sind mit E2700 und E5600 Controllern kompatibel und verfügen ab 1 über die Steckplatz-ID.

Schließen Sie den Wert für Fach-ID, die Fach-ID und den Wert für die Steckplatz-ID in eckigen Klammern ([ ]) an.

[NOTE]
====
Die Laufwerksliste kann nicht alle Laufwerke im Speicher-Array enthalten, oder der Befehl wird abgelehnt.

====
|===


== Minimale Firmware-Stufe

11.70.1
