---
permalink: commands-a-z/start-volumegroup-import.html 
sidebar: sidebar 
keywords: start, volume, group, import 
summary: Mit dem Befehl „Start Volume Volume Group Import“ wird eine Volume-Gruppe in einen vollständigen Zustand verschoben, um eine neu eingeführte Volume-Gruppe dem neuen Storage Array zur Verfügung zu stellen. 
---
= Starten Sie den Import der Volume-Gruppe
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `start volumeGroup import` Der Befehl verschiebt eine Volume-Gruppe in einen vollständigen Status, um eine neu eingeführte Volume-Gruppe für das neue Storage Array verfügbar zu machen.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

Die Volume-Gruppe muss sich in einem exportierten Status oder in einem Forced-Status befinden, bevor Sie diesen Befehl ausführen. Wenn der Befehl erfolgreich ausgeführt wurde, ist die Volume-Gruppe funktionsfähig.

[NOTE]
====
Innerhalb der Volume-Gruppe können Sie keine Volumes verschieben, die den Funktionen zugeordnet sind, von einem Speicher-Array zu einem anderen Speicher-Array.

====


== Syntax

[listing, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] import
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die Sie importieren möchten. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


== Hinweise

Volumes auf höherer Ebene, die sich speziell auf Funktionen (synchrone Spiegelung, Volume-Kopie, Zuordnung und persistente Reservierungen) beziehen, werden im Rahmen des Importvorgangs entfernt.

Sie müssen den ausführen `show volumeGroup importDependencies` Befehl vor dem Ausführen des `start volumeGroup import` Befehl.



== Minimale Firmware-Stufe

7.10
