---
permalink: commands-a-z/start-volumegroup-import.html 
sidebar: sidebar 
keywords: start, volume, group, import 
summary: Mit dem Befehl „Start Volume Volume Group Import“ wird eine Volume-Gruppe in einen vollständigen Zustand verschoben, um eine neu eingeführte Volume-Gruppe dem neuen Storage Array zur Verfügung zu stellen. 
---
= Importieren von Volumegruppen starten – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start volumeGroup import` Der Befehl verschiebt eine Volume-Gruppe in einen vollständigen Status, um eine neu eingeführte Volume-Gruppe für das neue Storage Array verfügbar zu machen.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Die Volume-Gruppe muss sich in einem exportierten Status oder in einem Forced-Status befinden, bevor Sie diesen Befehl ausführen. Wenn der Befehl erfolgreich ausgeführt wurde, ist die Volume-Gruppe funktionsfähig.

[NOTE]
====
Innerhalb der Volume-Gruppe können Sie keine Volumes verschieben, die den Funktionen zugeordnet sind, von einem Speicher-Array zu einem anderen Speicher-Array.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] import
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die Sie importieren möchten. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


[[notes]]
== Hinweise

Volumes auf höherer Ebene, die sich speziell auf Funktionen (synchrone Spiegelung, Volume-Kopie, Zuordnung und persistente Reservierungen) beziehen, werden im Rahmen des Importvorgangs entfernt.

Sie müssen den ausführen `show volumeGroup importDependencies` Befehl vor dem Ausführen des `start volumeGroup import` Befehl.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10
