---
permalink: commands-a-z/start-diskpool-locate.html 
sidebar: sidebar 
keywords: start, disk pool, locate 
summary: Der Befehl „Start diskPool Locate“ identifiziert die Laufwerke, die logisch gruppiert sind, um den angegebenen Laufwerk-Pool zu bilden, indem die Kontrollleuchten auf den Laufwerken blinkt. 
---
= Starten Sie die Datenträgerpoolsuche – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start diskPool locate` Der Befehl identifiziert die Laufwerke, die logisch gruppiert sind, um den angegebenen Laufwerk-Pool zu bilden, indem die Kontrollleuchten auf den Laufwerken blinkt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

(Verwenden Sie das `stop diskPool locate` Befehl zum Ausschalten der Kontrollleuchten auf den Laufwerken.)



== Syntax

[source, cli, subs="+macros"]
----
start diskPool pass:quotes[[_diskPoolName_]] locate
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`diskPool`
 a| 
Der Name des Laufwerk-Pools, nach dem Sie suchen möchten. Schließen Sie den Namen des Disk-Pools in eckige Klammern ([ ]). Wenn der Disk-Pool-Name Sonderzeichen oder Ziffern hat, müssen Sie den Disk-Pool-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

7.83
