---
permalink: commands-a-z/start-diskpool-locate.html 
sidebar: sidebar 
keywords: start, disk pool, locate 
summary: Der Befehl „Start diskPool Locate“ identifiziert die Laufwerke, die logisch gruppiert sind, um den angegebenen Laufwerk-Pool zu bilden, indem die Kontrollleuchten auf den Laufwerken blinkt. 
---
= Starten Sie den Datenträgerpool suchen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `start diskPool locate` Der Befehl identifiziert die Laufwerke, die logisch gruppiert sind, um den angegebenen Laufwerk-Pool zu bilden, indem die Kontrollleuchten auf den Laufwerken blinkt.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

(Verwenden Sie das `stop diskPool locate` Befehl zum Ausschalten der Kontrollleuchten auf den Laufwerken.)



== Syntax

[listing, subs="+macros"]
----
start diskPool pass:quotes[[_diskPoolName_]] locate
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`diskPool`
 a| 
Der Name des Laufwerk-Pools, nach dem Sie suchen möchten. Schließen Sie den Namen des Disk-Pools in eckige Klammern ([ ]). Wenn der Disk-Pool-Name Sonderzeichen oder Ziffern hat, müssen Sie den Disk-Pool-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

7.83
