---
permalink: commands-a-z/start-storagearray-isnsserverrefresh.html 
sidebar: sidebar 
keywords: start, storage, array, isns, server, refresh 
summary: Mit dem Befehl „Storage Array starten“ isnsServerRefresh wird eine Aktualisierung der Netzwerkaddress-Informationen für den iSNS-Server initiiert. 
---
= Starten Sie die Aktualisierung des Speicherarray-iSNS-Servers – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start storageArray isnsServerRefresh` Befehl startet eine Aktualisierung der Netzwerkaddress-Informationen für den iSNS-Server.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Wenn der DHCP-Server gering oder nicht reagiert, kann der Aktualisierungsvorgang zwei bis drei Minuten dauern.

[NOTE]
====
Dieser Befehl gilt nur für IPv4.

====


[[syntax]]
== Syntax

[source, cli]
----
start storageArray isnsServerRefresh
----


[[parameter]]
== Parameter

Keine.



[[notes]]
== Hinweise

Wenn Sie den verwendet haben `set storageArray isnsIPv4ConfigurationMethod` Befehl zum Festlegen der Konfiguration, hat die Konfiguration jedoch nicht auf DHCP festgelegt und führt das aus `start storageArray isnsServerRefresh` Gibt einen Fehler zurück.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10
