---
permalink: commands-a-z/start-ssdcache-locate.html 
sidebar: sidebar 
keywords: start, ssd, cache, locate 
summary: 'Der Befehl Start ssdCache Locate identifiziert die Solid State Disks (SSDs), die logisch gruppiert sind, um den SSD-Cache zu bilden, indem die Kontrollleuchten auf den SSDs blinken.' 
---
= Starten Sie die SSD-Cache-Suche
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `start ssdCache locate` Der Befehl identifiziert die Solid State Disks (SSDs), die logisch gruppiert sind, um den SSD-Cache zu bilden, indem die Kontrolllampen auf den SSDs blinkt.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E2700, E5600, E2800, E5700, EF600- und EF300-Arrays, sofern alle SMcli-Pakete installiert sind



== Rollen

Sie müssen über die Rolle Support Admin verfügen, um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array ausführen zu können.



== Kontext

Verwenden Sie die `stop ssdCache locate` Befehl zum Ausschalten der Kontrollleuchten auf den Laufwerken.



== Syntax

[listing, subs="+macros"]
----
start ssdCache pass:quotes[[_ssdCacheName_]] locate
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, den Sie suchen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
