---
permalink: commands-a-z/start-storagearray-isnsserverrefresh.html 
sidebar: sidebar 
keywords: start, storage, array, isns, server, refresh 
summary: Mit dem Befehl „Storage Array starten“ isnsServerRefresh wird eine Aktualisierung der Netzwerkaddress-Informationen für den iSNS-Server initiiert. 
---
= Starten Sie die Aktualisierung des Speicherarray-iSNS-Servers – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start storageArray isnsServerRefresh` Befehl startet eine Aktualisierung der Netzwerkaddress-Informationen für den iSNS-Server.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich der Arrays E4000, E2700, E5600, E2800, E5700, EF600 und EF300, sofern alle SMcli-Pakete installiert sind.



== Rollen

Zur Ausführung dieses Befehls auf einem E4000, E2800, E5700, EF600 oder EF300 Storage-Array müssen Sie über die Storage-Administratorrolle verfügen.



== Kontext

Wenn der DHCP-Server gering oder nicht reagiert, kann der Aktualisierungsvorgang zwei bis drei Minuten dauern.

[NOTE]
====
Dieser Befehl gilt nur für IPv4.

====


== Syntax

[source, cli]
----
start storageArray isnsServerRefresh
----


== Parameter

Keine.



== Hinweise

Wenn Sie den verwendet haben `set storageArray isnsIPv4ConfigurationMethod` Befehl zum Festlegen der Konfiguration, hat die Konfiguration jedoch nicht auf DHCP festgelegt und führt das aus `start storageArray isnsServerRefresh` Gibt einen Fehler zurück.



== Minimale Firmware-Stufe

7.10
