---
permalink: commands-a-z/start-volumegroup-export.html 
sidebar: sidebar 
keywords: start, volume, group, export 
summary: Mit dem Befehl „Export von VolumeGruppen starten“ wird eine Volume-Gruppe in einen exportierten Status verschoben. 
---
= Volumegruppenexport starten – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start volumeGroup export` Der Befehl verschiebt eine Volume-Gruppe in einen exportierten Status.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Anschließend können Sie die Laufwerke, die die Volume-Gruppe enthalten, entfernen und die Laufwerke in einem anderen Speicher-Array neu installieren.

[CAUTION]
====
Führen Sie diese Schritte nicht aus, ohne zuerst die in xref:../get-started/learn-about-volume-group-migration.adoc[Erfahren Sie mehr über die Migration von Volume-Gruppen.] aufgeführten Schritte auszuführen.

====
[NOTE]
====
Innerhalb der Volume-Gruppe können Sie keine Volumes verschieben, die den Funktionen zugeordnet sind, von einem Speicher-Array zu einem anderen Speicher-Array.

====


[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] export
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, die exportiert werden soll. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


[[notes]]
== Hinweise

Wenn dieser Befehl erfolgreich ist, können Sie den ausführen `start volumeGroup import` Befehl zum Abschließen des Verschiebens der Volume-Gruppe in einen vollständigen Zustand, der die Volume-Gruppe für das neue Storage-Array verfügbar macht.

Wenn dieser Befehl nicht erfolgreich ist, da Hardwareprobleme den Abschluss des Exports verhindert haben, verwenden Sie den `set volumeGroup forceState` Befehl. Der `set volumeGroup forceState` Mit dem Befehl können Sie den verwenden `start volumeGroup import` Befehl zum Importieren einer Volume-Gruppe.

Nachdem sich die Volume-Gruppe in einem exportierten Status oder „Forced“ befindet, können Sie die Laufwerke, die die Volume-Gruppe enthalten, aus dem Storage-Array entfernen. Sie können die Laufwerke in einem anderen Speicher-Array neu installieren.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.10
