---
permalink: commands-a-z/start-volumegroup-locate.html 
sidebar: sidebar 
keywords: start, volume, group, locate 
summary: Mit dem Befehl „Volume-Gruppe starten“ werden die Laufwerke identifiziert, die logisch gruppiert sind, um die angegebene Volume-Gruppe zu bilden, indem die Anzeigeleuchten auf den Laufwerken blinkt. 
---
= Volume-Gruppensuche starten – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start volumeGroup locate` Der Befehl identifiziert die Laufwerke, die logisch gruppiert sind, um die angegebene Volume-Gruppe zu bilden, indem die Kontrollleuchten auf den Laufwerken blinkt.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

Verwenden Sie die `stop volumeGroup locate` Befehl zum Ausschalten der Kontrollleuchten auf den Laufwerken.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] locate
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volumeGroup`
 a| 
Der Name der Volume-Gruppe, für die Sie die Laufwerke suchen möchten, die zu dieser Volume-Gruppe gehören. Umschließen Sie den Namen der Volume-Gruppe in eckige Klammern ([ ]).

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

6.16
