---
permalink: commands-a-z/start-volume-initialization.html 
sidebar: sidebar 
keywords: start, volume, initialization 
summary: Der Befehl Start Volume Initialize startet die Formatierung eines Volumes in einem Speicher-Array. 
---
= Volume-Initialisierung starten – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `start volume initialize` Der Befehl beginnt die Formatierung eines Volumes in einem Speicher-Array.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Kontext

[NOTE]
====
Beim Formatieren eines Volumens wird ein lang laufender Vorgang gestartet, der nicht gestoppt werden kann.

====


== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`volume`
 a| 
Der Name eines Volumes, das formatiert werden soll. Umschließen Sie den Volumennamen in eckige Klammern ([ ]). Wenn der Volume-Name Sonderzeichen oder Zahlen hat, müssen Sie den Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Minimale Firmware-Stufe

6.10
