---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: Mit dem Befehl stoppspeicherArray driveFirmwareDownload wird ein Firmware-Download auf die Laufwerke in einem Speicher-Array gestoppt, das mit dem Befehl herunterladenstorageArray driveFirmware gestartet wurde. 
---
= Download der Firmware für Speicher-Array-Laufwerke stoppen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `stop storageArray driveFirmwareDownload` Durch Befehl wird ein Firmware-Download auf die Laufwerke in einem Speicher-Array beendet, das mit gestartet wurde `download storageArray driveFirmware` Befehl.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



== Kontext

Mit diesem Befehl wird kein Firmware-Download angehalten, der bereits auf ein Laufwerk ausgeführt wird. Mit diesem Befehl werden alle Firmware-Downloads auf Laufwerke angehalten, die auf den Download warten.



== Syntax

[source, cli]
----
stop storageArray driveFirmwareDownload
----


== Parameter

Keine.



== Minimale Firmware-Stufe

6.10
