---
permalink: commands-a-z/stop-storagearray-drivefirmwaredownload.html 
sidebar: sidebar 
keywords: stop, storage, array, drive, firmware, download 
summary: Mit dem Befehl stoppspeicherArray driveFirmwareDownload wird ein Firmware-Download auf die Laufwerke in einem Speicher-Array gestoppt, das mit dem Befehl herunterladenstorageArray driveFirmware gestartet wurde. 
---
= Beenden Sie den Download der Speicher-Array-Laufwerk-Firmware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `stop storageArray driveFirmwareDownload` Durch Befehl wird ein Firmware-Download auf die Laufwerke in einem Speicher-Array beendet, das mit gestartet wurde `download storageArray driveFirmware` Befehl.



== Unterstützte Arrays

Dieser Befehl gilt für alle einzelnen Storage-Arrays, einschließlich E2700, E5600, E2800, E5700 EF600 und EF300 Arrays, solange alle SMcli-Pakete installiert sind.



== Rollen

Um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array auszuführen, muss die Storage-Administratorrolle vorhanden sein.



== Kontext

Mit diesem Befehl wird kein Firmware-Download angehalten, der bereits auf ein Laufwerk ausgeführt wird. Mit diesem Befehl werden alle Firmware-Downloads auf Laufwerke angehalten, die auf den Download warten.



== Syntax

[listing]
----
stop storageArray driveFirmwareDownload
----


== Parameter

Keine.



== Minimale Firmware-Stufe

6.10
