---
permalink: commands-a-z/stop-asyncmirrorgroup-rolechange.html 
sidebar: sidebar 
keywords: cancel, asynchronous, mirror, group, role, reversal 
summary: Der Befehl stop Async MirrorGroup Rolechange bricht eine ausstehende Rollenumkehrung zwischen asynchronen Spiegelgruppen ab. 
---
= Asynchrone Spiegelgruppen-Rollenumkehr abbrechen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `stop asyncMirrorGroup rolechange` Befehl bricht einen ausstehenden Rollenumkehrvorgang zwischen asynchronen Spiegelgruppen ab.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600 und EF300 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600 oder EF300 Storage Array auszuführen, ist die Rolle Storage Admin erforderlich.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[stop asyncMirrorGroup [_asyncMirrorGroupName_]] rolechange
----


[[parameter]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`asyncMirrorGroup`
 a| 
Der Name der asynchronen Spiegelgruppe, für die oder die Sie den ausstehenden Rollenumkehrungsvorgang abbrechen möchten. Schließen Sie den Namen der asynchronen Spiegelgruppe in eckige Klammern ([ ]). Wenn der Name der asynchronen Spiegelgruppe Sonderzeichen enthält oder nur aus Zahlen besteht, müssen Sie den Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
