---
permalink: commands-a-z/stop-volumecopy-target-source.html 
sidebar: sidebar 
keywords: stop, volume, copy 
summary: Mit dem Befehl stop VolumeCopy Zielquelle wird ein Kopiervorgang angehalten. Dieser Befehl gilt für Snapshot-Volume-Kopierpaare. 
---
= Volumekopie stoppen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `stop volumeCopy target source` Mit dem Befehl wird ein Kopiervorgang angehalten. Dieser Befehl gilt für Snapshot-Volume-Kopierpaare.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[syntax]]
== Syntax

[source, cli, subs="+macros"]
----
pass:quotes[stop volumeCopy target [_targetName_]] source pass:quotes[[_sourceName_]]
----


[[parameters]]
== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`target`
 a| 
Der Name des Zielvolume, für das Sie einen Kopiervorgang beenden möchten. Umschließen Sie den Namen des Zielvolumens in eckigen Klammern ([ ]). Wenn der Name des Ziel-Volumes Sonderzeichen oder Zahlen hat, müssen Sie den Namen des Zielvolumens in doppelten Anführungszeichen („ “) in eckigen Klammern setzen.



 a| 
`source`
 a| 
Der Name des Quell-Volume, für das Sie einen Vorgang der Volume-Kopie anhalten möchten. Umschließen Sie den Namen des Quellvolumens in eckige Klammern ([ ]). Wenn der Name des Quell-Volumes Sonderzeichen oder Zahlen hat, müssen Sie den Namen des Quell-Volumes in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===