---
permalink: commands-a-z/stop-drivechannel-faultdiagnostics.html 
sidebar: sidebar 
keywords: stop, drive, channel, fault, isolation, diagnostics 
summary: Mit dem Befehl driveChannel faultDiagnostics wird die Diagnose der Festplattenkanal-Fehlereingrenzung angehalten, durch die der Befehl „Diagnose der Laufwerkanalfehler starten“ angehalten wird, bevor die Diagnose abgeschlossen wird. 
---
= Diagnose der Laufwerkkanal-Fehlerisolierung stoppen – SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der `stop driveChannel faultDiagnostics` Mit dem Befehl wird die Fehlerisolationsdiagnose des Laufwerkanals beendet, sodass der beendet wird `start drive channel fault isolation diagnostics` Befehl, bevor er abgeschlossen ist.



[[supported-arrays]]
== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Speichersystem, einschließlich der E4000, E2700, E5600, E2800, E5700, EF600, EF300, EF50 und EF80 Arrays, sofern alle SMcli Pakete installiert sind.



[[roles]]
== Rollen

Um diesen Befehl auf einem E4000, E2800, E5700, EF600, EF300, EF50 oder EF80 Storage-Array auszuführen, müssen Sie die Storage Admin-Rolle haben.



[[context]]
== Kontext

[NOTE]
====
Mit der Firmware-Version 8.10 wird das `stop driveChannel faultDiagnostics` Befehl ist veraltet.

====


[[syntax]]
== Syntax

[source, cli]
----
stop driveChannel faultDiagnostics
----


[[parameters]]
== Parameter

Keine.



[[notes]]
== Hinweise

Verwenden Sie die `start driveChannel faultDiagnostics` Befehl und das `save driveChannel faultDiagnostics` Befehl mit dem `stop driveChannel faultDiagnostics` Befehl. Diese Befehle sind erforderlich, um den Diagnosetest zu starten und die Testergebnisse in einer Datei zu speichern.

Sie können auch die anhalten `start driveChannel faultDiagnostics` Befehl jederzeit durch Drücken `Ctrl+C`.



[[minimum-firmware-level]]
== Minimale Firmware-Stufe

7.15
