---
permalink: commands-a-z/suspend-ssdcache.html 
sidebar: sidebar 
keywords: suspend, ssd cache 
summary: Mit dem Befehl ssdCache suspendieren wird die Zwischenspeicherung für alle Volumes, die den SSD-Cache nutzen, vorübergehend angehalten. 
---
= Unterbrechen Sie den SSD-Cache
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Der `suspend ssdCache` Befehl stoppt das Caching für alle Volumes, die den SSD-Cache verwenden, vorübergehend.



== Unterstützte Arrays

Dieser Befehl gilt für jedes einzelne Storage-Array, einschließlich E2700, E5600, E2800, E5700, EF600- und EF300-Arrays, sofern alle SMcli-Pakete installiert sind



== Rollen

Sie müssen über die Rolle Support Admin verfügen, um diesen Befehl für ein E2800, E5700, EF600 oder EF300 Storage-Array ausführen zu können.



== Kontext

Während das Caching angehalten wird, werden Lesevorgänge auf dem Host über die Basis-Volumes anstatt über den SSD Cache ausgeführt.



== Syntax

[listing, subs="+macros"]
----

pass:quotes[suspend ssdCache [_ssdCacheName_]]
----


== Parameter

[cols="2*"]
|===
| Parameter | Beschreibung 


 a| 
`ssdCache`
 a| 
Der Name des SSD-Caches, den Sie aussetzen möchten. Schließen Sie den SSD-Cache-Namen in eckige Klammern ([ ]). Wenn der SSD-Cache-Name Sonderzeichen oder Ziffern hat, müssen Sie den SSD-Cache-Namen in doppelte Anführungszeichen („ “) in eckigen Klammern setzen.

|===


== Hinweise

Um das Caching neu zu starten, verwenden Sie den `resume ssdCache` Befehl.



== Minimale Firmware-Stufe

7.84

11.80 bietet Unterstützung für EF600 und EF300 Arrays
